import type { LabelDocument, LabelObject } from "@/lib/document/schema";
import { getSubstrate } from "@/lib/finishes/types";
import { getFontFamily } from "@/lib/fonts/registry";
import { runPreflight } from "@/lib/preflight/rules";
import { getMaterial, getMaterialOption } from "./materials";
import { readEasyContent } from "./meta";

/**
 * §11 — the printer specification sheet: everything a label printer needs
 * to quote and produce the job, in their language (this is the one surface
 * where the PROPER technical terms belong). Pure text — copyable, and
 * bundled into the print-ready ZIP.
 */
/**
 * Every font family + weight the document actually uses (§20's "font
 * information"): "Archivo — weights 400, 600". Text is always outlined or
 * rasterized in the print files, so this is reference information for the
 * printer, not files they need to install.
 */
export function listDocumentFonts(doc: LabelDocument): string[] {
  const weightsByFamily = new Map<string, Set<number>>();
  const walk = (objects: readonly LabelObject[]): void => {
    for (const o of objects) {
      if (o.type === "group") walk(o.children);
      if (o.type !== "text") continue;
      const set = weightsByFamily.get(o.fontFamilyId) ?? new Set<number>();
      set.add(o.fontWeight);
      weightsByFamily.set(o.fontFamilyId, set);
    }
  };
  walk(doc.objects);
  return [...weightsByFamily.entries()]
    .map(([id, weights]) => {
      const name = getFontFamily(id)?.name ?? id;
      return `${name} — weight${weights.size === 1 ? "" : "s"} ${[...weights].sort((a, b) => a - b).join(", ")}`;
    })
    .sort();
}

export function buildSpecSheet(doc: LabelDocument, projectName: string): string {
  const content = readEasyContent(doc);
  const material = content ? getMaterial(content.meta.materialId) : undefined;
  const option =
    material && content
      ? getMaterialOption(material, content.meta.materialOptionId)
      : undefined;
  const substrate = getSubstrate(doc.substrateId);
  const whiteInk = runPreflight(doc).some((i) => i.ruleId === "white-ink-needed");

  const lines: string[] = [
    "LABEL SPECIFICATION",
    `Product: ${projectName}`,
    "",
    `Size: ${doc.label.widthMm.toFixed(1)} mm × ${doc.label.heightMm.toFixed(1)} mm (finished/trim)`,
    `Shape: ${
      doc.label.shape === "circle"
        ? "Circle"
        : doc.label.cornerRadiusMm > 0
          ? `Rectangle with ${doc.label.cornerRadiusMm.toFixed(1)} mm rounded corners`
          : "Rectangle"
    }`,
    `Bleed: ${doc.label.bleedMm.toFixed(1)} mm per side (included in the artwork)`,
    `Safe area: ${doc.label.safeMm.toFixed(1)} mm inset`,
  ];

  if (doc.label.seamGapMm !== null) {
    lines.push(`Gap between label ends on the container: ${doc.label.seamGapMm.toFixed(1)} mm`);
  }

  lines.push(
    "",
    `Material: ${
      material && option
        ? `${material.name} — ${option.name} (${substrate?.name ?? doc.substrateId})`
        : (substrate?.name ?? doc.substrateId)
    }`,
    `Durability: ${option?.durability ?? (substrate?.waterproof ? "waterproof film" : "paper")}`,
    "Adhesive: Permanent (standard pressure-sensitive)",
    "Print: Full color (CMYK)",
  );

  if (material?.rules.sheen === "gloss") lines.push("Finish: Gloss laminate");
  if (material?.rules.sheen === "matte") lines.push("Finish: Matte laminate");
  if (whiteInk) {
    lines.push(
      "White ink: REQUIRED as an underbase beneath the artwork on this transparent/metallic stock (see the light artwork areas).",
    );
  }
  if (option?.specialtyPrinter) {
    lines.push(`Note: ${option.name} is a specialty stock — confirm availability.`);
  }

  const vial = doc.vial;
  lines.push(
    "",
    `Container: cylindrical, ⌀ ${vial.diameterMm.toFixed(1)} mm body, ${vial.straightWallHeightMm.toFixed(1)} mm straight wall`,
    "Artwork: supplied as print-ready PDF at exact physical size with bleed and crop marks",
    "",
    "Quantity: ______ (fill in when ordering)",
    "",
    "Generated by Forge Labels. Screen previews of special materials are",
    "simulations; confirm material, finish, and white-ink handling with the",
    "printer before a production run.",
  );

  return lines.join("\n");
}
