"use client";

import * as React from "react";
import { useRouter } from "next/navigation";
import { getMaterial, getMaterialOption } from "@/lib/easy/materials";
import { recommendTemplates, type Recommendation } from "@/lib/easy/recommend";
import {
  buildEasyDocument,
  DEFAULT_ENABLED,
  defaultEasyFields,
} from "@/lib/easy/create-doc";
import { ensureEasyFonts } from "@/lib/easy/fields";
import { clearDraft, type WizardDraft } from "@/lib/easy/draft";
import { measureTextHeightMm } from "@/lib/render/text-measure";
import { renderThumbnail } from "@/lib/export/raster";
import { getStorageAdapter } from "@/lib/storage";
import type { LabelDocument } from "@/lib/document/schema";
import { Badge } from "@/components/ui/badge";
import { Skeleton } from "@/components/ui/skeleton";
import { toast } from "@/components/ui/toaster";
import { StickyContinue, wizardPreset } from "./vial-step";
import { cn } from "@/lib/utils";

/**
 * Step 4 — pick a design. Every card is the user's ACTUAL label: their
 * vial size, material, palette, and words, generated by the layout engine
 * and rendered through the real export pipeline. Choosing one creates the
 * project and opens the Easy editor.
 */

interface Candidate {
  rec: Recommendation;
  doc: LabelDocument;
  thumbnail: string;
}

export function PickStep({
  draft,
  update,
}: {
  draft: WizardDraft;
  update: (patch: Partial<WizardDraft>) => void;
}) {
  const router = useRouter();
  const [candidates, setCandidates] = React.useState<Candidate[] | null>(null);
  const [creating, setCreating] = React.useState(false);
  const selectedId = draft.templateId;

  const preset = wizardPreset(draft);
  const material = draft.materialId ? getMaterial(draft.materialId) : undefined;

  React.useEffect(() => {
    if (!preset || !material) return;
    let alive = true;
    (async () => {
      // Real label dimensions so templates that need more room are skipped.
      const { createDocument } = await import("@/lib/document/defaults");
      const probe = createDocument({
        preset,
        diameterMm: draft.diameterMm,
        straightWallHeightMm: draft.straightWallHeightMm,
      });
      const recs = recommendTemplates({
        styleId: draft.styleId,
        preferDark: draft.preferDark ?? null,
        material,
        count: draft.auto ? 3 : 6,
        density: draft.density,
        wantsQr: draft.wantsQr,
        wantsBarcode: draft.wantsBarcode,
        hasLogo: draft.hasLogo,
        glass: draft.glass,
        labelWidthMm: probe.label.widthMm,
        labelHeightMm: probe.label.heightMm,
      });
      const option = getMaterialOption(
        material,
        draft.materialOptionId ?? material.defaultOptionId,
      );
      // Optional extras the user already answered come along for the ride —
      // an auto-flow QR link appears on all three finished designs.
      const enabled = new Set(DEFAULT_ENABLED);
      if (draft.fields?.qr?.trim()) enabled.add("qr");
      if (draft.fields?.subtitle?.trim()) enabled.add("subtitle");
      const built: Candidate[] = [];
      for (const rec of recs) {
        await ensureEasyFonts(rec.template);
        const doc = buildEasyDocument(
          {
            preset,
            diameterMm: draft.diameterMm,
            straightWallHeightMm: draft.straightWallHeightMm,
            templateId: rec.template.id,
            materialId: material.id,
            materialOptionId: option.id,
            intensity: draft.intensity,
            paletteId: rec.palette.id,
            styleId: draft.styleId,
            fields: defaultEasyFields(draft.fields),
            enabled,
          },
          measureTextHeightMm,
        );
        const thumbnail = await renderThumbnail(doc, 720);
        if (!alive) return;
        built.push({ rec, doc, thumbnail });
        setCandidates([...built]);
      }
    })().catch(() => {
      if (alive) toast.error("Couldn't build the previews — try going back a step.");
    });
    return () => {
      alive = false;
    };
    // Rebuild only when the inputs that shape the designs change.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [
    draft.presetId,
    draft.materialId,
    draft.materialOptionId,
    draft.styleId,
    draft.preferDark,
    draft.diameterMm,
    draft.straightWallHeightMm,
    draft.density,
    draft.wantsQr,
    draft.wantsBarcode,
    draft.glass,
  ]);

  const selected = candidates?.find((c) => c.rec.template.id === selectedId);

  async function create() {
    if (!selected) return;
    setCreating(true);
    try {
      const name =
        draft.fields?.["product-name"]?.trim() ||
        draft.fields?.brand?.trim() ||
        "My label";
      const project = await getStorageAdapter().createProject({
        name,
        doc: selected.doc,
      });
      clearDraft();
      router.push(`/easy/${project.id}`);
    } catch (err) {
      toast.error(
        "Couldn't create the project",
        err instanceof Error ? err.message : undefined,
      );
      setCreating(false);
    }
  }

  if (!preset || !material) return null;

  return (
    <div className="space-y-5">
      <p className="text-sm text-muted-foreground">
        Designed for your {preset.name.toLowerCase()} on{" "}
        {material.name.toLowerCase()} material — with your words already in
        place. You can change everything afterwards.
      </p>

      <ul className="grid gap-4 sm:grid-cols-2">
        {(candidates ?? []).map((candidate) => {
          const isSelected = candidate.rec.template.id === selectedId;
          return (
            <li key={candidate.rec.template.id}>
              <button
                type="button"
                onClick={() =>
                  update({
                    templateId: candidate.rec.template.id,
                    paletteId: candidate.rec.palette.id,
                  })
                }
                aria-pressed={isSelected}
                className={cn(
                  "w-full rounded-xl border-2 bg-surface p-3 text-left transition-colors",
                  isSelected
                    ? "border-primary bg-primary-subtle/30"
                    : "border-border hover:border-primary/40",
                )}
              >
                <div className="flex items-center justify-between gap-2">
                  <Badge variant={isSelected || candidate.rec.tag === "Best match" ? "default" : "secondary"}>
                    {candidate.rec.tag}
                  </Badge>
                  <span className="text-xs text-muted-foreground">
                    {candidate.rec.template.name}
                  </span>
                </div>
                <div className="mt-2 flex h-40 items-center justify-center overflow-hidden rounded-lg bg-canvas-backdrop p-3">
                  {/* eslint-disable-next-line @next/next/no-img-element -- generated preview */}
                  <img
                    src={candidate.thumbnail}
                    alt={`${candidate.rec.template.name} design preview`}
                    className="max-h-full max-w-full rounded-sm object-contain shadow-md"
                  />
                </div>
                <p className="mt-2 text-xs leading-relaxed text-muted-foreground">
                  {candidate.rec.reason}
                </p>
              </button>
            </li>
          );
        })}
        {!candidates &&
          Array.from({ length: 4 }).map((_, i) => (
            <li key={i}>
              <Skeleton className="h-56 rounded-xl" />
            </li>
          ))}
      </ul>

      <StickyContinue
        disabled={!selected}
        busy={creating}
        onClick={() => void create()}
        label="Use this design"
      />
    </div>
  );
}
