import type { Fill } from "@/lib/document/schema";
import { barcode, image, templateDoc, text } from "../authoring";
import type { TemplateDef } from "../types";

/**
 * Noir — pixel-exact reproductions of the owner's uploaded label artwork
 * (four raster masters). The artwork ships as a locked full-bleed plate
 * (public/templates/noir/*.png, variable regions healed out) and exactly
 * nine editable objects sit on top at the artwork's own positions:
 * product name, strength, CAT code, LOT / MFG / EXP values, composition,
 * the vertical batch number, and a real Code 128 barcode. Everything
 * else — brand, badge, notices, storage text, QR, frames — IS the
 * artwork and stays identical.
 *
 * Geometry lives in GEOMETRIES, measured in master-PNG pixels and
 * converted at the fixed physical size (60 × 30 mm, the artwork's own
 * 2:1). The numbers were derived by closed-loop calibration: each field
 * was rendered through the real export pipeline and its ink compared
 * against the master's until positions and sizes coincide. The masters
 * are raster (no font data), so overlay text uses the closest bundled
 * faces: Inter 700 for the display text, Archivo Narrow 400 for the
 * condensed data text. Sizes below the house 3.5 pt floor reproduce the
 * artwork's own microtext (templates.test.ts carves this family out).
 */

interface FieldGeom {
  /** Ink-box center in master px. */
  cx: number;
  cy: number;
  /** Text box width in master px (wide enough that seeded text never wraps). */
  w: number;
  /** Font size in points. */
  pt: number;
  /** Line height (multi-line fields). */
  lh?: number;
}

interface Geometry {
  /** Master pixel width (pre-bleed) — sets the px→mm scale. */
  masterPx: number;
  /** Healed plate dimensions (with bleed) for naturalWidthPx/HeightPx. */
  plate: [number, number];
  product: FieldGeom;
  strength: FieldGeom;
  cat: FieldGeom;
  lot: FieldGeom;
  mfg: FieldGeom;
  exp: FieldGeom;
  composition: FieldGeom;
  /** Vertical batch: w = run length along the reading direction. */
  batch: FieldGeom;
  /** Barcode bars: [cx, cy, runPx, barPx] (rotated 90°). */
  barcode: [number, number, number, number];
}

// Regenerated by the calibration loop during authoring; hand-edits to
// individual numbers are fine afterwards (px, master coordinate space).
// __NOIR_GEOMETRY_START__
const GEOMETRIES: Record<"core" | "cryo" | "spectral" | "grid", Geometry> = {
  core: {
    masterPx: 1774,
    plate: [1892, 1005],
    product: { cx: 898, cy: 384.5, w: 760, pt: 7.6, lh: 1.1 },
    strength: { cx: 888, cy: 534, w: 540, pt: 6.48 },
    cat: { cx: 953.5, cy: 672, w: 380, pt: 2.84 },
    lot: { cx: 1519, cy: 150.5, w: 200, pt: 2.87 },
    mfg: { cx: 1518, cy: 230.5, w: 200, pt: 3.34 },
    exp: { cx: 1518, cy: 313.5, w: 200, pt: 3.34 },
    composition: { cx: 299, cy: 597.5, w: 310, pt: 2.41, lh: 1.234 },
    batch: { cx: 1711, cy: 416, w: 240, pt: 3.08 },
    barcode: [1651, 413, 516.2, 84.7],
  },
  cryo: {
    masterPx: 1774,
    plate: [1892, 1005],
    product: { cx: 880.5, cy: 350.5, w: 760, pt: 7.5, lh: 1.189 },
    strength: { cx: 882.5, cy: 523, w: 540, pt: 6.46 },
    cat: { cx: 941, cy: 710.5, w: 380, pt: 3.05 },
    lot: { cx: 1483, cy: 100, w: 200, pt: 2.87 },
    mfg: { cx: 1483, cy: 180, w: 200, pt: 3.22 },
    exp: { cx: 1483, cy: 265, w: 200, pt: 3.25 },
    composition: { cx: 314, cy: 617.5, w: 310, pt: 2.5, lh: 1.229 },
    batch: { cx: 1717, cy: 426, w: 240, pt: 3.29 },
    barcode: [1630.5, 422.5, 607.3, 95.8],
  },
  spectral: {
    masterPx: 1536,
    plate: [1638, 870],
    product: { cx: 767.5, cy: 344, w: 658, pt: 6.76, lh: 1.314 },
    strength: { cx: 764, cy: 459, w: 468, pt: 5.67 },
    cat: { cx: 817, cy: 615.5, w: 329, pt: 2.99 },
    lot: { cx: 1303.5, cy: 101.5, w: 173, pt: 2.74 },
    mfg: { cx: 1297.5, cy: 180.5, w: 173, pt: 3.35 },
    exp: { cx: 1297.5, cy: 258, w: 173, pt: 3.35 },
    composition: { cx: 264, cy: 548.5, w: 268, pt: 2.6, lh: 1.324 },
    batch: { cx: 1482, cy: 390, w: 208, pt: 3.27 },
    barcode: [1416, 369, 508, 66],
  },
  grid: {
    masterPx: 1536,
    plate: [1638, 870],
    product: { cx: 760, cy: 324, w: 658, pt: 7.1, lh: 1.389 },
    strength: { cx: 773, cy: 456.5, w: 468, pt: 5.71 },
    cat: { cx: 819.5, cy: 625, w: 329, pt: 3.16 },
    lot: { cx: 1284.5, cy: 84.5, w: 173, pt: 2.79 },
    mfg: { cx: 1284.5, cy: 163, w: 173, pt: 3.16 },
    exp: { cx: 1284.5, cy: 239.5, w: 173, pt: 3.13 },
    composition: { cx: 264, cy: 540.5, w: 268, pt: 2.66, lh: 1.337 },
    batch: { cx: 1480.5, cy: 405, w: 208, pt: 3.32 },
    barcode: [1414, 370.5, 517.2, 70.6],
  },
};
// __NOIR_GEOMETRY_END__

interface Skin {
  id: "core" | "cryo" | "spectral" | "grid";
  name: string;
  description: string;
  plateUrl: string;
  background: string;
  productColor: string;
  valueColor: string;
  compositionColor: string;
  strengthColor: string;
  catColor: string;
  batchColor: string;
}

function noirTemplate(skin: Skin): TemplateDef {
  const g = GEOMETRIES[skin.id];
  const S = 60 / g.masterPx;
  const mm = (px: number) => Math.round(px * S * 1000) / 1000;
  const solid = (color: string): Fill => ({ type: "solid", color });

  const field = (
    name: string,
    f: FieldGeom,
    options: {
      color: string;
      textValue: string;
      display?: boolean;
      align?: "left" | "center" | "right";
      lines?: number;
      letterSpacingEm?: number;
      rotationDeg?: number;
    },
  ) => {
    const fontMm = f.pt * 0.3528;
    const lines = options.lines ?? 1;
    const lineHeight = f.lh ?? 1.15;
    return text({
      name,
      text: options.textValue,
      xMm: mm(f.cx),
      yMm: mm(f.cy),
      widthMm: mm(f.w),
      heightMm: Math.round(lines * fontMm * lineHeight * 100) / 100,
      fontSizePt: f.pt,
      fontFamilyId: options.display ? "inter" : "archivo-narrow",
      fontWeight: options.display ? 700 : 400,
      lineHeight,
      letterSpacingEm: options.letterSpacingEm ?? 0,
      align: options.align ?? "center",
      fill: solid(options.color),
      rotationDeg: options.rotationDeg ?? 0,
    });
  };

  return {
    id: `noir-exact-${skin.id}`,
    name: skin.name,
    brand: "NOIR PEPTIDES",
    description: skin.description,
    categories: ["pharma", "lab"],
    premium: false,
    presetId: "10ml-crimp",
    doc: templateDoc("10ml-crimp", {
      label: { style: "partial-wrap", widthMm: 60, heightMm: 30, bleedMm: 2, safeMm: 2 },
      background: { type: "solid", color: skin.background },
      substrateId: "white-pp",
      objects: [
        image({
          name: "Artwork plate (locked)",
          url: skin.plateUrl,
          xMm: 30,
          yMm: 15,
          widthMm: 64,
          heightMm: 34,
          naturalWidthPx: g.plate[0],
          naturalHeightPx: g.plate[1],
        }),
        field("Product name", g.product, {
          color: skin.productColor,
          display: true,
          lines: 2,
          textValue: "CJC-1295 +\nIpamorelin Blend",
        }),
        field("Strength", g.strength, {
          color: skin.strengthColor,
          display: true,
          textValue: "10 mg (5/5)",
        }),
        field("Catalog code", g.cat, {
          color: skin.catColor,
          letterSpacingEm: 0.1,
          textValue: "NP-CJC1295IPAM-10",
        }),
        field("LOT value", g.lot, {
          color: skin.valueColor,
          align: "left",
          textValue: "NP2405-001",
        }),
        field("MFG value", g.mfg, {
          color: skin.valueColor,
          align: "left",
          textValue: "05/24/2024",
        }),
        field("EXP value", g.exp, {
          color: skin.valueColor,
          align: "left",
          textValue: "05/24/2026",
        }),
        field("Composition", g.composition, {
          color: skin.compositionColor,
          align: "left",
          lines: 2,
          textValue: "CJC-1295 (DAC) – 5 mg\nIpamorelin – 5 mg",
        }),
        field("Batch (vertical)", g.batch, {
          color: skin.batchColor,
          rotationDeg: -90,
          textValue: "NP2405-001",
        }),
        barcode({
          name: "Barcode",
          value: "NP2405-001",
          symbology: "code128",
          showText: false,
          bgColor: null,
          fgColor: "#000000",
          xMm: mm(g.barcode[0]),
          yMm: mm(g.barcode[1]),
          widthMm: mm(g.barcode[2]),
          heightMm: mm(g.barcode[3]),
          rotationDeg: 90,
        }),
      ],
    }),
  };
}

const SKINS: Skin[] = [
  {
    id: "core",
    name: "Noir Core Black",
    description:
      "The owner's Core Black artwork, exact: silver-framed black label with hex badge, metallic strength band, and data column.",
    plateUrl: "/templates/noir/core.png",
    background: "#050505",
    productColor: "#f4f5f7",
    valueColor: "#eef0f3",
    compositionColor: "#c9cdd4",
    strengthColor: "#191c21",
    catColor: "#e8eaef",
    batchColor: "#d7dade",
  },
  {
    id: "cryo",
    name: "Noir Cryogenic",
    description:
      "The owner's Cryogenic artwork, exact: icy white label with blue hex badge, halftone strength band, and blue data rules.",
    plateUrl: "/templates/noir/cryo.png",
    background: "#fbfcfe",
    productColor: "#0c0e13",
    valueColor: "#101319",
    compositionColor: "#272b33",
    strengthColor: "#f5f8ff",
    catColor: "#10151d",
    batchColor: "#171b22",
  },
  {
    id: "spectral",
    name: "Noir Spectral",
    description:
      "The owner's Spectral artwork, exact: iridescent-framed black label with holographic accents and silver strength band.",
    plateUrl: "/templates/noir/spectral.png",
    background: "#050506",
    productColor: "#f4f5f7",
    valueColor: "#eef0f3",
    compositionColor: "#c9cdd4",
    strengthColor: "#191c21",
    catColor: "#e8eaef",
    batchColor: "#d7dade",
  },
  {
    id: "grid",
    name: "Noir Neural Grid",
    description:
      "The owner's Neural Grid artwork, exact: circuit-traced black label with electric-blue accents and glowing strength band.",
    plateUrl: "/templates/noir/grid.png",
    background: "#020409",
    productColor: "#f2f5f9",
    valueColor: "#edf2f8",
    compositionColor: "#c3cbd6",
    strengthColor: "#101418",
    catColor: "#dfe9f5",
    batchColor: "#d3dce8",
  },
];

export const NOIR_EXACT_TEMPLATES: TemplateDef[] = SKINS.map(noirTemplate);
