import { brandCaps, kickerSubtitle, productHero, strengthRow, volumeRow } from "./parts";
import type { EasyTemplateDef, RowDef } from "./types";
import { defineTemplate } from "./types";

/**
 * Premium biotechnology family (§8): engineered, modern, science-forward
 * branding — silver/chrome restraint, gradient energy, and genomic blues.
 * Mixed light/dark; several allow metallic or holographic material.
 */

function dataRow(slot: RowDef["slot"], overrides: Partial<RowDef> = {}): RowDef {
  return {
    slot,
    zone: "footer",
    font: "technical",
    sizeFactor: 0.044,
    minPt: 4,
    maxLines: 1,
    color: "muted",
    spacingBefore: 0.3,
    ...overrides,
  };
}

function noticeRow(overrides: Partial<RowDef> = {}): RowDef {
  return {
    slot: "notice",
    zone: "footer",
    font: "body",
    emphasis: true,
    sizeFactor: 0.044,
    minPt: 4,
    maxLines: 2,
    color: "text",
    letterSpacingEm: 0.08,
    casing: "uppercase",
    spacingBefore: 0.7,
    ...overrides,
  };
}

export const BIOTECHNOLOGY_TEMPLATES: readonly EasyTemplateDef[] = [
  defineTemplate({
    id: "biotech-silver",
    name: "Biotech Silver",
    family: "biotech-silver",
    familyName: "Biotech Silver",
    category: ["biotechnology", "clinical"],
    mood: ["silver", "wide-tracked", "restrained"],
    vibe: { premium: 2, clinical: 2, minimal: 1 },
    colorMode: "light",
    density: "standard",
    pairingId: "minimal-premium",
    recommendedGlass: ["frosted", "clear"],
    featured: true,
    align: "center",
    rows: [
      brandCaps({ align: "center", letterSpacingEm: 0.3 }),
      productHero(0.15, { align: "center" }),
      strengthRow({ align: "center", spacingBefore: 0.8 }),
      noticeRow({ align: "center" }),
      dataRow("lot", { align: "center", spacingBefore: 0.5 }),
      dataRow("batch", { align: "center" }),
      volumeRow("footer", { align: "center", spacingBefore: 0.35 }),
    ],
    codeCorner: "bottom-right",
    decor: [
      { kind: "divider", after: "brand", widthFactor: 0.2, strokePt: 0.8, fill: { role: "border" } },
    ],
    materials: ["plain", "matte", "glossy", "metallic"],
  }),
  defineTemplate({
    id: "genomic-blue",
    name: "Genomic Blue",
    family: "genomic-blue",
    familyName: "Genomic Blue",
    category: ["biotechnology", "clinical"],
    mood: ["banded", "approachable", "modern"],
    vibe: { clinical: 2, futuristic: 1, minimal: 1 },
    colorMode: "light",
    density: "standard",
    pairingId: "contemporary-skincare",
    recommendedGlass: ["cobalt", "clear"],
    align: "left",
    rows: [
      brandCaps(),
      { slot: "abbreviation", zone: "header", font: "technical", weight: 600, sizeFactor: 0.05, minPt: 4, maxLines: 1, color: "onAccent", chip: "fill", spacingBefore: 0.5 },
      productHero(0.155),
      { slot: "description", zone: "hero", font: "body", sizeFactor: 0.048, minPt: 4, maxLines: 2, color: "muted", spacingBefore: 0.7 },
      strengthRow({ spacingBefore: 0.7 }),
      noticeRow(),
      dataRow("lot", { spacingBefore: 0.45 }),
      { slot: "website", zone: "footer", font: "body", sizeFactor: 0.046, minPt: 4, maxLines: 1, color: "accent", spacingBefore: 0.45 },
      volumeRow("footer", { spacingBefore: 0.3 }),
    ],
    codeCorner: "bottom-right",
    decor: [
      { kind: "band", edge: "top", heightFactor: 0.05, fill: { role: "accent" } },
    ],
  }),
  defineTemplate({
    id: "cellular-gradient",
    name: "Cellular Gradient",
    family: "cellular-gradient",
    familyName: "Cellular Gradient",
    category: ["biotechnology", "glossy"],
    mood: ["gradient", "soft-energy", "contemporary"],
    vibe: { futuristic: 2, minimal: 1, playful: 1 },
    colorMode: "light",
    density: "standard",
    pairingId: "airy-modern",
    recommendedGlass: ["clear", "frosted"],
    align: "center",
    rows: [
      brandCaps({ align: "center", letterSpacingEm: 0.2 }),
      kickerSubtitle({ align: "center", spacingBefore: 0.8 }),
      productHero(0.16, { align: "center" }),
      strengthRow({ align: "center", spacingBefore: 0.8 }),
      noticeRow({ align: "center", sizeFactor: 0.042 }),
      dataRow("lot", { align: "center", spacingBefore: 0.45 }),
      volumeRow("footer", { align: "center", spacingBefore: 0.3 }),
    ],
    codeCorner: "bottom-right",
    decor: [
      { kind: "band", edge: "bottom", heightFactor: 0.16, fill: { gradient: true } },
    ],
    materials: ["plain", "glossy", "matte"],
  }),
  defineTemplate({
    id: "precision-chrome",
    name: "Precision Chrome",
    family: "precision-chrome",
    familyName: "Precision Chrome",
    category: ["biotechnology", "laboratory"],
    mood: ["chrome", "two-column", "machined"],
    vibe: { futuristic: 2, premium: 2 },
    colorMode: "light",
    density: "standard",
    pairingId: "engineered",
    recommendedGlass: ["clear", "frosted"],
    minHeightMm: 20,
    minWidthMm: 55,
    align: "left",
    split: { ratio: 0.56 },
    rows: [
      brandCaps({ letterSpacingEm: 0.2 }),
      productHero(0.13),
      strengthRow({ spacingBefore: 0.8 }),
      noticeRow({ sizeFactor: 0.042 }),
      dataRow("catalog", { zone: "header", column: "right", weight: 700, color: "text", spacingBefore: 0 }),
      dataRow("sku", { column: "right", spacingBefore: 0.3 }),
      dataRow("lot", { column: "right" }),
      dataRow("verification", { column: "right" }),
      dataRow("storage", { font: "body", column: "right", maxLines: 2, spacingBefore: 0.45 }),
      volumeRow("footer", { spacingBefore: 0.35 }),
    ],
    codeCorner: "bottom-right",
    decor: [
      { kind: "border", insetMm: 0.9, strokePt: 0.7, color: "border", minLabelHeightMm: 14 },
    ],
    materials: ["plain", "matte", "glossy", "metallic"],
  }),
  defineTemplate({
    id: "molecular-violet",
    name: "Molecular Violet",
    family: "molecular-violet",
    familyName: "Molecular Violet",
    category: ["biotechnology", "laboratory"],
    mood: ["violet", "orbital", "dark"],
    vibe: { futuristic: 3, premium: 1 },
    colorMode: "dark",
    density: "standard",
    pairingId: "cyber-orbit",
    recommendedGlass: ["opaque", "cobalt"],
    minHeightMm: 18,
    align: "center",
    rows: [
      { slot: "formula", zone: "header", font: "technical", sizeFactor: 0.044, minPt: 4, maxLines: 1, color: "muted", letterSpacingEm: 0.18, align: "center" },
      brandCaps({ align: "center", letterSpacingEm: 0.24, spacingBefore: 0.5 }),
      productHero(0.15, { align: "center" }),
      { slot: "abbreviation", zone: "hero", font: "display", sizeFactor: 0.065, minPt: 4.5, maxLines: 1, color: "accent", letterSpacingEm: 0.1, spacingBefore: 0.7 },
      strengthRow({ align: "center", spacingBefore: 0.7 }),
      noticeRow({ align: "center" }),
      dataRow("lot", { align: "center", spacingBefore: 0.45 }),
      dataRow("batch", { align: "center" }),
      volumeRow("footer", { align: "center", spacingBefore: 0.3 }),
    ],
    codeCorner: "bottom-right",
    codePlacement: "footer-center",
    decor: [
      { kind: "divider", after: "product-name", widthFactor: 0.3, strokePt: 0.9, fill: { role: "accent" } },
    ],
  }),
  defineTemplate({
    id: "bioengineering-green",
    name: "Bioengineering Green",
    family: "bioengineering-green",
    familyName: "Bioengineering Green",
    category: ["biotechnology", "laboratory"],
    mood: ["stripe", "utilitarian", "fresh"],
    vibe: { clinical: 2, futuristic: 1, botanical: 1 },
    colorMode: "light",
    density: "standard",
    pairingId: "tech-lab",
    recommendedGlass: ["clear", "amber"],
    align: "left",
    rows: [
      brandCaps({ letterSpacingEm: 0.1 }),
      productHero(0.15),
      strengthRow({ spacingBefore: 0.8 }),
      { slot: "storage", zone: "footer", font: "body", sizeFactor: 0.044, minPt: 4, maxLines: 2, color: "muted", spacingBefore: 0.4 },
      dataRow("retest", { spacingBefore: 0.35 }),
      dataRow("lot"),
      noticeRow({ sizeFactor: 0.042 }),
      volumeRow("footer", { spacingBefore: 0.3 }),
    ],
    codeCorner: "bottom-right",
    decor: [
      { kind: "stripe", edge: "left", widthFactor: 0.05, fill: { role: "accent" } },
      { kind: "divider", after: "strength", widthFactor: 0.5, strokePt: 0.7, fill: { role: "border" } },
    ],
  }),
  defineTemplate({
    id: "future-laboratory",
    name: "Future Laboratory",
    family: "future-laboratory",
    familyName: "Future Laboratory",
    category: ["biotechnology", "laboratory"],
    mood: ["display", "spaced", "sci-fi"],
    vibe: { futuristic: 3, bold: 1 },
    colorMode: "dark",
    density: "minimal",
    pairingId: "audiowide-energy",
    recommendedGlass: ["opaque", "clear"],
    minHeightMm: 16,
    align: "center",
    codePlacement: "footer-center",
    rows: [
      brandCaps({ align: "center", letterSpacingEm: 0.26 }),
      productHero(0.15, { align: "center", casing: "uppercase", letterSpacingEm: 0.06 }),
      strengthRow({ align: "center", font: "technical", spacingBefore: 0.9 }),
      noticeRow({ align: "center", sizeFactor: 0.042 }),
      dataRow("lot", { align: "center", spacingBefore: 0.5 }),
      volumeRow("footer", { align: "center", font: "technical", spacingBefore: 0.3 }),
    ],
    codeCorner: "bottom-right",
    decor: [
      { kind: "underline-hero", widthFactor: 0.4, strokePt: 1.2, fill: { gradient: true } },
    ],
  }),
  defineTemplate({
    id: "scientific-prism",
    name: "Scientific Prism",
    family: "scientific-prism",
    familyName: "Scientific Prism",
    category: ["biotechnology", "holographic"],
    mood: ["prism", "spectral", "protected"],
    vibe: { futuristic: 2, premium: 2 },
    colorMode: "light",
    density: "standard",
    pairingId: "grotesk-minimal",
    recommendedGlass: ["clear", "frosted"],
    minHeightMm: 18,
    align: "left",
    rows: [
      brandCaps({ letterSpacingEm: 0.16 }),
      productHero(0.15),
      { slot: "abbreviation", zone: "hero", font: "technical", weight: 700, sizeFactor: 0.055, minPt: 4.5, maxLines: 1, color: "accent", chip: "outline", spacingBefore: 0.8 },
      strengthRow({ color: "text", spacingBefore: 0.7 }),
      noticeRow(),
      dataRow("lot", { spacingBefore: 0.45 }),
      dataRow("batch"),
      volumeRow("footer", { spacingBefore: 0.3 }),
    ],
    codeCorner: "bottom-right",
    decor: [
      { kind: "frame-effect", thicknessFactor: 0.05, minLabelHeightMm: 15 },
    ],
    materials: ["plain", "glossy", "holographic"],
  }),
  defineTemplate({
    id: "clinical-technology",
    name: "Clinical Technology",
    family: "clinical-technology",
    familyName: "Clinical Technology",
    category: ["biotechnology", "clinical", "pharmaceutical"],
    mood: ["header-data", "practice", "exact"],
    vibe: { clinical: 3, futuristic: 1 },
    colorMode: "light",
    density: "standard",
    pairingId: "modern-clinical",
    recommendedGlass: ["clear", "cobalt"],
    align: "left",
    rows: [
      brandCaps(),
      { slot: "catalog", zone: "header", font: "technical", sizeFactor: 0.044, minPt: 4, maxLines: 1, color: "muted", spacingBefore: 0.35 },
      { slot: "batch", zone: "header", font: "technical", sizeFactor: 0.044, minPt: 4, maxLines: 1, color: "muted", spacingBefore: 0.25 },
      productHero(0.15),
      { slot: "strength", zone: "hero", font: "body", weight: 600, sizeFactor: 0.062, minPt: 4.5, maxLines: 1, color: "accent", chip: "outline", spacingBefore: 0.9 },
      noticeRow({ sizeFactor: 0.042 }),
      { slot: "website", zone: "footer", font: "body", sizeFactor: 0.044, minPt: 4, maxLines: 1, color: "muted", spacingBefore: 0.45 },
      { slot: "contact", zone: "footer", font: "body", sizeFactor: 0.042, minPt: 4, maxLines: 1, color: "muted", spacingBefore: 0.25 },
      volumeRow("footer", { spacingBefore: 0.3 }),
    ],
    codeCorner: "bottom-right",
    decor: [
      { kind: "band", edge: "bottom", heightFactor: 0.045, fill: { role: "accent" }, inset: true, minLabelHeightMm: 16 },
    ],
  }),
  defineTemplate({
    id: "biotech-reserve",
    name: "Biotech Reserve",
    family: "biotech-reserve",
    familyName: "Biotech Reserve",
    category: ["biotechnology", "luxury"],
    mood: ["reserve", "serif", "flagship"],
    vibe: { premium: 3, luxury: 1, clinical: 1 },
    colorMode: "dark",
    density: "standard",
    pairingId: "editorial-beauty",
    recommendedGlass: ["opaque", "amber"],
    premium: true,
    minHeightMm: 18,
    align: "center",
    rows: [
      brandCaps({ align: "center", letterSpacingEm: 0.24 }),
      productHero(0.16, { align: "center", minPt: 8 }),
      { slot: "purity", zone: "hero", font: "body", sizeFactor: 0.05, minPt: 4, maxLines: 1, color: "muted", letterSpacingEm: 0.1, spacingBefore: 0.8 },
      strengthRow({ align: "center", spacingBefore: 0.6 }),
      noticeRow({ align: "center", sizeFactor: 0.042 }),
      dataRow("lot", { align: "center", spacingBefore: 0.5 }),
      volumeRow("footer", { align: "center", spacingBefore: 0.3 }),
    ],
    codeCorner: "bottom-right",
    decor: [
      { kind: "border", insetMm: 1.1, strokePt: 0.7, color: "accent", minLabelHeightMm: 15 },
      { kind: "divider", after: "brand", widthFactor: 0.16, strokePt: 0.8, fill: { role: "accent" } },
    ],
  }),
] as const;
