import { footerRows } from "./core";
import type { EasyTemplateDef } from "./types";
import { defineTemplate } from "./types";

/** Clinical flagship families (§5): precise, trustworthy, data-forward. */

export const CLINICAL_TEMPLATES: readonly EasyTemplateDef[] = [
  defineTemplate({
    id: "clinical-blue",
    name: "Clinical Blue",
    family: "clinical-blue",
    familyName: "Clinical Blue",
    category: ["clinical", "plain"],
    mood: ["banded", "trustworthy", "badged"],
    vibe: { clinical: 3, bold: 1 },
    colorMode: "light",
    density: "standard",
    pairingId: "modern-clinical",
    recommendedGlass: ["clear"],
    featured: true,
    align: "left",
    rows: [
      { slot: "brand", zone: "header", font: "body", weight: 600, sizeFactor: 0.058, minPt: 4.5, maxLines: 1, color: "text", letterSpacingEm: 0.1, casing: "uppercase" },
      { slot: "product-name", zone: "hero", font: "display", sizeFactor: 0.15, minPt: 7, maxLines: 2, color: "text" },
      { slot: "subtitle", zone: "hero", font: "body", sizeFactor: 0.052, minPt: 4, maxLines: 1, color: "muted", spacingBefore: 0.8 },
      { slot: "strength", zone: "hero", font: "body", weight: 600, sizeFactor: 0.065, minPt: 4.5, maxLines: 1, color: "onAccent", chip: "fill", spacingBefore: 1.2 },
      { slot: "volume", zone: "footer", font: "body", sizeFactor: 0.05, minPt: 4, maxLines: 1, color: "muted" },
      ...footerRows(),
    ],
    codeCorner: "bottom-right",
    decor: [
      { kind: "band", edge: "top", heightFactor: 0.08, fill: { role: "accent" }, minLabelHeightMm: 13 },
    ],
  }),
  defineTemplate({
    id: "sterile-white",
    name: "Sterile White",
    family: "sterile-white",
    familyName: "Sterile White",
    category: ["clinical", "plain"],
    mood: ["sparse", "sterile", "tracked"],
    vibe: { clinical: 3, minimal: 3 },
    colorMode: "light",
    density: "minimal",
    pairingId: "pharmaceutical",
    recommendedGlass: ["clear"],
    align: "center",
    rows: [
      { slot: "brand", zone: "header", font: "body", weight: 600, sizeFactor: 0.05, minPt: 4.5, maxLines: 1, color: "muted", letterSpacingEm: 0.32, casing: "uppercase" },
      { slot: "product-name", zone: "hero", font: "display", sizeFactor: 0.13, minPt: 6.5, maxLines: 2, color: "text", letterSpacingEm: 0.04, casing: "uppercase" },
      { slot: "strength", zone: "hero", font: "body", weight: 600, sizeFactor: 0.06, minPt: 4.5, maxLines: 1, color: "text", letterSpacingEm: 0.12, spacingBefore: 1.2 },
      { slot: "subtitle", zone: "hero", font: "body", sizeFactor: 0.048, minPt: 4, maxLines: 1, color: "muted", letterSpacingEm: 0.08, spacingBefore: 0.7 },
      { slot: "volume", zone: "footer", font: "body", sizeFactor: 0.048, minPt: 4, maxLines: 1, color: "muted", letterSpacingEm: 0.08 },
      ...footerRows(),
    ],
    codeCorner: "bottom-right",
    decor: [],
  }),
  defineTemplate({
    id: "medical-index",
    name: "Medical Index",
    family: "medical-index",
    familyName: "Medical Index",
    category: ["clinical", "laboratory"],
    mood: ["indexed", "two-column", "data"],
    vibe: { clinical: 3, futuristic: 1 },
    colorMode: "light",
    density: "detailed",
    pairingId: "modern-clinical",
    recommendedGlass: ["clear", "cobalt"],
    featured: true,
    align: "left",
    minHeightMm: 22,
    minWidthMm: 45,
    split: { ratio: 0.56, divider: true },
    rows: [
      { slot: "brand", zone: "header", font: "body", weight: 600, sizeFactor: 0.055, minPt: 4.5, maxLines: 1, color: "accent", letterSpacingEm: 0.12, casing: "uppercase" },
      { slot: "product-name", zone: "hero", font: "display", sizeFactor: 0.15, minPt: 7, maxLines: 2, color: "text" },
      { slot: "subtitle", zone: "hero", font: "body", sizeFactor: 0.05, minPt: 4, maxLines: 2, color: "muted", spacingBefore: 0.8 },
      { slot: "strength", zone: "hero", font: "body", weight: 600, sizeFactor: 0.068, minPt: 4.5, maxLines: 1, color: "accent", spacingBefore: 1 },
      { slot: "volume", zone: "header", font: "technical", sizeFactor: 0.046, minPt: 4, maxLines: 1, color: "muted", column: "right" },
      { slot: "lot", zone: "header", font: "technical", sizeFactor: 0.046, minPt: 4, maxLines: 1, color: "muted", column: "right", spacingBefore: 0.4 },
      { slot: "expiry", zone: "header", font: "technical", sizeFactor: 0.046, minPt: 4, maxLines: 1, color: "muted", column: "right", spacingBefore: 0.3 },
      { slot: "verification", zone: "header", font: "technical", sizeFactor: 0.044, minPt: 4, maxLines: 1, color: "muted", column: "right", spacingBefore: 0.3 },
      { slot: "description", zone: "hero", font: "body", sizeFactor: 0.046, minPt: 4, maxLines: 3, color: "muted", column: "right" },
      { slot: "ingredients", zone: "footer", font: "body", sizeFactor: 0.042, minPt: 4, maxLines: 3, color: "muted", column: "right" },
      { slot: "directions", zone: "footer", font: "body", sizeFactor: 0.042, minPt: 4, maxLines: 2, color: "muted", column: "right", spacingBefore: 0.4 },
      { slot: "storage", zone: "footer", font: "body", sizeFactor: 0.042, minPt: 4, maxLines: 1, color: "muted", column: "right", spacingBefore: 0.4 },
      { slot: "warning", zone: "footer", font: "body", emphasis: true, sizeFactor: 0.044, minPt: 4, maxLines: 2, color: "text" },
      { slot: "website", zone: "footer", font: "body", sizeFactor: 0.046, minPt: 4, maxLines: 1, color: "accent", spacingBefore: 0.5 },
    ],
    codeCorner: "bottom-right",
    decor: [],
  }),
  defineTemplate({
    id: "dosage-band",
    name: "Dosage Band",
    family: "dosage-band",
    familyName: "Dosage Band",
    category: ["clinical", "plain"],
    mood: ["dosage", "banded", "bold"],
    vibe: { clinical: 2, bold: 2 },
    colorMode: "light",
    density: "standard",
    pairingId: "neutral-inter",
    recommendedGlass: ["clear", "amber"],
    align: "left",
    rows: [
      { slot: "brand", zone: "header", font: "body", weight: 600, sizeFactor: 0.055, minPt: 4.5, maxLines: 1, color: "muted", letterSpacingEm: 0.1, casing: "uppercase" },
      { slot: "product-name", zone: "hero", font: "display", sizeFactor: 0.16, minPt: 7, maxLines: 2, color: "text" },
      { slot: "strength", zone: "hero", font: "display", sizeFactor: 0.1, minPt: 5.5, maxLines: 1, color: "onAccent", chip: "fill", spacingBefore: 1.2 },
      { slot: "subtitle", zone: "hero", font: "body", sizeFactor: 0.05, minPt: 4, maxLines: 1, color: "muted", spacingBefore: 0.8 },
      { slot: "volume", zone: "footer", font: "body", weight: 500, sizeFactor: 0.05, minPt: 4, maxLines: 1, color: "muted" },
      ...footerRows(),
    ],
    codeCorner: "bottom-right",
    decor: [
      { kind: "band", edge: "bottom", heightFactor: 0.06, fill: { role: "accent" } },
    ],
  }),
  defineTemplate({
    id: "controlled-batch",
    name: "Controlled Batch",
    family: "controlled-batch",
    familyName: "Controlled Batch",
    category: ["clinical", "laboratory"],
    mood: ["batch", "registration", "marked"],
    vibe: { clinical: 3, futuristic: 1, minimal: 1 },
    colorMode: "light",
    density: "standard",
    pairingId: "pharmaceutical",
    recommendedGlass: ["clear", "cobalt"],
    align: "center",
    codePlacement: "footer-center",
    rows: [
      { slot: "brand", zone: "header", font: "body", weight: 600, sizeFactor: 0.052, minPt: 4.5, maxLines: 1, color: "text", letterSpacingEm: 0.2, casing: "uppercase" },
      { slot: "lot", zone: "header", font: "technical", sizeFactor: 0.044, minPt: 4, maxLines: 1, color: "muted", spacingBefore: 0.5 },
      { slot: "product-name", zone: "hero", font: "display", sizeFactor: 0.14, minPt: 6.5, maxLines: 2, color: "text" },
      { slot: "strength", zone: "hero", font: "body", weight: 600, sizeFactor: 0.065, minPt: 4.5, maxLines: 1, color: "accent", spacingBefore: 1 },
      { slot: "subtitle", zone: "hero", font: "body", sizeFactor: 0.048, minPt: 4, maxLines: 1, color: "muted", spacingBefore: 0.6 },
      { slot: "volume", zone: "footer", font: "body", sizeFactor: 0.048, minPt: 4, maxLines: 1, color: "muted" },
      { slot: "expiry", zone: "footer", font: "technical", sizeFactor: 0.044, minPt: 4, maxLines: 1, color: "muted", spacingBefore: 0.3 },
      { slot: "warning", zone: "footer", font: "body", emphasis: true, sizeFactor: 0.044, minPt: 4, maxLines: 2, color: "text", spacingBefore: 0.5 },
      { slot: "verification", zone: "footer", font: "technical", sizeFactor: 0.042, minPt: 4, maxLines: 1, color: "muted", spacingBefore: 0.3 },
      { slot: "website", zone: "footer", font: "body", sizeFactor: 0.046, minPt: 4, maxLines: 1, color: "muted", spacingBefore: 0.5 },
    ],
    codeCorner: "bottom-right",
    decor: [
      { kind: "corners", lengthMm: 2.6, strokePt: 0.9, color: "muted", insetMm: 1.2, minLabelHeightMm: 14 },
    ],
  }),
] as const;
