import type { ColorRole, EasyTemplateDef, RowDef } from "./types";
import { defineTemplate } from "./types";

/**
 * The original twelve archetypes, upgraded to the v2 template shape.
 * IDs are stable — stored documents reference them — and each keeps the
 * typography it shipped with via an equivalent font pairing.
 */

// Shared footer rows (small print) used by most archetypes.
export function footerRows(color: ColorRole = "muted"): RowDef[] {
  return [
    { slot: "description", zone: "hero", font: "body", sizeFactor: 0.055, minPt: 4.5, maxLines: 3, color: "muted", spacingBefore: 1.4 },
    { slot: "ingredients", zone: "footer", font: "body", sizeFactor: 0.045, minPt: 4, maxLines: 3, color },
    { slot: "directions", zone: "footer", font: "body", sizeFactor: 0.045, minPt: 4, maxLines: 2, color, spacingBefore: 0.6 },
    { slot: "storage", zone: "footer", font: "body", sizeFactor: 0.045, minPt: 4, maxLines: 1, color, spacingBefore: 0.6 },
    { slot: "warning", zone: "footer", font: "body", emphasis: true, sizeFactor: 0.045, minPt: 4, maxLines: 2, color: "text", spacingBefore: 0.6 },
    { slot: "lot", zone: "footer", font: "technical", sizeFactor: 0.045, minPt: 4, maxLines: 1, color, spacingBefore: 0.8 },
    { slot: "expiry", zone: "footer", font: "technical", sizeFactor: 0.045, minPt: 4, maxLines: 1, color, spacingBefore: 0.3 },
    { slot: "verification", zone: "footer", font: "technical", sizeFactor: 0.042, minPt: 4, maxLines: 1, color, spacingBefore: 0.3 },
    { slot: "website", zone: "footer", font: "body", sizeFactor: 0.05, minPt: 4, maxLines: 1, color, spacingBefore: 0.8 },
  ];
}

export const CORE_TEMPLATES: readonly EasyTemplateDef[] = [
  defineTemplate({
    id: "clinical-frame",
    name: "Clinical frame",
    family: "precision-clinical",
    familyName: "Precision Clinical",
    category: ["clinical", "plain"],
    mood: ["precise", "trustworthy", "framed"],
    vibe: { clinical: 3, minimal: 2 },
    colorMode: "light",
    density: "standard",
    pairingId: "neutral-inter",
    recommendedGlass: ["clear", "amber"],
    featured: true,
    align: "left",
    rows: [
      { slot: "brand", zone: "header", font: "body", weight: 600, sizeFactor: 0.06, minPt: 4.5, maxLines: 1, color: "muted", letterSpacingEm: 0.14, casing: "uppercase" },
      { slot: "product-name", zone: "hero", font: "display", sizeFactor: 0.15, minPt: 7, maxLines: 2, color: "text" },
      { slot: "subtitle", zone: "hero", font: "body", sizeFactor: 0.06, minPt: 4.5, maxLines: 1, color: "muted", spacingBefore: 0.8 },
      { slot: "strength", zone: "hero", font: "body", weight: 600, sizeFactor: 0.075, minPt: 5, maxLines: 1, color: "accent", spacingBefore: 1 },
      { slot: "volume", zone: "hero", font: "body", sizeFactor: 0.055, minPt: 4.5, maxLines: 1, color: "muted", spacingBefore: 0.4 },
      ...footerRows(),
    ],
    codeCorner: "bottom-right",
    decor: [{ kind: "border", insetMm: 1.2, strokePt: 0.8, color: "accent" }],
  }),
  defineTemplate({
    id: "luxury-center",
    name: "Luxury centered",
    family: "gilded-serif",
    familyName: "Gilded Serif",
    category: ["luxury", "glossy"],
    mood: ["elegant", "serif", "rich"],
    vibe: { luxury: 3, premium: 3 },
    colorMode: "dark",
    density: "standard",
    pairingId: "luxury-classic",
    recommendedGlass: ["amber", "clear"],
    featured: true,
    align: "center",
    rows: [
      { slot: "brand", zone: "header", font: "body", weight: 500, sizeFactor: 0.06, minPt: 4.5, maxLines: 1, color: "muted", letterSpacingEm: 0.3, casing: "uppercase" },
      { slot: "product-name", zone: "hero", font: "display", sizeFactor: 0.16, minPt: 7, maxLines: 2, color: "text" },
      { slot: "subtitle", zone: "hero", font: "body", sizeFactor: 0.055, minPt: 4.5, maxLines: 1, color: "muted", letterSpacingEm: 0.08, spacingBefore: 1 },
      { slot: "strength", zone: "hero", font: "body", weight: 500, sizeFactor: 0.065, minPt: 4.5, maxLines: 1, color: "accent", letterSpacingEm: 0.12, spacingBefore: 1.2 },
      { slot: "volume", zone: "footer", font: "body", sizeFactor: 0.05, minPt: 4, maxLines: 1, color: "muted" },
      ...footerRows(),
    ],
    codeCorner: "bottom-right",
    decor: [
      { kind: "underline-hero", widthFactor: 0.18, strokePt: 1, fill: { effect: true } },
    ],
  }),
  defineTemplate({
    id: "bold-block",
    name: "Bold block",
    family: "bold-block",
    familyName: "Bold Block",
    category: ["plain", "neon", "glossy"],
    mood: ["loud", "confident", "banded"],
    vibe: { bold: 3, playful: 1 },
    colorMode: "dark",
    density: "standard",
    pairingId: "impact-display",
    recommendedGlass: ["clear", "amber"],
    featured: true,
    align: "left",
    rows: [
      { slot: "brand", zone: "header", font: "body", weight: 600, sizeFactor: 0.06, minPt: 4.5, maxLines: 1, color: "muted", letterSpacingEm: 0.12, casing: "uppercase" },
      { slot: "product-name", zone: "hero", font: "display", sizeFactor: 0.24, minPt: 9, maxLines: 2, color: "text", casing: "uppercase" },
      { slot: "strength", zone: "hero", font: "body", weight: 600, sizeFactor: 0.085, minPt: 5, maxLines: 1, color: "accent", spacingBefore: 0.8 },
      { slot: "subtitle", zone: "hero", font: "body", sizeFactor: 0.055, minPt: 4.5, maxLines: 1, color: "muted", spacingBefore: 0.6 },
      { slot: "volume", zone: "footer", font: "body", weight: 600, sizeFactor: 0.055, minPt: 4, maxLines: 1, color: "muted" },
      ...footerRows(),
    ],
    codeCorner: "bottom-right",
    decor: [
      { kind: "band", edge: "top", heightFactor: 0.14, fill: { effect: true } },
      { kind: "band", edge: "bottom", heightFactor: 0.07, fill: { role: "accent" } },
    ],
  }),
  defineTemplate({
    id: "futuristic-band",
    name: "Futuristic band",
    family: "futuristic-band",
    familyName: "Futuristic Band",
    category: ["holographic", "neon", "laboratory"],
    mood: ["techy", "engineered", "sci-fi"],
    vibe: { futuristic: 3, bold: 1, clinical: 1 },
    colorMode: "dark",
    density: "standard",
    pairingId: "cyber-orbit",
    recommendedGlass: ["cobalt", "clear"],
    align: "center",
    rows: [
      { slot: "brand", zone: "header", font: "body", weight: 500, sizeFactor: 0.055, minPt: 4.5, maxLines: 1, color: "muted", letterSpacingEm: 0.35, casing: "uppercase" },
      { slot: "product-name", zone: "hero", font: "display", sizeFactor: 0.14, minPt: 6.5, maxLines: 2, color: "text", casing: "uppercase", letterSpacingEm: 0.06 },
      { slot: "strength", zone: "hero", font: "body", weight: 500, sizeFactor: 0.07, minPt: 4.5, maxLines: 1, color: "accent", letterSpacingEm: 0.2, spacingBefore: 1.2 },
      { slot: "subtitle", zone: "hero", font: "body", sizeFactor: 0.05, minPt: 4, maxLines: 1, color: "muted", letterSpacingEm: 0.1, spacingBefore: 0.6 },
      { slot: "volume", zone: "footer", font: "body", sizeFactor: 0.05, minPt: 4, maxLines: 1, color: "muted" },
      ...footerRows(),
    ],
    codeCorner: "bottom-left",
    decor: [
      { kind: "stripe", edge: "left", widthFactor: 0.045, fill: { effect: true } },
      { kind: "stripe", edge: "right", widthFactor: 0.045, fill: { effect: true } },
    ],
  }),
  defineTemplate({
    id: "minimal-left",
    name: "Minimal left",
    family: "modern-type",
    familyName: "Modern Type",
    category: ["plain", "clinical", "beauty"],
    mood: ["quiet", "modern", "whitespace"],
    vibe: { minimal: 3, clinical: 1, premium: 1 },
    colorMode: "light",
    density: "standard",
    pairingId: "grotesk-minimal",
    recommendedGlass: ["clear", "frosted"],
    featured: true,
    align: "left",
    rows: [
      { slot: "brand", zone: "header", font: "body", weight: 500, sizeFactor: 0.055, minPt: 4.5, maxLines: 1, color: "muted", letterSpacingEm: 0.06 },
      { slot: "product-name", zone: "hero", font: "display", sizeFactor: 0.13, minPt: 6.5, maxLines: 2, color: "text" },
      { slot: "strength", zone: "hero", font: "body", sizeFactor: 0.06, minPt: 4.5, maxLines: 1, color: "text", spacingBefore: 1 },
      { slot: "subtitle", zone: "hero", font: "body", sizeFactor: 0.05, minPt: 4, maxLines: 1, color: "muted", spacingBefore: 0.5 },
      { slot: "volume", zone: "footer", font: "body", sizeFactor: 0.05, minPt: 4, maxLines: 1, color: "muted" },
      ...footerRows(),
    ],
    codeCorner: "bottom-right",
    decor: [{ kind: "underline-hero", widthFactor: 0.1, strokePt: 1.4, fill: { role: "accent" } }],
  }),
  defineTemplate({
    id: "botanical-soft",
    name: "Botanical soft",
    family: "botanical-soft",
    familyName: "Botanical Soft",
    category: ["botanical", "beauty"],
    mood: ["natural", "organic", "calm"],
    vibe: { botanical: 3, luxury: 1, minimal: 1 },
    colorMode: "light",
    density: "standard",
    pairingId: "botanical-premium",
    recommendedGlass: ["amber", "clear"],
    align: "center",
    rows: [
      { slot: "brand", zone: "header", font: "body", weight: 500, sizeFactor: 0.055, minPt: 4.5, maxLines: 1, color: "muted", letterSpacingEm: 0.22, casing: "uppercase" },
      { slot: "product-name", zone: "hero", font: "display", sizeFactor: 0.17, minPt: 7, maxLines: 2, color: "text" },
      { slot: "subtitle", zone: "hero", font: "body", sizeFactor: 0.052, minPt: 4, maxLines: 2, color: "muted", spacingBefore: 0.8 },
      { slot: "strength", zone: "hero", font: "body", weight: 500, sizeFactor: 0.06, minPt: 4.5, maxLines: 1, color: "accent", spacingBefore: 1 },
      { slot: "volume", zone: "footer", font: "body", sizeFactor: 0.05, minPt: 4, maxLines: 1, color: "muted" },
      ...footerRows(),
    ],
    codeCorner: "bottom-right",
    decor: [{ kind: "border", insetMm: 1.6, strokePt: 0.6, color: "muted" }],
  }),
  defineTemplate({
    id: "lab-mono",
    name: "Laboratory mono",
    family: "specimen-record",
    familyName: "Specimen Record",
    category: ["laboratory", "clinical"],
    mood: ["data", "monospace", "exact"],
    vibe: { clinical: 2, futuristic: 1, minimal: 1 },
    colorMode: "light",
    density: "detailed",
    pairingId: "retro-terminal",
    recommendedGlass: ["clear", "cobalt"],
    align: "left",
    rows: [
      { slot: "brand", zone: "header", font: "body", weight: 700, sizeFactor: 0.055, minPt: 4.5, maxLines: 1, color: "accent", casing: "uppercase" },
      { slot: "lot", zone: "header", font: "technical", sizeFactor: 0.045, minPt: 4, maxLines: 1, color: "muted", spacingBefore: 0.3 },
      { slot: "expiry", zone: "header", font: "technical", sizeFactor: 0.045, minPt: 4, maxLines: 1, color: "muted", spacingBefore: 0.2 },
      { slot: "product-name", zone: "hero", font: "display", sizeFactor: 0.12, minPt: 6, maxLines: 2, color: "text", casing: "uppercase" },
      { slot: "strength", zone: "hero", font: "body", weight: 700, sizeFactor: 0.07, minPt: 4.5, maxLines: 1, color: "accent", spacingBefore: 0.6 },
      { slot: "volume", zone: "footer", font: "body", sizeFactor: 0.048, minPt: 4, maxLines: 1, color: "muted" },
      { slot: "description", zone: "footer", font: "body", sizeFactor: 0.045, minPt: 4, maxLines: 2, color: "muted", spacingBefore: 0.35 },
      { slot: "ingredients", zone: "footer", font: "body", sizeFactor: 0.042, minPt: 4, maxLines: 3, color: "muted", spacingBefore: 0.35 },
      { slot: "directions", zone: "footer", font: "body", sizeFactor: 0.042, minPt: 4, maxLines: 2, color: "muted", spacingBefore: 0.3 },
      { slot: "storage", zone: "footer", font: "body", sizeFactor: 0.042, minPt: 4, maxLines: 1, color: "muted", spacingBefore: 0.3 },
      { slot: "warning", zone: "footer", font: "body", weight: 700, sizeFactor: 0.042, minPt: 4, maxLines: 2, color: "text", spacingBefore: 0.3 },
      { slot: "verification", zone: "footer", font: "technical", sizeFactor: 0.042, minPt: 4, maxLines: 1, color: "muted", spacingBefore: 0.3 },
      { slot: "website", zone: "footer", font: "body", sizeFactor: 0.045, minPt: 4, maxLines: 1, color: "accent", spacingBefore: 0.4 },
    ],
    codeCorner: "bottom-right",
    decor: [{ kind: "border", insetMm: 1, strokePt: 1.2, color: "text" }],
  }),
  defineTemplate({
    id: "skincare-airy",
    name: "Skincare airy",
    family: "dermatology-minimal",
    familyName: "Dermatology Minimal",
    category: ["beauty", "plain", "clinical"],
    mood: ["airy", "tracked", "soft"],
    vibe: { minimal: 2, luxury: 1, botanical: 1, premium: 1 },
    colorMode: "light",
    density: "minimal",
    pairingId: "airy-modern",
    recommendedGlass: ["frosted", "clear"],
    align: "center",
    rows: [
      { slot: "brand", zone: "header", font: "body", weight: 600, sizeFactor: 0.05, minPt: 4.5, maxLines: 1, color: "text", letterSpacingEm: 0.4, casing: "uppercase" },
      { slot: "product-name", zone: "hero", font: "display", sizeFactor: 0.115, minPt: 6, maxLines: 2, color: "text", letterSpacingEm: 0.12, casing: "uppercase", spacingBefore: 1.4 },
      { slot: "subtitle", zone: "hero", font: "body", sizeFactor: 0.05, minPt: 4, maxLines: 2, color: "muted", letterSpacingEm: 0.06, spacingBefore: 1.2 },
      { slot: "strength", zone: "hero", font: "body", sizeFactor: 0.055, minPt: 4.5, maxLines: 1, color: "muted", letterSpacingEm: 0.14, spacingBefore: 1.6 },
      { slot: "volume", zone: "footer", font: "body", sizeFactor: 0.048, minPt: 4, maxLines: 1, color: "muted", letterSpacingEm: 0.1 },
      ...footerRows(),
    ],
    codeCorner: "bottom-right",
    decor: [{ kind: "underline-hero", widthFactor: 0.08, strokePt: 0.7, fill: { role: "muted" } }],
  }),
  defineTemplate({
    id: "premium-cinzel",
    name: "Dark estate",
    family: "estate-frame",
    familyName: "Estate Frame",
    category: ["luxury"],
    mood: ["estate", "engraved", "formal"],
    vibe: { premium: 3, luxury: 2 },
    colorMode: "dark",
    density: "standard",
    pairingId: "classic-estate",
    recommendedGlass: ["amber", "opaque"],
    align: "center",
    rows: [
      { slot: "brand", zone: "header", font: "display", weight: 700, sizeFactor: 0.06, minPt: 4.5, maxLines: 1, color: "accent", letterSpacingEm: 0.18, casing: "uppercase" },
      { slot: "product-name", zone: "hero", font: "display", sizeFactor: 0.14, minPt: 6.5, maxLines: 2, color: "text", casing: "uppercase", letterSpacingEm: 0.04 },
      { slot: "subtitle", zone: "hero", font: "body", sizeFactor: 0.05, minPt: 4, maxLines: 1, color: "muted", letterSpacingEm: 0.1, spacingBefore: 1 },
      { slot: "strength", zone: "hero", font: "body", weight: 500, sizeFactor: 0.06, minPt: 4.5, maxLines: 1, color: "accent", letterSpacingEm: 0.15, spacingBefore: 1.2 },
      { slot: "volume", zone: "footer", font: "body", sizeFactor: 0.048, minPt: 4, maxLines: 1, color: "muted", letterSpacingEm: 0.08 },
      ...footerRows(),
    ],
    codeCorner: "bottom-right",
    decor: [
      { kind: "border", insetMm: 1.1, strokePt: 0.7, color: "accent" },
      { kind: "border", insetMm: 1.9, strokePt: 0.35, color: "accent" },
      { kind: "underline-hero", widthFactor: 0.14, strokePt: 0.8, fill: { effect: true } },
    ],
  }),
  defineTemplate({
    id: "type-stack",
    name: "Type stack",
    family: "pure-typography",
    familyName: "Pure Typography",
    category: ["plain", "neon"],
    mood: ["typographic", "stacked", "raw"],
    vibe: { bold: 3, minimal: 1, futuristic: 1 },
    colorMode: "dark",
    density: "minimal",
    pairingId: "impact-display",
    recommendedGlass: ["clear"],
    align: "left",
    rows: [
      { slot: "brand", zone: "hero", font: "display", sizeFactor: 0.1, minPt: 5.5, maxLines: 1, color: "muted", casing: "uppercase" },
      { slot: "product-name", zone: "hero", font: "display", sizeFactor: 0.26, minPt: 9, maxLines: 2, color: "text", casing: "uppercase", spacingBefore: 0.2 },
      { slot: "strength", zone: "hero", font: "display", sizeFactor: 0.11, minPt: 5.5, maxLines: 1, color: "accent", casing: "uppercase", spacingBefore: 0.3 },
      { slot: "subtitle", zone: "footer", font: "body", sizeFactor: 0.05, minPt: 4, maxLines: 1, color: "muted" },
      { slot: "volume", zone: "footer", font: "body", sizeFactor: 0.05, minPt: 4, maxLines: 1, color: "muted", spacingBefore: 0.4 },
      ...footerRows(),
    ],
    codeCorner: "bottom-right",
    decor: [],
  }),
  defineTemplate({
    id: "wellness-band",
    name: "Wellness band",
    family: "wellness-band",
    familyName: "Wellness Band",
    category: ["botanical", "beauty", "plain"],
    mood: ["friendly", "warm", "banded"],
    vibe: { botanical: 2, playful: 1, minimal: 1 },
    colorMode: "light",
    density: "standard",
    pairingId: "airy-modern",
    recommendedGlass: ["clear", "amber"],
    align: "center",
    rows: [
      { slot: "brand", zone: "header", font: "body", weight: 600, sizeFactor: 0.055, minPt: 4.5, maxLines: 1, color: "muted", letterSpacingEm: 0.2, casing: "uppercase" },
      { slot: "product-name", zone: "hero", font: "display", weight: 800, sizeFactor: 0.14, minPt: 6.5, maxLines: 2, color: "text" },
      { slot: "strength", zone: "hero", font: "body", weight: 600, sizeFactor: 0.065, minPt: 4.5, maxLines: 1, color: "accent", spacingBefore: 1 },
      { slot: "subtitle", zone: "hero", font: "body", sizeFactor: 0.05, minPt: 4, maxLines: 2, color: "muted", spacingBefore: 0.6 },
      { slot: "volume", zone: "footer", font: "body", weight: 600, sizeFactor: 0.05, minPt: 4, maxLines: 1, color: "muted" },
      ...footerRows(),
    ],
    codeCorner: "bottom-left",
    // The band is decorative — the inset logic keeps text above it.
    decor: [{ kind: "band", edge: "bottom", heightFactor: 0.22, fill: { role: "accent" } }],
  }),
  defineTemplate({
    id: "qr-forward",
    name: "Scan first",
    family: "scan-first",
    familyName: "Scan First",
    category: ["laboratory", "clinical", "plain"],
    mood: ["connected", "practical"],
    vibe: { futuristic: 2, clinical: 1, minimal: 1 },
    colorMode: "light",
    density: "standard",
    pairingId: "grotesk-minimal",
    recommendedGlass: ["clear"],
    align: "left",
    rows: [
      { slot: "brand", zone: "header", font: "body", weight: 600, sizeFactor: 0.055, minPt: 4.5, maxLines: 1, color: "muted", letterSpacingEm: 0.08, casing: "uppercase" },
      { slot: "product-name", zone: "hero", font: "display", weight: 700, sizeFactor: 0.13, minPt: 6.5, maxLines: 2, color: "text" },
      { slot: "strength", zone: "hero", font: "body", weight: 600, sizeFactor: 0.065, minPt: 4.5, maxLines: 1, color: "accent", spacingBefore: 0.8 },
      { slot: "website", zone: "footer", font: "body", weight: 500, sizeFactor: 0.05, minPt: 4, maxLines: 1, color: "accent" },
      { slot: "volume", zone: "footer", font: "body", sizeFactor: 0.048, minPt: 4, maxLines: 1, color: "muted", spacingBefore: 0.4 },
      { slot: "subtitle", zone: "footer", font: "body", sizeFactor: 0.048, minPt: 4, maxLines: 1, color: "muted", spacingBefore: 0.4 },
      ...footerRows().filter((r) => r.slot !== "website" && r.slot !== "subtitle"),
    ],
    codeCorner: "bottom-right",
    qrScale: 1.35,
    decor: [{ kind: "stripe", edge: "right", widthFactor: 0.035, fill: { effect: true } }],
  }),
] as const;
