import { brandBottom, brandCaps, kickerSubtitle, productHero, strengthRow, volumeRow } from "./parts";
import type { EasyTemplateDef, RowDef } from "./types";
import { defineTemplate } from "./types";

/**
 * Dark laboratory family (§8): black-label research looks — carbon,
 * graphite, silver-on-black. All colorMode "dark" (validated against the
 * materials' dark palettes) with the research vocabulary carried in
 * monospace data rows.
 */

function dataRow(slot: RowDef["slot"], overrides: Partial<RowDef> = {}): RowDef {
  return {
    slot,
    zone: "footer",
    font: "technical",
    sizeFactor: 0.044,
    minPt: 4,
    maxLines: 1,
    color: "muted",
    spacingBefore: 0.3,
    ...overrides,
  };
}

function noticeRow(overrides: Partial<RowDef> = {}): RowDef {
  return {
    slot: "notice",
    zone: "footer",
    font: "body",
    emphasis: true,
    sizeFactor: 0.046,
    minPt: 4,
    maxLines: 2,
    color: "text",
    letterSpacingEm: 0.08,
    casing: "uppercase",
    spacingBefore: 0.7,
    ...overrides,
  };
}

export const DARK_LABORATORY_TEMPLATES: readonly EasyTemplateDef[] = [
  defineTemplate({
    id: "black-laboratory",
    name: "Black Laboratory",
    family: "black-laboratory",
    familyName: "Black Laboratory",
    category: ["laboratory", "research"],
    mood: ["black", "tracked", "austere"],
    vibe: { clinical: 2, premium: 2, minimal: 1 },
    colorMode: "dark",
    density: "standard",
    pairingId: "grotesk-minimal",
    recommendedGlass: ["clear", "opaque"],
    featured: true,
    align: "left",
    rows: [
      brandCaps({ letterSpacingEm: 0.24 }),
      productHero(0.155),
      strengthRow({ spacingBefore: 0.8 }),
      noticeRow(),
      dataRow("catalog", { spacingBefore: 0.5 }),
      dataRow("lot"),
      dataRow("batch"),
      volumeRow("footer", { font: "technical", spacingBefore: 0.35 }),
    ],
    codeCorner: "bottom-right",
    decor: [
      { kind: "divider", after: "brand", widthFactor: 0.38, strokePt: 0.9, fill: { role: "accent" } },
    ],
  }),
  defineTemplate({
    id: "carbon-research",
    name: "Carbon Research",
    family: "carbon-research",
    familyName: "Carbon Research",
    category: ["laboratory", "research"],
    mood: ["carbon", "two-column", "engineered"],
    vibe: { futuristic: 2, clinical: 2 },
    colorMode: "dark",
    density: "standard",
    pairingId: "engineered",
    recommendedGlass: ["clear", "opaque"],
    minHeightMm: 20,
    minWidthMm: 55,
    align: "left",
    split: { ratio: 0.54, divider: true },
    rows: [
      brandCaps({ font: "body", letterSpacingEm: 0.14 }),
      productHero(0.13),
      { slot: "abbreviation", zone: "hero", font: "display", sizeFactor: 0.07, minPt: 4.5, maxLines: 1, color: "accent", spacingBefore: 0.8 },
      strengthRow({ color: "text", spacingBefore: 0.7 }),
      dataRow("catalog", { zone: "header", column: "right", color: "text", weight: 700, spacingBefore: 0 }),
      dataRow("lot", { column: "right", spacingBefore: 0.35 }),
      dataRow("batch", { column: "right" }),
      dataRow("storage", { font: "body", column: "right", maxLines: 2, spacingBefore: 0.45 }),
      noticeRow({ column: "right", sizeFactor: 0.042 }),
      volumeRow("footer", { spacingBefore: 0.35 }),
    ],
    codeCorner: "bottom-right",
    decor: [],
  }),
  defineTemplate({
    id: "obsidian-science",
    name: "Obsidian Science",
    family: "obsidian-science",
    familyName: "Obsidian Science",
    category: ["laboratory", "research"],
    mood: ["monogram", "ceremonial", "dark"],
    vibe: { premium: 3, clinical: 1 },
    colorMode: "dark",
    density: "minimal",
    pairingId: "minimal-premium",
    recommendedGlass: ["opaque", "cobalt"],
    minHeightMm: 18,
    align: "center",
    rows: [
      { slot: "brand", zone: "header", font: "display", sizeFactor: 0.1, minPt: 6, maxLines: 1, color: "accent", monogram: true, align: "center" },
      productHero(0.13, { align: "center" }),
      strengthRow({ align: "center", spacingBefore: 0.7 }),
      noticeRow({ align: "center", sizeFactor: 0.042 }),
      dataRow("lot", { align: "center", spacingBefore: 0.5 }),
      volumeRow("footer", { align: "center", spacingBefore: 0.35 }),
    ],
    codeCorner: "bottom-right",
    decor: [
      { kind: "medallion", sizeFactor: 0.24, fill: { role: "accent" }, ring: true, minLabelHeightMm: 16 },
    ],
  }),
  defineTemplate({
    id: "midnight-clinical",
    name: "Midnight Clinical",
    family: "midnight-clinical",
    familyName: "Midnight Clinical",
    category: ["laboratory", "clinical"],
    mood: ["midnight", "banded", "calm"],
    vibe: { clinical: 3, premium: 1 },
    colorMode: "dark",
    density: "standard",
    pairingId: "modern-clinical",
    recommendedGlass: ["cobalt", "opaque"],
    align: "left",
    rows: [
      brandCaps({ letterSpacingEm: 0.12 }),
      kickerSubtitle({ spacingBefore: 0.9 }),
      productHero(0.15),
      strengthRow({ spacingBefore: 0.8 }),
      { slot: "storage", zone: "footer", font: "body", sizeFactor: 0.044, minPt: 4, maxLines: 2, color: "muted", spacingBefore: 0.4 },
      dataRow("lot", { spacingBefore: 0.4 }),
      dataRow("expiry"),
      noticeRow({ sizeFactor: 0.042 }),
      volumeRow("footer", { spacingBefore: 0.3 }),
    ],
    codeCorner: "bottom-right",
    decor: [
      { kind: "band", edge: "top", heightFactor: 0.07, fill: { role: "accent" }, minLabelHeightMm: 14 },
    ],
  }),
  defineTemplate({
    id: "dark-molecular",
    name: "Dark Molecular",
    family: "dark-molecular",
    familyName: "Dark Molecular",
    category: ["laboratory", "research"],
    mood: ["formula-forward", "futuristic", "dark"],
    vibe: { futuristic: 3, clinical: 1 },
    colorMode: "dark",
    density: "detailed",
    pairingId: "futuristic",
    recommendedGlass: ["clear", "opaque"],
    minHeightMm: 22,
    align: "center",
    rows: [
      { slot: "formula", zone: "header", font: "technical", sizeFactor: 0.048, minPt: 4, maxLines: 1, color: "accent", letterSpacingEm: 0.16, align: "center", casing: "uppercase" },
      brandCaps({ align: "center", letterSpacingEm: 0.2, spacingBefore: 0.5 }),
      productHero(0.14, { align: "center" }),
      strengthRow({ align: "center", spacingBefore: 0.8 }),
      dataRow("molecular-weight", { align: "center", minLabelHeightMm: 22 }),
      dataRow("cas", { align: "center", minLabelHeightMm: 22 }),
      dataRow("lot", { align: "center", spacingBefore: 0.5 }),
      dataRow("batch", { align: "center" }),
      noticeRow({ align: "center" }),
      volumeRow("footer", { align: "center", spacingBefore: 0.4 }),
    ],
    codeCorner: "bottom-right",
    decor: [
      { kind: "underline-hero", widthFactor: 0.26, strokePt: 1, fill: { role: "accent" } },
    ],
  }),
  defineTemplate({
    id: "graphite-grid",
    name: "Graphite Grid",
    family: "graphite-grid",
    familyName: "Graphite Grid",
    category: ["laboratory", "research"],
    mood: ["grid", "terminal", "dense"],
    vibe: { clinical: 2, futuristic: 2 },
    colorMode: "dark",
    density: "detailed",
    pairingId: "retro-terminal",
    recommendedGlass: ["clear"],
    minHeightMm: 22,
    minWidthMm: 55,
    align: "left",
    split: { ratio: 0.5, divider: true },
    rows: [
      brandCaps({ font: "technical", letterSpacingEm: 0.1 }),
      productHero(0.12),
      { slot: "abbreviation", zone: "hero", font: "technical", weight: 700, sizeFactor: 0.06, minPt: 4.5, maxLines: 1, color: "accent", spacingBefore: 0.7 },
      strengthRow({ font: "technical", spacingBefore: 0.6 }),
      noticeRow({ sizeFactor: 0.04 }),
      dataRow("catalog", { zone: "header", column: "right", spacingBefore: 0 }),
      dataRow("sku", { column: "right" }),
      dataRow("lot", { column: "right" }),
      dataRow("batch", { column: "right" }),
      dataRow("produced", { column: "right" }),
      dataRow("retest", { column: "right" }),
      dataRow("storage", { font: "body", column: "right", maxLines: 2, spacingBefore: 0.4 }),
      volumeRow("footer", { font: "technical", spacingBefore: 0.3 }),
    ],
    codeCorner: "bottom-right",
    decor: [
      { kind: "corners", lengthMm: 2.6, strokePt: 0.8, color: "muted", insetMm: 1.2, minLabelHeightMm: 15 },
    ],
  }),
  defineTemplate({
    id: "black-silver-lab",
    name: "Black-and-Silver Lab",
    family: "black-silver-lab",
    familyName: "Black-and-Silver Lab",
    category: ["laboratory", "biotechnology"],
    mood: ["silver", "rail", "premium"],
    vibe: { premium: 2, clinical: 2 },
    colorMode: "dark",
    density: "standard",
    pairingId: "tech-lab",
    recommendedGlass: ["opaque", "clear"],
    minHeightMm: 18,
    minWidthMm: 55,
    align: "left",
    verticalRow: {
      slot: "brand",
      edge: "right",
      font: "body",
      weight: 600,
      sizeFactor: 0.085,
      minPt: 4.5,
      color: "muted",
      letterSpacingEm: 0.22,
      casing: "uppercase",
    },
    rows: [
      productHero(0.16),
      { slot: "subtitle", zone: "hero", font: "body", sizeFactor: 0.048, minPt: 4, maxLines: 1, color: "muted", spacingBefore: 0.6 },
      strengthRow({ spacingBefore: 0.8 }),
      noticeRow(),
      dataRow("lot", { spacingBefore: 0.5 }),
      dataRow("expiry"),
      volumeRow("footer", { spacingBefore: 0.35 }),
    ],
    codeCorner: "bottom-left",
    decor: [
      { kind: "side-rail", edge: "left", insetMm: 1.1, strokePt: 1, color: "accent" },
    ],
    materials: ["plain", "matte", "glossy", "metallic"],
  }),
  defineTemplate({
    id: "dark-analytical",
    name: "Dark Analytical",
    family: "dark-analytical",
    familyName: "Dark Analytical",
    category: ["laboratory", "research"],
    mood: ["analytical", "header-data", "sober"],
    vibe: { clinical: 3, minimal: 1 },
    colorMode: "dark",
    density: "standard",
    pairingId: "neutral-inter",
    recommendedGlass: ["clear", "amber"],
    align: "left",
    rows: [
      brandCaps(),
      { slot: "lot", zone: "header", font: "technical", sizeFactor: 0.044, minPt: 4, maxLines: 1, color: "muted", spacingBefore: 0.4 },
      { slot: "expiry", zone: "header", font: "technical", sizeFactor: 0.044, minPt: 4, maxLines: 1, color: "muted", spacingBefore: 0.25 },
      productHero(0.15),
      { slot: "purity", zone: "hero", font: "body", weight: 600, sizeFactor: 0.055, minPt: 4.5, maxLines: 1, color: "accent", spacingBefore: 0.8 },
      { slot: "storage", zone: "footer", font: "body", sizeFactor: 0.044, minPt: 4, maxLines: 2, color: "muted", spacingBefore: 0.4 },
      noticeRow({ sizeFactor: 0.042 }),
      volumeRow("footer", { spacingBefore: 0.3 }),
    ],
    codeCorner: "bottom-right",
    decor: [
      { kind: "stripe", edge: "right", widthFactor: 0.04, fill: { role: "accent" } },
    ],
  }),
  defineTemplate({
    id: "research-noir",
    name: "Research Noir",
    family: "research-noir",
    familyName: "Research Noir",
    category: ["laboratory", "luxury"],
    mood: ["noir", "serif", "editorial"],
    vibe: { premium: 3, luxury: 2 },
    colorMode: "dark",
    density: "minimal",
    pairingId: "quiet-luxury",
    recommendedGlass: ["opaque", "amber"],
    minHeightMm: 16,
    align: "center",
    rows: [
      productHero(0.17, { align: "center", minPt: 8 }),
      { slot: "strength", zone: "hero", font: "body", sizeFactor: 0.055, minPt: 4.5, maxLines: 1, color: "muted", letterSpacingEm: 0.14, align: "center", spacingBefore: 0.9 },
      { slot: "notice", zone: "footer", font: "body", sizeFactor: 0.042, minPt: 4, maxLines: 2, color: "muted", letterSpacingEm: 0.12, casing: "uppercase", align: "center", chip: "outline", spacingBefore: 0.7 },
      dataRow("lot", { align: "center", spacingBefore: 0.5 }),
      brandBottom({ align: "center", spacingBefore: 0.7 }),
      volumeRow("footer", { align: "center", spacingBefore: 0.3 }),
    ],
    codeCorner: "bottom-right",
    decor: [
      { kind: "band", edge: "bottom", heightFactor: 0.05, fill: { role: "accent" } },
    ],
  }),
  defineTemplate({
    id: "controlled-carbon",
    name: "Controlled Carbon",
    family: "controlled-carbon",
    familyName: "Controlled Carbon",
    category: ["laboratory", "pharmaceutical"],
    mood: ["dosage-forward", "condensed", "controlled"],
    vibe: { bold: 2, clinical: 2 },
    colorMode: "dark",
    density: "standard",
    pairingId: "condensed-impact",
    recommendedGlass: ["clear", "opaque"],
    minHeightMm: 16,
    align: "left",
    rows: [
      brandCaps({ letterSpacingEm: 0.18 }),
      productHero(0.14),
      { slot: "strength", zone: "hero", font: "display", sizeFactor: 0.11, minPt: 6, maxLines: 1, color: "onAccent", chip: "fill", spacingBefore: 1 },
      noticeRow(),
      dataRow("catalog", { spacingBefore: 0.5 }),
      dataRow("lot"),
      dataRow("batch"),
      volumeRow("footer", { font: "technical", spacingBefore: 0.3 }),
    ],
    codeCorner: "bottom-right",
    decor: [
      { kind: "corners", lengthMm: 3, strokePt: 1, color: "accent", insetMm: 1.3, minLabelHeightMm: 15 },
    ],
  }),
] as const;
