import { footerRows } from "./core";
import type { EasyTemplateDef } from "./types";
import { defineTemplate } from "./types";

/**
 * Holographic & neon flagship families (§5). These lean on the material
 * system — effect fills only appear where the material provides a finish,
 * and readability protection is automatic — so they also degrade
 * gracefully on plain stock.
 */

export const EFFECT_TEMPLATES: readonly EasyTemplateDef[] = [
  // --- Holographic ------------------------------------------------------------
  defineTemplate({
    id: "prism-frame",
    name: "Prism Frame",
    family: "prism-frame",
    familyName: "Prism Frame",
    category: ["holographic", "luxury"],
    mood: ["framed", "prismatic", "clean"],
    vibe: { futuristic: 1, luxury: 2, minimal: 2 },
    colorMode: "dark",
    density: "standard",
    pairingId: "minimal-premium",
    recommendedGlass: ["frosted", "clear"],
    featured: true,
    align: "center",
    materials: ["holographic", "metallic", "glossy", "plain"],
    rows: [
      { slot: "brand", zone: "header", font: "body", weight: 600, sizeFactor: 0.052, minPt: 4.5, maxLines: 1, color: "muted", letterSpacingEm: 0.28, casing: "uppercase" },
      { slot: "product-name", zone: "hero", font: "display", sizeFactor: 0.15, minPt: 7, maxLines: 2, color: "text" },
      { slot: "subtitle", zone: "hero", font: "body", sizeFactor: 0.05, minPt: 4, maxLines: 1, color: "muted", spacingBefore: 0.9 },
      { slot: "strength", zone: "hero", font: "body", weight: 600, sizeFactor: 0.062, minPt: 4.5, maxLines: 1, color: "accent", spacingBefore: 1.1 },
      { slot: "volume", zone: "footer", font: "body", sizeFactor: 0.048, minPt: 4, maxLines: 1, color: "muted" },
      ...footerRows(),
    ],
    codeCorner: "bottom-right",
    decor: [{ kind: "frame-effect", thicknessFactor: 0.05, minLabelHeightMm: 13 }],
  }),
  defineTemplate({
    id: "iridescent-core",
    name: "Iridescent Core",
    family: "iridescent-core",
    familyName: "Iridescent Core",
    category: ["holographic", "beauty"],
    mood: ["soft", "shimmering", "airy"],
    vibe: { luxury: 1, minimal: 2, botanical: 1 },
    colorMode: "light",
    density: "minimal",
    pairingId: "contemporary-skincare",
    recommendedGlass: ["frosted", "clear"],
    align: "center",
    materials: ["holographic", "metallic", "clear", "glossy", "plain"],
    rows: [
      { slot: "brand", zone: "header", font: "body", weight: 600, sizeFactor: 0.05, minPt: 4.5, maxLines: 1, color: "text", letterSpacingEm: 0.3, casing: "uppercase" },
      { slot: "product-name", zone: "hero", font: "display", sizeFactor: 0.14, minPt: 6.5, maxLines: 2, color: "text" },
      { slot: "subtitle", zone: "hero", font: "body", sizeFactor: 0.05, minPt: 4, maxLines: 2, color: "muted", spacingBefore: 1 },
      { slot: "strength", zone: "hero", font: "body", sizeFactor: 0.055, minPt: 4.5, maxLines: 1, color: "muted", letterSpacingEm: 0.12, spacingBefore: 1.3 },
      { slot: "volume", zone: "footer", font: "body", sizeFactor: 0.046, minPt: 4, maxLines: 1, color: "muted" },
      ...footerRows(),
    ],
    codeCorner: "bottom-right",
    decor: [
      { kind: "band", edge: "top", heightFactor: 0.07, fill: { effect: true }, minLabelHeightMm: 13 },
      { kind: "band", edge: "bottom", heightFactor: 0.07, fill: { effect: true }, minLabelHeightMm: 13 },
    ],
  }),
  defineTemplate({
    id: "rainbow-edge",
    name: "Rainbow Edge",
    family: "rainbow-edge",
    familyName: "Rainbow Edge",
    category: ["holographic", "neon"],
    mood: ["edged", "vertical", "kinetic"],
    vibe: { futuristic: 2, bold: 2 },
    colorMode: "dark",
    density: "standard",
    pairingId: "futuristic",
    recommendedGlass: ["cobalt", "clear"],
    align: "left",
    minHeightMm: 16,
    materials: ["holographic", "metallic", "neon", "glossy"],
    verticalRow: { slot: "brand", edge: "right", font: "body", weight: 700, sizeFactor: 0.048, minPt: 4.5, color: "muted", letterSpacingEm: 0.24, casing: "uppercase" },
    rows: [
      { slot: "product-name", zone: "hero", font: "display", sizeFactor: 0.15, minPt: 6.5, maxLines: 2, color: "text", casing: "uppercase", letterSpacingEm: 0.04 },
      { slot: "strength", zone: "hero", font: "body", weight: 700, sizeFactor: 0.068, minPt: 4.5, maxLines: 1, color: "accent", spacingBefore: 1 },
      { slot: "subtitle", zone: "hero", font: "body", sizeFactor: 0.048, minPt: 4, maxLines: 1, color: "muted", spacingBefore: 0.6 },
      { slot: "volume", zone: "footer", font: "body", sizeFactor: 0.046, minPt: 4, maxLines: 1, color: "muted" },
      ...footerRows(),
    ],
    codeCorner: "bottom-left",
    decor: [
      { kind: "stripe", edge: "left", widthFactor: 0.09, fill: { effect: true } },
    ],
  }),
  defineTemplate({
    id: "holographic-monogram",
    name: "Holographic Monogram",
    family: "holographic-monogram",
    familyName: "Holographic Monogram",
    category: ["holographic", "luxury"],
    mood: ["monogram", "medallion", "spectral"],
    vibe: { luxury: 2, futuristic: 1, premium: 2 },
    colorMode: "dark",
    density: "minimal",
    pairingId: "editorial-beauty",
    recommendedGlass: ["opaque", "amber"],
    align: "center",
    minHeightMm: 18,
    materials: ["holographic", "metallic", "glossy"],
    rows: [
      { slot: "brand", zone: "header", font: "display", sizeFactor: 0.13, minPt: 7, maxLines: 1, color: "text", monogram: true },
      { slot: "product-name", zone: "hero", font: "display", sizeFactor: 0.13, minPt: 6.5, maxLines: 2, color: "text", spacingBefore: 1.4 },
      { slot: "strength", zone: "hero", font: "body", weight: 600, sizeFactor: 0.058, minPt: 4.5, maxLines: 1, color: "accent", letterSpacingEm: 0.14, spacingBefore: 1 },
      { slot: "subtitle", zone: "hero", font: "body", sizeFactor: 0.046, minPt: 4, maxLines: 1, color: "muted", spacingBefore: 0.6 },
      { slot: "volume", zone: "footer", font: "body", sizeFactor: 0.046, minPt: 4, maxLines: 1, color: "muted" },
      ...footerRows(),
    ],
    codeCorner: "bottom-right",
    decor: [
      { kind: "medallion", sizeFactor: 0.22, fill: { effect: true }, minLabelHeightMm: 18 },
    ],
  }),
  // --- Neon ---------------------------------------------------------------------
  defineTemplate({
    id: "acid-signal",
    name: "Acid Signal",
    family: "acid-signal",
    familyName: "Acid Signal",
    category: ["neon", "plain"],
    mood: ["loud", "condensed", "badged"],
    vibe: { bold: 3, playful: 1, futuristic: 1 },
    colorMode: "dark",
    density: "standard",
    pairingId: "condensed-impact",
    recommendedGlass: ["clear"],
    featured: true,
    align: "left",
    materials: ["neon", "plain", "glossy"],
    rows: [
      { slot: "brand", zone: "header", font: "body", weight: 600, sizeFactor: 0.055, minPt: 4.5, maxLines: 1, color: "muted", letterSpacingEm: 0.14, casing: "uppercase" },
      { slot: "product-name", zone: "hero", font: "display", sizeFactor: 0.22, minPt: 8.5, maxLines: 2, color: "text", casing: "uppercase" },
      { slot: "strength", zone: "hero", font: "body", weight: 600, sizeFactor: 0.07, minPt: 4.5, maxLines: 1, color: "onAccent", chip: "fill", spacingBefore: 1.3 },
      { slot: "subtitle", zone: "hero", font: "body", sizeFactor: 0.05, minPt: 4, maxLines: 1, color: "muted", spacingBefore: 0.8 },
      { slot: "volume", zone: "footer", font: "body", weight: 600, sizeFactor: 0.05, minPt: 4, maxLines: 1, color: "muted" },
      ...footerRows(),
    ],
    codeCorner: "bottom-right",
    decor: [
      { kind: "corners", lengthMm: 3, strokePt: 1.1, color: "accent", insetMm: 1.3, minLabelHeightMm: 14 },
    ],
  }),
  defineTemplate({
    id: "electric-cyan",
    name: "Electric Cyan",
    family: "electric-cyan",
    familyName: "Electric Cyan",
    category: ["neon"],
    mood: ["electric", "rounded", "energetic"],
    vibe: { bold: 2, playful: 2, futuristic: 1 },
    colorMode: "dark",
    density: "standard",
    pairingId: "audiowide-energy",
    recommendedGlass: ["cobalt", "clear"],
    align: "center",
    materials: ["neon", "plain", "glossy"],
    rows: [
      { slot: "brand", zone: "header", font: "body", weight: 700, sizeFactor: 0.052, minPt: 4.5, maxLines: 1, color: "muted", letterSpacingEm: 0.2, casing: "uppercase" },
      { slot: "product-name", zone: "hero", font: "display", sizeFactor: 0.13, minPt: 6.5, maxLines: 2, color: "text" },
      { slot: "strength", zone: "hero", font: "body", weight: 700, sizeFactor: 0.066, minPt: 4.5, maxLines: 1, color: "accent", letterSpacingEm: 0.1, spacingBefore: 1.1 },
      { slot: "subtitle", zone: "hero", font: "body", sizeFactor: 0.048, minPt: 4, maxLines: 1, color: "muted", spacingBefore: 0.6 },
      { slot: "volume", zone: "footer", font: "body", sizeFactor: 0.046, minPt: 4, maxLines: 1, color: "muted" },
      ...footerRows(),
    ],
    codeCorner: "bottom-left",
    decor: [
      { kind: "band", edge: "bottom", heightFactor: 0.1, fill: { role: "accent" }, inset: true, minLabelHeightMm: 15 },
    ],
  }),
  defineTemplate({
    id: "laser-grid",
    name: "Laser Grid",
    family: "laser-grid",
    familyName: "Laser Grid",
    category: ["neon", "laboratory"],
    mood: ["gridded", "railed", "cyber"],
    vibe: { futuristic: 3, bold: 1 },
    colorMode: "dark",
    density: "standard",
    pairingId: "tech-lab",
    recommendedGlass: ["cobalt", "clear"],
    align: "center",
    materials: ["neon", "holographic", "plain", "glossy"],
    rows: [
      { slot: "brand", zone: "header", font: "body", weight: 600, sizeFactor: 0.05, minPt: 4.5, maxLines: 1, color: "accent", letterSpacingEm: 0.3, casing: "uppercase" },
      { slot: "product-name", zone: "hero", font: "display", sizeFactor: 0.135, minPt: 6.5, maxLines: 2, color: "text", casing: "uppercase", letterSpacingEm: 0.05 },
      { slot: "strength", zone: "hero", font: "body", weight: 700, sizeFactor: 0.064, minPt: 4.5, maxLines: 1, color: "accent", letterSpacingEm: 0.16, spacingBefore: 1.1 },
      { slot: "subtitle", zone: "hero", font: "body", sizeFactor: 0.046, minPt: 4, maxLines: 1, color: "muted", letterSpacingEm: 0.1, spacingBefore: 0.6 },
      { slot: "volume", zone: "footer", font: "body", sizeFactor: 0.046, minPt: 4, maxLines: 1, color: "muted" },
      ...footerRows(),
    ],
    codeCorner: "bottom-right",
    decor: [
      { kind: "side-rail", edge: "left", insetMm: 1.2, strokePt: 1, color: "accent" },
      { kind: "side-rail", edge: "right", insetMm: 1.2, strokePt: 1, color: "accent" },
      { kind: "divider", after: "product-name", widthFactor: 0.3, strokePt: 0.7, fill: { role: "accent" } },
    ],
  }),
  defineTemplate({
    id: "cyber-pulse",
    name: "Cyber Pulse",
    family: "cyber-pulse",
    familyName: "Cyber Pulse",
    category: ["neon", "laboratory"],
    mood: ["split", "pulse", "dense"],
    vibe: { futuristic: 3, clinical: 1 },
    colorMode: "dark",
    density: "detailed",
    pairingId: "futuristic",
    recommendedGlass: ["cobalt"],
    align: "left",
    minHeightMm: 22,
    minWidthMm: 45,
    materials: ["neon", "holographic", "plain", "glossy"],
    split: { ratio: 0.6, divider: true },
    rows: [
      { slot: "brand", zone: "header", font: "body", weight: 700, sizeFactor: 0.052, minPt: 4.5, maxLines: 1, color: "muted", letterSpacingEm: 0.2, casing: "uppercase" },
      { slot: "product-name", zone: "hero", font: "display", sizeFactor: 0.15, minPt: 6.5, maxLines: 2, color: "text", casing: "uppercase" },
      { slot: "strength", zone: "hero", font: "body", weight: 700, sizeFactor: 0.07, minPt: 4.5, maxLines: 1, color: "accent", spacingBefore: 1 },
      { slot: "subtitle", zone: "hero", font: "body", sizeFactor: 0.048, minPt: 4, maxLines: 2, color: "muted", spacingBefore: 0.6 },
      { slot: "volume", zone: "header", font: "technical", sizeFactor: 0.046, minPt: 4, maxLines: 1, color: "muted", column: "right" },
      { slot: "lot", zone: "header", font: "technical", sizeFactor: 0.046, minPt: 4, maxLines: 1, color: "muted", column: "right", spacingBefore: 0.35 },
      { slot: "expiry", zone: "header", font: "technical", sizeFactor: 0.046, minPt: 4, maxLines: 1, color: "muted", column: "right", spacingBefore: 0.25 },
      { slot: "description", zone: "hero", font: "body", sizeFactor: 0.044, minPt: 4, maxLines: 3, color: "muted", column: "right" },
      { slot: "ingredients", zone: "footer", font: "body", sizeFactor: 0.042, minPt: 4, maxLines: 3, color: "muted", column: "right" },
      { slot: "directions", zone: "footer", font: "body", sizeFactor: 0.042, minPt: 4, maxLines: 2, color: "muted", column: "right", spacingBefore: 0.35 },
      { slot: "storage", zone: "footer", font: "body", sizeFactor: 0.042, minPt: 4, maxLines: 1, color: "muted", column: "right", spacingBefore: 0.35 },
      { slot: "warning", zone: "footer", font: "body", emphasis: true, sizeFactor: 0.044, minPt: 4, maxLines: 2, color: "text" },
      { slot: "verification", zone: "footer", font: "technical", sizeFactor: 0.042, minPt: 4, maxLines: 1, color: "muted", spacingBefore: 0.3 },
      { slot: "website", zone: "footer", font: "body", emphasis: true, sizeFactor: 0.044, minPt: 4, maxLines: 1, color: "accent", spacingBefore: 0.4 },
    ],
    codeCorner: "bottom-right",
    decor: [],
  }),
] as const;
