import { footerRows } from "./core";
import type { EasyTemplateDef } from "./types";
import { defineTemplate } from "./types";

/**
 * Plain/minimal, beauty, botanical, and transparent flagship families
 * (§5): strong without effects — typography, spacing, and hierarchy do
 * the work.
 */

export const EVERYDAY_TEMPLATES: readonly EasyTemplateDef[] = [
  // --- Plain & minimal -----------------------------------------------------------
  defineTemplate({
    id: "essential-white",
    name: "Essential White",
    family: "essential-white",
    familyName: "Essential White",
    category: ["plain", "clinical", "beauty"],
    mood: ["essential", "quiet", "brand-below"],
    vibe: { minimal: 3, clinical: 1 },
    colorMode: "light",
    density: "minimal",
    pairingId: "neutral-inter",
    recommendedGlass: ["clear"],
    featured: true,
    align: "center",
    rows: [
      { slot: "product-name", zone: "hero", font: "display", sizeFactor: 0.17, minPt: 7.5, maxLines: 2, color: "text" },
      { slot: "strength", zone: "hero", font: "body", sizeFactor: 0.062, minPt: 4.5, maxLines: 1, color: "muted", spacingBefore: 1 },
      { slot: "subtitle", zone: "hero", font: "body", sizeFactor: 0.05, minPt: 4, maxLines: 1, color: "muted", spacingBefore: 0.6 },
      { slot: "brand", zone: "footer", font: "body", weight: 600, sizeFactor: 0.05, minPt: 4.5, maxLines: 1, color: "text", letterSpacingEm: 0.22, casing: "uppercase" },
      { slot: "volume", zone: "footer", font: "body", sizeFactor: 0.046, minPt: 4, maxLines: 1, color: "muted", spacingBefore: 0.4 },
      ...footerRows(),
    ],
    codeCorner: "bottom-right",
    decor: [],
  }),
  defineTemplate({
    id: "clean-border",
    name: "Clean Border",
    family: "clean-border",
    familyName: "Clean Border",
    category: ["plain", "clinical"],
    mood: ["bordered", "friendly", "simple"],
    vibe: { minimal: 2, clinical: 1, playful: 1 },
    colorMode: "light",
    density: "standard",
    pairingId: "contemporary-skincare",
    recommendedGlass: ["clear", "amber"],
    align: "left",
    rows: [
      { slot: "brand", zone: "header", font: "body", weight: 600, sizeFactor: 0.055, minPt: 4.5, maxLines: 1, color: "accent", letterSpacingEm: 0.08, casing: "uppercase" },
      { slot: "product-name", zone: "hero", font: "display", sizeFactor: 0.15, minPt: 7, maxLines: 2, color: "text" },
      { slot: "subtitle", zone: "hero", font: "body", sizeFactor: 0.05, minPt: 4, maxLines: 1, color: "muted", spacingBefore: 0.8 },
      { slot: "strength", zone: "hero", font: "body", weight: 600, sizeFactor: 0.064, minPt: 4.5, maxLines: 1, color: "text", spacingBefore: 1 },
      { slot: "volume", zone: "footer", font: "body", sizeFactor: 0.048, minPt: 4, maxLines: 1, color: "muted" },
      ...footerRows(),
    ],
    codeCorner: "bottom-right",
    decor: [
      { kind: "border", insetMm: 1.4, strokePt: 1.1, color: "border" },
    ],
  }),
  defineTemplate({
    id: "single-accent",
    name: "Single Accent",
    family: "single-accent",
    familyName: "Single Accent",
    category: ["plain", "botanical", "beauty"],
    mood: ["dotted", "warm", "centered"],
    vibe: { minimal: 2, botanical: 1, playful: 1 },
    colorMode: "light",
    density: "minimal",
    pairingId: "warm-editorial",
    recommendedGlass: ["clear", "amber"],
    align: "center",
    rows: [
      { slot: "brand", zone: "header", font: "body", weight: 600, sizeFactor: 0.05, minPt: 4.5, maxLines: 1, color: "muted", letterSpacingEm: 0.2, casing: "uppercase" },
      { slot: "product-name", zone: "hero", font: "display", sizeFactor: 0.16, minPt: 7, maxLines: 2, color: "text", spacingBefore: 1.6 },
      { slot: "subtitle", zone: "hero", font: "body", sizeFactor: 0.05, minPt: 4, maxLines: 2, color: "muted", spacingBefore: 0.9 },
      { slot: "strength", zone: "hero", font: "body", weight: 600, sizeFactor: 0.058, minPt: 4.5, maxLines: 1, color: "accent", spacingBefore: 1.1 },
      { slot: "volume", zone: "footer", font: "body", sizeFactor: 0.046, minPt: 4, maxLines: 1, color: "muted" },
      ...footerRows(),
    ],
    codeCorner: "bottom-right",
    decor: [
      { kind: "divider", after: "brand", widthFactor: 0.07, strokePt: 1.6, fill: { role: "accent" } },
    ],
  }),
  // --- Beauty & skincare -----------------------------------------------------------
  defineTemplate({
    id: "soft-serum",
    name: "Soft Serum",
    family: "soft-serum",
    familyName: "Soft Serum",
    category: ["beauty", "plain"],
    mood: ["soft", "airy", "modern"],
    vibe: { minimal: 2, luxury: 1, botanical: 1 },
    colorMode: "light",
    density: "minimal",
    pairingId: "contemporary-skincare",
    recommendedGlass: ["frosted", "clear"],
    featured: true,
    align: "left",
    rows: [
      { slot: "brand", zone: "header", font: "body", weight: 600, sizeFactor: 0.052, minPt: 4.5, maxLines: 1, color: "text", letterSpacingEm: 0.16, casing: "uppercase" },
      { slot: "product-name", zone: "hero", font: "display", sizeFactor: 0.15, minPt: 7, maxLines: 2, color: "text" },
      { slot: "subtitle", zone: "hero", font: "body", sizeFactor: 0.052, minPt: 4, maxLines: 2, color: "muted", spacingBefore: 0.9 },
      { slot: "strength", zone: "hero", font: "body", sizeFactor: 0.058, minPt: 4.5, maxLines: 1, color: "accent", spacingBefore: 1.2 },
      { slot: "volume", zone: "footer", font: "body", sizeFactor: 0.046, minPt: 4, maxLines: 1, color: "muted" },
      ...footerRows(),
    ],
    codeCorner: "bottom-right",
    decor: [
      { kind: "divider", after: "brand", widthFactor: 0.16, strokePt: 0.8, fill: { role: "accent" } },
    ],
  }),
  defineTemplate({
    id: "rosewater",
    name: "Rosewater",
    family: "rosewater",
    familyName: "Rosewater",
    category: ["beauty", "luxury"],
    mood: ["blush", "editorial", "banded"],
    vibe: { luxury: 2, botanical: 1, minimal: 1 },
    colorMode: "light",
    density: "standard",
    pairingId: "editorial-beauty",
    recommendedGlass: ["frosted", "clear"],
    align: "center",
    rows: [
      { slot: "brand", zone: "header", font: "body", weight: 600, sizeFactor: 0.052, minPt: 4.5, maxLines: 1, color: "muted", letterSpacingEm: 0.26, casing: "uppercase" },
      // Kicker: the subtitle sits ABOVE the product name, magazine-style.
      { slot: "subtitle", zone: "hero", font: "body", sizeFactor: 0.046, minPt: 4, maxLines: 1, color: "accent", letterSpacingEm: 0.2, casing: "uppercase" },
      { slot: "product-name", zone: "hero", font: "display", sizeFactor: 0.165, minPt: 7, maxLines: 2, color: "text", spacingBefore: 0.6 },
      { slot: "strength", zone: "hero", font: "body", weight: 600, sizeFactor: 0.056, minPt: 4.5, maxLines: 1, color: "accent", chip: "outline", spacingBefore: 1.4 },
      { slot: "volume", zone: "footer", font: "body", sizeFactor: 0.046, minPt: 4, maxLines: 1, color: "muted" },
      ...footerRows(),
    ],
    codeCorner: "bottom-left",
    decor: [
      { kind: "band", edge: "bottom", heightFactor: 0.12, fill: { role: "accent" }, inset: true, minLabelHeightMm: 15 },
    ],
  }),
  defineTemplate({
    id: "modern-apothecary",
    name: "Modern Apothecary",
    family: "modern-apothecary",
    familyName: "Modern Apothecary",
    category: ["botanical", "beauty", "plain"],
    mood: ["apothecary", "heritage", "framed"],
    vibe: { botanical: 3, luxury: 1 },
    colorMode: "light",
    density: "standard",
    pairingId: "heritage-apothecary",
    recommendedGlass: ["amber"],
    featured: true,
    align: "center",
    materials: ["kraft", "plain", "matte", "clear", "glossy"],
    rows: [
      { slot: "brand", zone: "header", font: "display", weight: 700, sizeFactor: 0.062, minPt: 4.5, maxLines: 1, color: "text", letterSpacingEm: 0.1 },
      { slot: "product-name", zone: "hero", font: "display", sizeFactor: 0.15, minPt: 7, maxLines: 2, color: "text" },
      { slot: "subtitle", zone: "hero", font: "body", sizeFactor: 0.05, minPt: 4, maxLines: 2, color: "muted", spacingBefore: 0.9 },
      { slot: "strength", zone: "hero", font: "body", weight: 600, sizeFactor: 0.058, minPt: 4.5, maxLines: 1, color: "accent", spacingBefore: 1 },
      { slot: "volume", zone: "footer", font: "body", sizeFactor: 0.046, minPt: 4, maxLines: 1, color: "muted" },
      ...footerRows(),
    ],
    codeCorner: "bottom-right",
    decor: [
      { kind: "border", insetMm: 1.2, strokePt: 0.7, color: "text" },
      { kind: "divider", after: "brand", widthFactor: 0.24, strokePt: 0.5, fill: { role: "muted" } },
    ],
  }),
  // --- Transparent ------------------------------------------------------------------
  defineTemplate({
    id: "floating-type",
    name: "Floating Type",
    family: "floating-type",
    familyName: "Floating Type",
    category: ["transparent", "plain"],
    mood: ["floating", "no-label", "minimal"],
    vibe: { minimal: 3, premium: 1 },
    colorMode: "light",
    density: "minimal",
    pairingId: "minimal-premium",
    recommendedGlass: ["clear", "frosted"],
    featured: true,
    align: "center",
    materials: ["clear", "plain", "glossy", "holographic"],
    rows: [
      { slot: "brand", zone: "header", font: "body", weight: 600, sizeFactor: 0.052, minPt: 4.5, maxLines: 1, color: "text", letterSpacingEm: 0.34, casing: "uppercase" },
      { slot: "product-name", zone: "hero", font: "display", sizeFactor: 0.155, minPt: 7, maxLines: 2, color: "text" },
      { slot: "strength", zone: "hero", font: "body", weight: 600, sizeFactor: 0.06, minPt: 4.5, maxLines: 1, color: "text", spacingBefore: 1.2 },
      { slot: "subtitle", zone: "hero", font: "body", sizeFactor: 0.048, minPt: 4, maxLines: 1, color: "muted", spacingBefore: 0.7 },
      { slot: "volume", zone: "footer", font: "body", sizeFactor: 0.046, minPt: 4, maxLines: 1, color: "muted" },
      ...footerRows(),
    ],
    codeCorner: "bottom-right",
    decor: [],
  }),
  defineTemplate({
    id: "clear-clinical",
    name: "Clear Clinical",
    family: "clear-clinical",
    familyName: "Clear Clinical",
    category: ["transparent", "clinical"],
    mood: ["window", "precise", "left"],
    vibe: { clinical: 3, minimal: 2 },
    colorMode: "light",
    density: "standard",
    pairingId: "modern-clinical",
    recommendedGlass: ["clear", "cobalt"],
    align: "left",
    materials: ["clear", "plain", "matte"],
    rows: [
      { slot: "brand", zone: "header", font: "body", weight: 600, sizeFactor: 0.055, minPt: 4.5, maxLines: 1, color: "text", letterSpacingEm: 0.12, casing: "uppercase" },
      { slot: "product-name", zone: "hero", font: "display", sizeFactor: 0.14, minPt: 6.5, maxLines: 2, color: "text" },
      { slot: "strength", zone: "hero", font: "body", weight: 600, sizeFactor: 0.062, minPt: 4.5, maxLines: 1, color: "text", spacingBefore: 0.9 },
      { slot: "subtitle", zone: "hero", font: "body", sizeFactor: 0.048, minPt: 4, maxLines: 1, color: "muted", spacingBefore: 0.5 },
      { slot: "volume", zone: "footer", font: "technical", sizeFactor: 0.046, minPt: 4, maxLines: 1, color: "muted" },
      { slot: "lot", zone: "footer", font: "technical", sizeFactor: 0.044, minPt: 4, maxLines: 1, color: "muted", spacingBefore: 0.3 },
      { slot: "expiry", zone: "footer", font: "technical", sizeFactor: 0.044, minPt: 4, maxLines: 1, color: "muted", spacingBefore: 0.25 },
      { slot: "warning", zone: "footer", font: "body", emphasis: true, sizeFactor: 0.044, minPt: 4, maxLines: 2, color: "text", spacingBefore: 0.4 },
      { slot: "website", zone: "footer", font: "body", sizeFactor: 0.046, minPt: 4, maxLines: 1, color: "accent", spacingBefore: 0.4 },
    ],
    codeCorner: "bottom-right",
    decor: [
      { kind: "side-rail", edge: "left", insetMm: 1.2, strokePt: 1.2, color: "text" },
    ],
  }),
] as const;
