import {
  brandBottom,
  brandCaps,
  detailBlock,
  kickerSubtitle,
  productHero,
  strengthRow,
  subtitleRow,
  volumeRow,
} from "./parts";
import type { EasyTemplateDef } from "./types";
import { defineTemplate } from "./types";

/** Library expansion — luxury, glossy, and plain families (§4/§5). */

export const LUXE_EXPANSION: readonly EasyTemplateDef[] = [
  // --- Luxury -----------------------------------------------------------------
  defineTemplate({
    id: "black-prism",
    name: "Black Prism",
    family: "black-prism",
    familyName: "Black Prism",
    category: ["luxury", "holographic"],
    mood: ["prismatic", "kicker", "framed"],
    vibe: { luxury: 2, premium: 2, futuristic: 1 },
    colorMode: "dark",
    density: "standard",
    pairingId: "editorial-beauty",
    recommendedGlass: ["opaque", "amber"],
    align: "center",
    rows: [
      brandCaps({ letterSpacingEm: 0.3 }),
      kickerSubtitle({ spacingBefore: 0.4 }),
      productHero(0.15, { spacingBefore: 0.5 }),
      strengthRow({ weight: 600, letterSpacingEm: 0.14, casing: "uppercase", sizeFactor: 0.06 }),
      volumeRow(),
      ...detailBlock(),
    ],
    codeCorner: "bottom-right",
    decor: [{ kind: "frame-effect", thicknessFactor: 0.04, minLabelHeightMm: 14 }],
    materials: ["holographic", "metallic", "glossy", "plain"],
  }),
  defineTemplate({
    id: "architectural-gold",
    name: "Architectural Gold",
    family: "architectural-gold",
    familyName: "Architectural Gold",
    category: ["luxury"],
    mood: ["structured", "columned", "gold"],
    vibe: { luxury: 3, premium: 2, clinical: 1 },
    colorMode: "dark",
    density: "detailed",
    pairingId: "prata-elegant",
    recommendedGlass: ["amber", "opaque"],
    align: "left",
    minHeightMm: 22,
    minWidthMm: 45,
    split: { ratio: 0.62 },
    rows: [
      brandCaps({ color: "accent", weight: 600, letterSpacingEm: 0.3 }),
      productHero(0.16),
      subtitleRow({ maxLines: 2 }),
      strengthRow({ weight: 500, letterSpacingEm: 0.14 }),
      volumeRow("header", { column: "right", font: "technical" }),
      { slot: "description", zone: "hero", font: "body", sizeFactor: 0.046, minPt: 4, maxLines: 4, color: "muted", column: "right" },
      { slot: "ingredients", zone: "footer", font: "body", sizeFactor: 0.042, minPt: 4, maxLines: 3, color: "muted", column: "right" },
      { slot: "directions", zone: "footer", font: "body", sizeFactor: 0.042, minPt: 4, maxLines: 2, color: "muted", column: "right", spacingBefore: 0.4 },
      { slot: "storage", zone: "footer", font: "body", sizeFactor: 0.042, minPt: 4, maxLines: 1, color: "muted", column: "right", spacingBefore: 0.4 },
      { slot: "warning", zone: "footer", font: "body", emphasis: true, sizeFactor: 0.042, minPt: 4, maxLines: 2, color: "text", column: "right", spacingBefore: 0.4 },
      { slot: "lot", zone: "footer", font: "technical", sizeFactor: 0.044, minPt: 4, maxLines: 1, color: "muted" },
      { slot: "expiry", zone: "footer", font: "technical", sizeFactor: 0.044, minPt: 4, maxLines: 1, color: "muted", spacingBefore: 0.25 },
      { slot: "verification", zone: "footer", font: "technical", sizeFactor: 0.042, minPt: 4, maxLines: 1, color: "muted", spacingBefore: 0.25 },
      { slot: "website", zone: "footer", font: "body", weight: 600, sizeFactor: 0.044, minPt: 4, maxLines: 1, color: "accent", spacingBefore: 0.5 },
    ],
    codeCorner: "bottom-right",
    decor: [{ kind: "side-rail", edge: "left", insetMm: 1.2, strokePt: 1.4, color: "accent" }],
  }),
  defineTemplate({
    id: "liquid-silver",
    name: "Liquid Silver",
    family: "liquid-silver",
    familyName: "Liquid Silver",
    category: ["luxury", "glossy"],
    mood: ["fluid", "vertical", "sleek"],
    vibe: { luxury: 2, premium: 2, minimal: 1 },
    colorMode: "light",
    density: "standard",
    pairingId: "minimal-premium",
    recommendedGlass: ["clear", "frosted"],
    align: "center",
    minHeightMm: 16,
    verticalRow: { slot: "brand", edge: "right", font: "body", weight: 600, sizeFactor: 0.048, minPt: 4.5, color: "muted", letterSpacingEm: 0.26, casing: "uppercase" },
    rows: [
      productHero(0.155),
      subtitleRow(),
      strengthRow({ weight: 600, sizeFactor: 0.06 }),
      volumeRow(),
      ...detailBlock(),
    ],
    codeCorner: "bottom-left",
    decor: [{ kind: "underline-hero", widthFactor: 0.16, strokePt: 0.9, fill: { effect: true } }],
    materials: ["metallic", "holographic", "glossy", "plain", "matte"],
  }),
  defineTemplate({
    id: "pearl-minimal",
    name: "Pearl Minimal",
    family: "pearl-minimal",
    familyName: "Pearl Minimal",
    category: ["luxury", "plain", "beauty"],
    mood: ["pearl", "quiet", "serif"],
    vibe: { luxury: 2, minimal: 3 },
    colorMode: "light",
    density: "minimal",
    pairingId: "quiet-luxury",
    recommendedGlass: ["frosted", "opaque"],
    align: "center",
    rows: [
      brandCaps({ letterSpacingEm: 0.3, weight: 500 }),
      productHero(0.16, { spacingBefore: 1.2 }),
      strengthRow({ weight: 500, color: "muted", sizeFactor: 0.055, spacingBefore: 1.2 }),
      subtitleRow({ spacingBefore: 0.6 }),
      volumeRow(),
      ...detailBlock(),
    ],
    codeCorner: "bottom-right",
    decor: [],
  }),
  defineTemplate({
    id: "gilded-column",
    name: "Gilded Column",
    family: "gilded-column",
    familyName: "Gilded Column",
    category: ["luxury"],
    mood: ["engraved", "vertical", "bordered"],
    vibe: { luxury: 3, premium: 2 },
    colorMode: "dark",
    density: "standard",
    pairingId: "classic-estate",
    recommendedGlass: ["amber", "opaque"],
    align: "left",
    minHeightMm: 16,
    verticalRow: { slot: "brand", edge: "left", font: "display", sizeFactor: 0.05, minPt: 4.5, color: "accent", letterSpacingEm: 0.2, casing: "uppercase" },
    rows: [
      productHero(0.15),
      subtitleRow(),
      strengthRow({ weight: 500, letterSpacingEm: 0.14 }),
      volumeRow(),
      ...detailBlock(),
    ],
    codeCorner: "bottom-right",
    decor: [
      { kind: "border", insetMm: 1.1, strokePt: 0.7, color: "accent" },
      { kind: "border", insetMm: 1.8, strokePt: 0.35, color: "accent", minLabelHeightMm: 15 },
    ],
  }),
  defineTemplate({
    id: "estate-monogram",
    name: "Estate Monogram",
    family: "estate-frame",
    familyName: "Estate Frame",
    category: ["luxury"],
    mood: ["monogram", "cornered", "formal"],
    vibe: { premium: 3, luxury: 2, minimal: 1 },
    colorMode: "dark",
    density: "minimal",
    pairingId: "prata-elegant",
    recommendedGlass: ["amber"],
    align: "center",
    minHeightMm: 18,
    rows: [
      { slot: "brand", zone: "header", font: "display", sizeFactor: 0.13, minPt: 7, maxLines: 1, color: "accent", monogram: true },
      productHero(0.125, { casing: "uppercase", letterSpacingEm: 0.08, spacingBefore: 1.6 }),
      strengthRow({ weight: 500, sizeFactor: 0.055, letterSpacingEm: 0.16 }),
      subtitleRow({ sizeFactor: 0.046 }),
      volumeRow(),
      ...detailBlock(),
    ],
    codeCorner: "bottom-right",
    decor: [
      { kind: "corners", lengthMm: 3, strokePt: 0.7, color: "accent", insetMm: 1.4, minLabelHeightMm: 15 },
    ],
  }),
  defineTemplate({
    id: "velvet-noir",
    name: "Velvet Noir",
    family: "velvet-noir",
    familyName: "Velvet Noir",
    category: ["luxury", "glossy"],
    mood: ["noir", "condensed", "divided"],
    vibe: { premium: 2, bold: 2, luxury: 2 },
    colorMode: "dark",
    density: "standard",
    pairingId: "condensed-impact",
    recommendedGlass: ["opaque", "amber"],
    align: "left",
    rows: [
      brandCaps({ letterSpacingEm: 0.24, weight: 400 }),
      productHero(0.19, { casing: "uppercase", minPt: 8 }),
      strengthRow({ letterSpacingEm: 0.1 }),
      subtitleRow(),
      volumeRow(),
      ...detailBlock(),
    ],
    codeCorner: "bottom-right",
    decor: [
      { kind: "divider", after: "product-name", widthFactor: 0.22, strokePt: 0.6, fill: { role: "accent" } },
    ],
  }),
  defineTemplate({
    id: "golden-ratio",
    name: "Golden Ratio",
    family: "golden-ratio",
    familyName: "Golden Ratio",
    category: ["luxury", "botanical"],
    mood: ["warm", "kicker", "banded"],
    vibe: { luxury: 2, botanical: 2, premium: 1 },
    colorMode: "light",
    density: "standard",
    pairingId: "warm-editorial",
    recommendedGlass: ["amber", "clear"],
    align: "center",
    rows: [
      brandCaps({ letterSpacingEm: 0.22 }),
      kickerSubtitle({ spacingBefore: 0.5 }),
      productHero(0.16, { spacingBefore: 0.5 }),
      strengthRow({ sizeFactor: 0.058 }),
      volumeRow(),
      ...detailBlock(),
    ],
    codeCorner: "bottom-left",
    decor: [
      { kind: "band", edge: "top", heightFactor: 0.07, fill: { role: "accent" }, inset: true, minLabelHeightMm: 14 },
    ],
  }),
  defineTemplate({
    id: "silver-thread",
    name: "Silver Thread",
    family: "silver-thread",
    familyName: "Silver Thread",
    category: ["luxury", "beauty"],
    mood: ["threaded", "airy", "right-rail"],
    vibe: { luxury: 2, minimal: 2 },
    colorMode: "light",
    density: "standard",
    pairingId: "luxury-classic",
    recommendedGlass: ["frosted", "clear"],
    align: "left",
    rows: [
      brandCaps({ letterSpacingEm: 0.24, weight: 500 }),
      productHero(0.155),
      subtitleRow({ maxLines: 2 }),
      strengthRow({ weight: 500, color: "text" }),
      volumeRow(),
      ...detailBlock(),
    ],
    codeCorner: "bottom-left",
    decor: [{ kind: "side-rail", edge: "right", insetMm: 1.3, strokePt: 0.9, color: "border" }],
  }),
  defineTemplate({
    id: "imperial-line",
    name: "Imperial Line",
    family: "imperial-emerald",
    familyName: "Imperial Emerald",
    category: ["luxury", "botanical"],
    mood: ["regal", "stacked", "bordered"],
    vibe: { luxury: 3, premium: 1, botanical: 1 },
    colorMode: "dark",
    density: "standard",
    pairingId: "botanical-premium",
    recommendedGlass: ["amber", "cobalt"],
    align: "center",
    rows: [
      brandCaps({ color: "accent", weight: 600, letterSpacingEm: 0.28 }),
      productHero(0.15),
      subtitleRow(),
      strengthRow({ weight: 500 }),
      volumeRow(),
      ...detailBlock(),
    ],
    codeCorner: "bottom-right",
    decor: [
      { kind: "border", insetMm: 1.1, strokePt: 0.6, color: "accent" },
      { kind: "divider", after: "strength", widthFactor: 0.14, strokePt: 0.6, fill: { role: "accent" } },
    ],
  }),
  defineTemplate({
    id: "luxe-band",
    name: "Luxe Band",
    family: "luxe-band",
    familyName: "Luxe Band",
    category: ["luxury", "glossy"],
    mood: ["banded", "serif", "grounded"],
    vibe: { luxury: 2, premium: 2 },
    colorMode: "dark",
    density: "standard",
    pairingId: "luxury-classic",
    recommendedGlass: ["amber", "opaque"],
    align: "center",
    rows: [
      brandCaps({ letterSpacingEm: 0.3, weight: 500 }),
      productHero(0.16),
      subtitleRow(),
      strengthRow({ weight: 500, letterSpacingEm: 0.12 }),
      volumeRow(),
      ...detailBlock(),
    ],
    codeCorner: "bottom-right",
    decor: [
      { kind: "band", edge: "bottom", heightFactor: 0.06, fill: { role: "accent" } },
      { kind: "divider", after: "product-name", widthFactor: 0.12, strokePt: 0.7, fill: { role: "accent" } },
    ],
  }),
  defineTemplate({
    id: "onyx-grid",
    name: "Onyx Grid",
    family: "onyx-grid",
    familyName: "Onyx Grid",
    category: ["luxury", "glossy"],
    mood: ["railed", "modern", "grid"],
    vibe: { premium: 2, bold: 1, futuristic: 1, luxury: 1 },
    colorMode: "dark",
    density: "standard",
    pairingId: "bold-modern",
    recommendedGlass: ["opaque", "cobalt"],
    align: "center",
    rows: [
      brandCaps({ letterSpacingEm: 0.26 }),
      productHero(0.15, { casing: "uppercase", letterSpacingEm: 0.03 }),
      strengthRow({ sizeFactor: 0.062, letterSpacingEm: 0.12 }),
      subtitleRow({ sizeFactor: 0.046 }),
      volumeRow(),
      ...detailBlock(),
    ],
    codeCorner: "bottom-right",
    decor: [
      { kind: "side-rail", edge: "left", insetMm: 1.3, strokePt: 0.8, color: "accent" },
      { kind: "side-rail", edge: "right", insetMm: 1.3, strokePt: 0.8, color: "accent" },
    ],
  }),
  // --- Glossy -------------------------------------------------------------------
  defineTemplate({
    id: "gloss-black",
    name: "Gloss Black",
    family: "gloss-black",
    familyName: "Gloss Black",
    category: ["glossy", "luxury"],
    mood: ["piano-black", "display", "badged"],
    vibe: { premium: 3, bold: 1, minimal: 1 },
    colorMode: "dark",
    density: "standard",
    pairingId: "minimal-premium",
    recommendedGlass: ["opaque", "amber"],
    featured: true,
    align: "center",
    rows: [
      brandCaps({ letterSpacingEm: 0.3 }),
      productHero(0.16),
      { slot: "strength", zone: "hero", font: "display", sizeFactor: 0.085, minPt: 5, maxLines: 1, color: "onAccent", chip: "fill", spacingBefore: 1.4 },
      subtitleRow(),
      volumeRow(),
      ...detailBlock(),
    ],
    codeCorner: "bottom-right",
    decor: [],
    materials: ["glossy", "plain", "metallic", "matte"],
  }),
  defineTemplate({
    id: "gloss-white",
    name: "Gloss White",
    family: "gloss-white",
    familyName: "Gloss White",
    category: ["glossy", "beauty", "plain"],
    mood: ["bright", "clean", "outlined"],
    vibe: { minimal: 2, clinical: 1, premium: 1 },
    colorMode: "light",
    density: "standard",
    pairingId: "contemporary-skincare",
    recommendedGlass: ["clear", "opaque"],
    align: "left",
    rows: [
      brandCaps({ color: "accent", letterSpacingEm: 0.12 }),
      productHero(0.155),
      subtitleRow(),
      { slot: "strength", zone: "hero", font: "body", weight: 600, sizeFactor: 0.058, minPt: 4.5, maxLines: 1, color: "accent", chip: "outline", spacingBefore: 1.3 },
      volumeRow(),
      ...detailBlock(),
    ],
    codeCorner: "bottom-right",
    decor: [
      { kind: "band", edge: "top", heightFactor: 0.05, fill: { role: "accent" }, minLabelHeightMm: 13 },
    ],
    materials: ["glossy", "plain", "matte", "clear"],
  }),
  defineTemplate({
    id: "deep-emerald",
    name: "Deep Emerald",
    family: "deep-emerald",
    familyName: "Deep Emerald",
    category: ["glossy", "luxury", "botanical"],
    mood: ["deep", "serif", "underlined"],
    vibe: { luxury: 2, botanical: 2, premium: 1 },
    colorMode: "dark",
    density: "standard",
    pairingId: "botanical-premium",
    recommendedGlass: ["amber", "cobalt"],
    align: "center",
    rows: [
      brandCaps({ weight: 500, letterSpacingEm: 0.26 }),
      productHero(0.165),
      subtitleRow({ maxLines: 2 }),
      strengthRow({ weight: 500 }),
      volumeRow(),
      ...detailBlock(),
    ],
    codeCorner: "bottom-left",
    decor: [
      { kind: "underline-hero", widthFactor: 0.14, strokePt: 0.8, fill: { role: "accent" } },
    ],
    materials: ["glossy", "plain", "matte", "kraft"],
  }),
  defineTemplate({
    id: "rich-burgundy",
    name: "Rich Burgundy",
    family: "rich-burgundy",
    familyName: "Rich Burgundy",
    category: ["glossy", "luxury"],
    mood: ["wine", "kicker", "warm"],
    vibe: { luxury: 2, premium: 2, botanical: 1 },
    colorMode: "dark",
    density: "standard",
    pairingId: "warm-editorial",
    recommendedGlass: ["amber"],
    align: "left",
    rows: [
      brandCaps({ letterSpacingEm: 0.2 }),
      kickerSubtitle({ spacingBefore: 0.6 }),
      productHero(0.16, { spacingBefore: 0.5 }),
      strengthRow(),
      volumeRow(),
      ...detailBlock(),
    ],
    codeCorner: "bottom-right",
    decor: [],
    materials: ["glossy", "plain", "matte"],
  }),
  defineTemplate({
    id: "midnight-blue-gloss",
    name: "Midnight Blue",
    family: "midnight-blue",
    familyName: "Midnight Blue",
    category: ["glossy", "clinical"],
    mood: ["navy", "marked", "tracked"],
    vibe: { clinical: 2, premium: 2, minimal: 1 },
    colorMode: "dark",
    density: "standard",
    pairingId: "pharmaceutical",
    recommendedGlass: ["cobalt", "clear"],
    align: "center",
    rows: [
      brandCaps({ letterSpacingEm: 0.24 }),
      productHero(0.14, { casing: "uppercase", letterSpacingEm: 0.04 }),
      strengthRow({ sizeFactor: 0.062 }),
      subtitleRow({ sizeFactor: 0.046 }),
      volumeRow(),
      ...detailBlock(),
    ],
    codeCorner: "bottom-right",
    decor: [
      { kind: "corners", lengthMm: 2.8, strokePt: 0.8, color: "muted", insetMm: 1.3, minLabelHeightMm: 14 },
    ],
    materials: ["glossy", "plain", "metallic"],
  }),
  defineTemplate({
    id: "high-contrast-type",
    name: "High-Contrast Type",
    family: "high-contrast-type",
    familyName: "High-Contrast Type",
    category: ["glossy", "plain", "neon"],
    mood: ["poster", "huge", "centered-codes"],
    vibe: { bold: 3, minimal: 1 },
    colorMode: "dark",
    density: "minimal",
    pairingId: "poster-block",
    recommendedGlass: ["clear", "opaque"],
    align: "left",
    codePlacement: "footer-center",
    rows: [
      brandCaps({ weight: 400, letterSpacingEm: 0.18 }),
      productHero(0.24, { casing: "uppercase" }),
      strengthRow({ font: "display", sizeFactor: 0.095, minPt: 5.5, casing: "uppercase", color: "accent", weight: undefined }),
      subtitleRow(),
      volumeRow(),
      ...detailBlock(),
    ],
    codeCorner: "bottom-right",
    decor: [],
    materials: ["glossy", "plain", "neon"],
  }),
  defineTemplate({
    id: "reflective-minimal",
    name: "Reflective Minimal",
    family: "reflective-minimal",
    familyName: "Reflective Minimal",
    category: ["glossy", "plain"],
    mood: ["reflective", "brand-below", "sparse"],
    vibe: { minimal: 3, premium: 1 },
    colorMode: "light",
    density: "minimal",
    pairingId: "grotesk-minimal",
    recommendedGlass: ["clear", "frosted"],
    align: "center",
    rows: [
      productHero(0.17),
      { slot: "strength", zone: "hero", font: "body", weight: 500, sizeFactor: 0.056, minPt: 4.5, maxLines: 1, color: "accent", chip: "outline", spacingBefore: 1.3 },
      subtitleRow({ spacingBefore: 0.7 }),
      brandBottom(),
      volumeRow("footer", { spacingBefore: 0.4 }),
      ...detailBlock(),
    ],
    codeCorner: "bottom-right",
    decor: [],
    materials: ["glossy", "plain", "matte", "clear"],
  }),
  defineTemplate({
    id: "gloss-color-block",
    name: "Gloss Color Block",
    family: "gloss-color-block",
    familyName: "Gloss Color Block",
    category: ["glossy", "plain"],
    mood: ["blocked", "confident", "modern"],
    vibe: { bold: 2, minimal: 1, premium: 1 },
    colorMode: "light",
    density: "standard",
    pairingId: "bold-modern",
    recommendedGlass: ["clear", "opaque"],
    align: "left",
    rows: [
      brandCaps({ letterSpacingEm: 0.14 }),
      productHero(0.17),
      strengthRow({ sizeFactor: 0.068 }),
      subtitleRow(),
      volumeRow(),
      ...detailBlock(),
    ],
    codeCorner: "bottom-left",
    decor: [
      { kind: "band", edge: "top", heightFactor: 0.16, fill: { role: "accent" }, inset: true, minLabelHeightMm: 17 },
    ],
    materials: ["glossy", "plain", "neon", "matte"],
  }),
  defineTemplate({
    id: "gloss-monoline",
    name: "Gloss Monoline",
    family: "gloss-monoline",
    familyName: "Gloss Monoline",
    category: ["glossy", "plain"],
    mood: ["linear", "dark", "quiet"],
    vibe: { minimal: 2, premium: 2 },
    colorMode: "dark",
    density: "standard",
    pairingId: "minimal-premium",
    recommendedGlass: ["opaque", "clear"],
    align: "left",
    rows: [
      brandCaps({ weight: 400, letterSpacingEm: 0.2 }),
      productHero(0.15),
      strengthRow({ weight: 600, color: "text" }),
      subtitleRow(),
      volumeRow(),
      ...detailBlock(),
    ],
    codeCorner: "bottom-right",
    decor: [
      { kind: "divider", after: "brand", widthFactor: 0.94, strokePt: 0.4, fill: { role: "border" } },
      { kind: "divider", after: "strength", widthFactor: 0.12, strokePt: 0.9, fill: { role: "accent" } },
    ],
    materials: ["glossy", "plain", "matte", "metallic"],
  }),
  // --- Plain & minimal -------------------------------------------------------------
  defineTemplate({
    id: "essential-black",
    name: "Essential Black",
    family: "essential-black",
    familyName: "Essential Black",
    category: ["plain", "glossy"],
    mood: ["black", "typographic", "direct"],
    vibe: { minimal: 2, bold: 2 },
    colorMode: "dark",
    density: "minimal",
    pairingId: "impact-display",
    recommendedGlass: ["clear", "opaque"],
    align: "center",
    rows: [
      brandCaps({ weight: 500, letterSpacingEm: 0.24 }),
      productHero(0.19, { casing: "uppercase" }),
      strengthRow({ sizeFactor: 0.07 }),
      subtitleRow(),
      volumeRow(),
      ...detailBlock(),
    ],
    codeCorner: "bottom-right",
    decor: [],
  }),
  defineTemplate({
    id: "simple-column",
    name: "Simple Column",
    family: "simple-column",
    familyName: "Simple Column",
    category: ["plain", "clinical"],
    mood: ["columnar", "tidy", "left"],
    vibe: { minimal: 2, clinical: 2 },
    colorMode: "light",
    density: "standard",
    pairingId: "neutral-inter",
    recommendedGlass: ["clear"],
    align: "left",
    rows: [
      brandCaps({ letterSpacingEm: 0.08 }),
      productHero(0.14),
      subtitleRow(),
      strengthRow({ color: "text", weight: 600, sizeFactor: 0.06 }),
      volumeRow(),
      ...detailBlock(),
    ],
    codeCorner: "bottom-right",
    decor: [{ kind: "side-rail", edge: "left", insetMm: 1.2, strokePt: 1, color: "muted" }],
  }),
  defineTemplate({
    id: "soft-neutral",
    name: "Soft Neutral",
    family: "soft-neutral",
    familyName: "Soft Neutral",
    category: ["plain", "beauty", "botanical"],
    mood: ["gentle", "dotted", "warm"],
    vibe: { minimal: 2, botanical: 1, playful: 1 },
    colorMode: "light",
    density: "standard",
    pairingId: "friendly-organic",
    recommendedGlass: ["clear", "amber"],
    align: "center",
    rows: [
      brandCaps({ weight: 600, letterSpacingEm: 0.18 }),
      productHero(0.15, { spacingBefore: 1.2 }),
      subtitleRow({ maxLines: 2 }),
      strengthRow({ sizeFactor: 0.058 }),
      volumeRow(),
      ...detailBlock(),
    ],
    codeCorner: "bottom-left",
    decor: [
      { kind: "divider", after: "brand", widthFactor: 0.05, strokePt: 1.8, fill: { role: "accent" } },
    ],
  }),
  defineTemplate({
    id: "affordable-premium",
    name: "Affordable Premium",
    family: "affordable-premium",
    familyName: "Affordable Premium",
    category: ["plain"],
    mood: ["accessible", "polished", "divided"],
    vibe: { minimal: 2, premium: 1, clinical: 1 },
    colorMode: "light",
    density: "standard",
    pairingId: "minimal-premium",
    recommendedGlass: ["clear", "amber"],
    align: "left",
    rows: [
      brandCaps({ letterSpacingEm: 0.1 }),
      productHero(0.155),
      strengthRow({ sizeFactor: 0.062 }),
      subtitleRow(),
      volumeRow(),
      ...detailBlock(),
    ],
    codeCorner: "bottom-right",
    decor: [
      { kind: "divider", after: "brand", widthFactor: 0.94, strokePt: 0.5, fill: { role: "border" } },
    ],
  }),
  defineTemplate({
    id: "balanced-clinical",
    name: "Balanced Clinical",
    family: "balanced-clinical",
    familyName: "Balanced Clinical",
    category: ["plain", "clinical"],
    mood: ["balanced", "recorded", "bordered"],
    vibe: { clinical: 2, minimal: 2 },
    colorMode: "light",
    density: "detailed",
    pairingId: "modern-clinical",
    recommendedGlass: ["clear", "cobalt"],
    align: "center",
    rows: [
      brandCaps({ letterSpacingEm: 0.16 }),
      { slot: "lot", zone: "header", font: "technical", sizeFactor: 0.042, minPt: 4, maxLines: 1, color: "muted", spacingBefore: 0.4 },
      productHero(0.135),
      strengthRow({ sizeFactor: 0.06 }),
      subtitleRow({ sizeFactor: 0.046 }),
      { slot: "volume", zone: "footer", font: "technical", sizeFactor: 0.044, minPt: 4, maxLines: 1, color: "muted" },
      { slot: "description", zone: "footer", font: "body", sizeFactor: 0.044, minPt: 4, maxLines: 2, color: "muted", spacingBefore: 0.35 },
      { slot: "ingredients", zone: "footer", font: "body", sizeFactor: 0.042, minPt: 4, maxLines: 3, color: "muted", spacingBefore: 0.35 },
      { slot: "directions", zone: "footer", font: "body", sizeFactor: 0.042, minPt: 4, maxLines: 2, color: "muted", spacingBefore: 0.3 },
      { slot: "storage", zone: "footer", font: "body", sizeFactor: 0.042, minPt: 4, maxLines: 1, color: "muted", spacingBefore: 0.3 },
      { slot: "warning", zone: "footer", font: "body", emphasis: true, sizeFactor: 0.042, minPt: 4, maxLines: 2, color: "text", spacingBefore: 0.3 },
      { slot: "expiry", zone: "footer", font: "technical", sizeFactor: 0.042, minPt: 4, maxLines: 1, color: "muted", spacingBefore: 0.3 },
      { slot: "verification", zone: "footer", font: "technical", sizeFactor: 0.042, minPt: 4, maxLines: 1, color: "muted", spacingBefore: 0.25 },
      { slot: "website", zone: "footer", font: "body", sizeFactor: 0.044, minPt: 4, maxLines: 1, color: "accent", spacingBefore: 0.4 },
    ],
    codeCorner: "bottom-right",
    decor: [{ kind: "border", insetMm: 1.2, strokePt: 0.6, color: "border" }],
  }),
  defineTemplate({
    id: "premium-monochrome",
    name: "Premium Monochrome",
    family: "premium-monochrome",
    familyName: "Premium Monochrome",
    category: ["glossy", "plain", "luxury"],
    mood: ["monochrome", "brand-below", "railed"],
    vibe: { premium: 2, minimal: 2, bold: 1 },
    colorMode: "dark",
    density: "standard",
    pairingId: "grotesk-minimal",
    recommendedGlass: ["opaque", "clear"],
    align: "center",
    rows: [
      productHero(0.165),
      strengthRow({ color: "text", sizeFactor: 0.064 }),
      subtitleRow(),
      brandBottom({ letterSpacingEm: 0.24 }),
      volumeRow("footer", { spacingBefore: 0.35 }),
      ...detailBlock(),
    ],
    codeCorner: "bottom-left",
    decor: [
      { kind: "side-rail", edge: "right", insetMm: 1.3, strokePt: 1, color: "text" },
    ],
    materials: ["glossy", "plain", "matte", "metallic"],
  }),
  defineTemplate({
    id: "type-ladder",
    name: "Type Ladder",
    family: "pure-typography",
    familyName: "Pure Typography",
    category: ["plain", "neon"],
    mood: ["typographic", "centered", "ladder"],
    vibe: { bold: 2, minimal: 2 },
    colorMode: "light",
    density: "minimal",
    pairingId: "poster-block",
    recommendedGlass: ["clear"],
    align: "center",
    codePlacement: "footer-center",
    rows: [
      brandCaps({ weight: 400, letterSpacingEm: 0.22 }),
      productHero(0.21, { casing: "uppercase", minPt: 8 }),
      { slot: "strength", zone: "hero", font: "display", sizeFactor: 0.085, minPt: 5, maxLines: 1, color: "accent", casing: "uppercase", spacingBefore: 0.6 },
      subtitleRow(),
      volumeRow(),
      ...detailBlock(),
    ],
    codeCorner: "bottom-right",
    decor: [],
  }),
] as const;
