import {
  brandBottom,
  brandCaps,
  detailBlock,
  kickerSubtitle,
  productHero,
  strengthRow,
  subtitleRow,
  techHeader,
  tightDetailBlock,
  volumeRow,
} from "./parts";
import type { EasyTemplateDef } from "./types";
import { defineTemplate } from "./types";

/** Library expansion — clinical, laboratory, and transparent families. */

export const LAB_EXPANSION: readonly EasyTemplateDef[] = [
  // --- Clinical ------------------------------------------------------------------
  defineTemplate({
    id: "modern-pharmacy",
    name: "Modern Pharmacy",
    family: "modern-pharmacy",
    familyName: "Modern Pharmacy",
    category: ["clinical"],
    mood: ["pharmacy", "banded", "recorded"],
    vibe: { clinical: 3, minimal: 1 },
    colorMode: "light",
    density: "standard",
    pairingId: "modern-clinical",
    recommendedGlass: ["clear", "amber"],
    align: "left",
    rows: [
      brandCaps({ color: "text", letterSpacingEm: 0.1 }),
      ...techHeader(),
      productHero(0.15),
      strengthRow({ sizeFactor: 0.068 }),
      subtitleRow(),
      volumeRow(),
      ...detailBlock().filter((r) => r.slot !== "lot" && r.slot !== "expiry"),
    ],
    codeCorner: "bottom-right",
    decor: [
      { kind: "band", edge: "top", heightFactor: 0.06, fill: { role: "accent" }, inset: true, minLabelHeightMm: 14 },
    ],
  }),
  defineTemplate({
    id: "clean-specification",
    name: "Clean Specification",
    family: "clean-specification",
    familyName: "Clean Specification",
    category: ["clinical", "laboratory"],
    mood: ["spec-sheet", "two-column", "sterile"],
    vibe: { clinical: 3, futuristic: 1, minimal: 1 },
    colorMode: "light",
    density: "detailed",
    pairingId: "pharmaceutical",
    recommendedGlass: ["clear"],
    align: "left",
    minHeightMm: 22,
    minWidthMm: 45,
    split: { ratio: 0.5, divider: true },
    rows: [
      brandCaps({ letterSpacingEm: 0.18 }),
      productHero(0.14),
      strengthRow({ sizeFactor: 0.066 }),
      subtitleRow({ maxLines: 2 }),
      volumeRow("header", { column: "right", font: "technical" }),
      { slot: "lot", zone: "header", font: "technical", sizeFactor: 0.044, minPt: 4, maxLines: 1, color: "muted", column: "right", spacingBefore: 0.3 },
      { slot: "expiry", zone: "header", font: "technical", sizeFactor: 0.044, minPt: 4, maxLines: 1, color: "muted", column: "right", spacingBefore: 0.25 },
      { slot: "verification", zone: "header", font: "technical", sizeFactor: 0.042, minPt: 4, maxLines: 1, color: "muted", column: "right", spacingBefore: 0.25 },
      { slot: "ingredients", zone: "hero", font: "body", sizeFactor: 0.042, minPt: 4, maxLines: 4, color: "muted", column: "right" },
      { slot: "directions", zone: "footer", font: "body", sizeFactor: 0.042, minPt: 4, maxLines: 2, color: "muted", column: "right", spacingBefore: 0.35 },
      { slot: "storage", zone: "footer", font: "body", sizeFactor: 0.042, minPt: 4, maxLines: 1, color: "muted", column: "right", spacingBefore: 0.3 },
      { slot: "description", zone: "footer", font: "body", sizeFactor: 0.044, minPt: 4, maxLines: 2, color: "muted" },
      { slot: "warning", zone: "footer", font: "body", emphasis: true, sizeFactor: 0.044, minPt: 4, maxLines: 2, color: "text", spacingBefore: 0.4 },
      { slot: "website", zone: "footer", font: "body", sizeFactor: 0.044, minPt: 4, maxLines: 1, color: "accent", spacingBefore: 0.4 },
    ],
    codeCorner: "bottom-right",
    decor: [],
  }),
  defineTemplate({
    id: "clinical-column",
    name: "Clinical Column",
    family: "clinical-column",
    familyName: "Clinical Column",
    category: ["clinical"],
    mood: ["vertical", "efficient", "centered-codes"],
    vibe: { clinical: 3 },
    colorMode: "light",
    density: "standard",
    pairingId: "neutral-inter",
    recommendedGlass: ["clear", "cobalt"],
    align: "left",
    minHeightMm: 16,
    codePlacement: "footer-center",
    verticalRow: { slot: "brand", edge: "left", font: "body", weight: 600, sizeFactor: 0.048, minPt: 4.5, color: "accent", letterSpacingEm: 0.22, casing: "uppercase" },
    rows: [
      productHero(0.15),
      strengthRow({ sizeFactor: 0.066 }),
      subtitleRow(),
      volumeRow(),
      ...detailBlock(),
    ],
    codeCorner: "bottom-right",
    decor: [],
  }),
  defineTemplate({
    id: "precision-plus",
    name: "Precision Plus",
    family: "precision-clinical",
    familyName: "Precision Clinical",
    category: ["clinical", "plain"],
    mood: ["marked", "badged", "precise"],
    vibe: { clinical: 3, minimal: 1, bold: 1 },
    colorMode: "light",
    density: "standard",
    pairingId: "modern-clinical",
    recommendedGlass: ["clear"],
    align: "left",
    rows: [
      brandCaps({ letterSpacingEm: 0.12 }),
      productHero(0.15),
      subtitleRow(),
      { slot: "strength", zone: "hero", font: "body", weight: 600, sizeFactor: 0.062, minPt: 4.5, maxLines: 1, color: "onAccent", chip: "fill", spacingBefore: 1.2 },
      volumeRow(),
      ...detailBlock(),
    ],
    codeCorner: "bottom-right",
    decor: [
      { kind: "corners", lengthMm: 2.6, strokePt: 0.8, color: "accent", insetMm: 1.2, minLabelHeightMm: 14 },
    ],
  }),
  defineTemplate({
    id: "essential-laboratory",
    name: "Essential Laboratory",
    family: "essential-laboratory",
    familyName: "Essential Laboratory",
    category: ["clinical", "laboratory"],
    mood: ["essential", "mono", "centered"],
    vibe: { clinical: 2, minimal: 2 },
    colorMode: "light",
    density: "standard",
    pairingId: "retro-terminal",
    recommendedGlass: ["clear"],
    align: "center",
    rows: [
      brandCaps({ font: "display", weight: 700, letterSpacingEm: 0.08 }),
      productHero(0.125, { casing: "uppercase" }),
      strengthRow({ weight: 700, sizeFactor: 0.062 }),
      subtitleRow({ sizeFactor: 0.046 }),
      volumeRow("footer", { font: "technical" }),
      ...tightDetailBlock(),
    ],
    codeCorner: "bottom-right",
    decor: [
      { kind: "divider", after: "brand", widthFactor: 0.3, strokePt: 0.6, fill: { role: "accent" } },
    ],
  }),
  // --- Laboratory -------------------------------------------------------------------
  defineTemplate({
    id: "research-minimal",
    name: "Research Minimal",
    family: "research-minimal",
    familyName: "Research Minimal",
    category: ["laboratory", "plain"],
    mood: ["undecorated", "mono", "quiet"],
    vibe: { clinical: 1, minimal: 3, futuristic: 1 },
    colorMode: "light",
    density: "standard",
    pairingId: "retro-terminal",
    recommendedGlass: ["clear", "frosted"],
    align: "left",
    rows: [
      brandCaps({ weight: 400, letterSpacingEm: 0.06, casing: undefined }),
      productHero(0.13),
      strengthRow({ weight: 700, sizeFactor: 0.06, spacingBefore: 0.8 }),
      subtitleRow({ sizeFactor: 0.046 }),
      volumeRow("footer", { font: "technical" }),
      ...tightDetailBlock(),
    ],
    codeCorner: "bottom-right",
    decor: [],
  }),
  defineTemplate({
    id: "instrument-panel",
    name: "Instrument Panel",
    family: "instrument-panel",
    familyName: "Instrument Panel",
    category: ["laboratory", "clinical"],
    mood: ["instrument", "dark", "railed"],
    vibe: { futuristic: 2, clinical: 2 },
    colorMode: "dark",
    density: "standard",
    pairingId: "tech-lab",
    recommendedGlass: ["cobalt", "opaque"],
    align: "left",
    rows: [
      brandCaps({ letterSpacingEm: 0.2 }),
      ...techHeader(),
      productHero(0.14, { casing: "uppercase", letterSpacingEm: 0.03 }),
      { slot: "strength", zone: "hero", font: "body", weight: 600, sizeFactor: 0.06, minPt: 4.5, maxLines: 1, color: "accent", chip: "outline", spacingBefore: 1.2 },
      subtitleRow({ sizeFactor: 0.046 }),
      volumeRow("footer", { font: "technical" }),
      ...tightDetailBlock().filter((r) => r.slot !== "lot" && r.slot !== "expiry"),
    ],
    codeCorner: "bottom-right",
    decor: [
      { kind: "side-rail", edge: "left", insetMm: 1.2, strokePt: 1.2, color: "accent" },
      { kind: "side-rail", edge: "right", insetMm: 1.2, strokePt: 0.5, color: "border", minLabelHeightMm: 15 },
    ],
  }),
  defineTemplate({
    id: "analytical-series",
    name: "Analytical Series",
    family: "analytical-series",
    familyName: "Analytical Series",
    category: ["laboratory"],
    mood: ["analytical", "two-column", "engineered"],
    vibe: { futuristic: 2, clinical: 2, minimal: 1 },
    colorMode: "light",
    density: "detailed",
    pairingId: "engineered",
    recommendedGlass: ["clear", "cobalt"],
    align: "left",
    minHeightMm: 22,
    minWidthMm: 45,
    split: { ratio: 0.56, divider: true },
    rows: [
      brandCaps({ weight: 700, letterSpacingEm: 0.22 }),
      ...techHeader(),
      productHero(0.14),
      strengthRow({ sizeFactor: 0.064 }),
      subtitleRow({ maxLines: 2, sizeFactor: 0.046 }),
      { slot: "description", zone: "header", font: "body", sizeFactor: 0.044, minPt: 4, maxLines: 3, color: "muted", column: "right" },
      { slot: "ingredients", zone: "hero", font: "body", sizeFactor: 0.042, minPt: 4, maxLines: 3, color: "muted", column: "right" },
      { slot: "directions", zone: "footer", font: "body", sizeFactor: 0.042, minPt: 4, maxLines: 2, color: "muted", column: "right", spacingBefore: 0.35 },
      { slot: "storage", zone: "footer", font: "body", sizeFactor: 0.042, minPt: 4, maxLines: 1, color: "muted", column: "right", spacingBefore: 0.3 },
      { slot: "warning", zone: "footer", font: "body", emphasis: true, sizeFactor: 0.042, minPt: 4, maxLines: 2, color: "text", column: "right", spacingBefore: 0.3 },
      { slot: "volume", zone: "footer", font: "technical", sizeFactor: 0.044, minPt: 4, maxLines: 1, color: "muted" },
      { slot: "verification", zone: "footer", font: "technical", sizeFactor: 0.042, minPt: 4, maxLines: 1, color: "muted", spacingBefore: 0.3 },
      { slot: "website", zone: "footer", font: "body", sizeFactor: 0.044, minPt: 4, maxLines: 1, color: "accent", spacingBefore: 0.4 },
    ],
    codeCorner: "bottom-left",
    decor: [],
  }),
  defineTemplate({
    id: "technical-column",
    name: "Technical Column",
    family: "technical-column",
    familyName: "Technical Column",
    category: ["laboratory", "clinical"],
    mood: ["technical", "vertical", "tight"],
    vibe: { futuristic: 2, clinical: 2, minimal: 1 },
    colorMode: "light",
    density: "standard",
    pairingId: "tech-lab",
    recommendedGlass: ["clear"],
    align: "left",
    minHeightMm: 16,
    verticalRow: { slot: "brand", edge: "right", font: "body", weight: 700, sizeFactor: 0.046, minPt: 4.5, color: "accent", letterSpacingEm: 0.24, casing: "uppercase" },
    rows: [
      productHero(0.14, { casing: "uppercase" }),
      strengthRow({ weight: 700, sizeFactor: 0.064 }),
      subtitleRow({ sizeFactor: 0.046 }),
      volumeRow("footer", { font: "technical" }),
      ...tightDetailBlock(),
    ],
    codeCorner: "bottom-left",
    decor: [
      { kind: "divider", after: "product-name", widthFactor: 0.4, strokePt: 0.6, fill: { role: "accent" } },
    ],
  }),
  defineTemplate({
    id: "batch-control",
    name: "Batch Control",
    family: "batch-control",
    familyName: "Batch Control",
    category: ["laboratory", "clinical"],
    mood: ["batch", "stamped", "centered-codes"],
    vibe: { clinical: 3, futuristic: 1 },
    colorMode: "light",
    density: "standard",
    pairingId: "pharmaceutical",
    recommendedGlass: ["clear", "amber"],
    align: "left",
    codePlacement: "footer-center",
    rows: [
      brandCaps({ letterSpacingEm: 0.14 }),
      { slot: "lot", zone: "header", font: "technical", weight: 600, sizeFactor: 0.05, minPt: 4.5, maxLines: 1, color: "text", spacingBefore: 0.5 },
      { slot: "expiry", zone: "header", font: "technical", sizeFactor: 0.044, minPt: 4, maxLines: 1, color: "muted", spacingBefore: 0.25 },
      productHero(0.14),
      strengthRow({ sizeFactor: 0.064 }),
      volumeRow(),
      { slot: "warning", zone: "footer", font: "body", emphasis: true, sizeFactor: 0.044, minPt: 4, maxLines: 2, color: "text", spacingBefore: 0.4 },
      { slot: "verification", zone: "footer", font: "technical", sizeFactor: 0.044, minPt: 4, maxLines: 1, color: "muted", spacingBefore: 0.3 },
      { slot: "website", zone: "footer", font: "body", sizeFactor: 0.044, minPt: 4, maxLines: 1, color: "muted", spacingBefore: 0.4 },
    ],
    codeCorner: "bottom-left",
    decor: [
      { kind: "border", insetMm: 1, strokePt: 0.8, color: "text" },
    ],
  }),
  defineTemplate({
    id: "cryo-lab",
    name: "Cryo Lab",
    family: "cryo-lab",
    familyName: "Cryo Lab",
    category: ["laboratory", "neon"],
    mood: ["cold", "dark", "kicker"],
    vibe: { futuristic: 3, clinical: 1 },
    colorMode: "dark",
    density: "standard",
    pairingId: "engineered",
    recommendedGlass: ["cobalt", "clear"],
    align: "left",
    rows: [
      brandCaps({ letterSpacingEm: 0.24 }),
      kickerSubtitle({ spacingBefore: 0.6, color: "muted" }),
      productHero(0.145, { casing: "uppercase", letterSpacingEm: 0.04, spacingBefore: 0.5 }),
      { slot: "strength", zone: "hero", font: "body", weight: 700, sizeFactor: 0.06, minPt: 4.5, maxLines: 1, color: "accent", chip: "outline", spacingBefore: 1.3 },
      volumeRow("footer", { font: "technical" }),
      ...tightDetailBlock(),
    ],
    codeCorner: "bottom-right",
    decor: [],
    materials: ["neon", "plain", "glossy", "holographic", "metallic"],
  }),
  // --- Transparent ------------------------------------------------------------------
  defineTemplate({
    id: "white-ink-minimal",
    name: "White Ink Minimal",
    family: "white-ink-minimal",
    familyName: "White Ink Minimal",
    category: ["transparent", "beauty"],
    mood: ["white-ink", "tracked", "floating"],
    vibe: { minimal: 3, premium: 1 },
    colorMode: "dark",
    density: "minimal",
    pairingId: "airy-modern",
    recommendedGlass: ["amber", "cobalt"],
    align: "center",
    rows: [
      brandCaps({ color: "text", letterSpacingEm: 0.34 }),
      productHero(0.13, { casing: "uppercase", letterSpacingEm: 0.1, spacingBefore: 1.4 }),
      strengthRow({ color: "text", weight: 600, sizeFactor: 0.055, letterSpacingEm: 0.14, spacingBefore: 1.3 }),
      subtitleRow({ sizeFactor: 0.046, letterSpacingEm: 0.08 }),
      volumeRow(),
      ...detailBlock(),
    ],
    codeCorner: "bottom-right",
    decor: [],
    materials: ["clear", "metallic", "holographic"],
  }),
  defineTemplate({
    id: "transparent-border",
    name: "Transparent Border",
    family: "transparent-border",
    familyName: "Transparent Border",
    category: ["transparent", "plain"],
    mood: ["outlined", "window", "clean"],
    vibe: { minimal: 2, clinical: 1 },
    colorMode: "light",
    density: "standard",
    pairingId: "neutral-inter",
    recommendedGlass: ["clear", "amber"],
    align: "center",
    rows: [
      brandCaps({ letterSpacingEm: 0.2 }),
      productHero(0.145),
      subtitleRow(),
      strengthRow({ color: "text", sizeFactor: 0.06 }),
      volumeRow(),
      ...detailBlock(),
    ],
    codeCorner: "bottom-right",
    decor: [{ kind: "border", insetMm: 1.3, strokePt: 1, color: "text" }],
    materials: ["clear", "plain", "glossy", "matte"],
  }),
  defineTemplate({
    id: "clear-botanical",
    name: "Clear Botanical",
    family: "clear-botanical",
    familyName: "Clear Botanical",
    category: ["transparent", "botanical"],
    mood: ["botanical", "see-through", "serif"],
    vibe: { botanical: 3, minimal: 1 },
    colorMode: "light",
    density: "standard",
    pairingId: "botanical-premium",
    recommendedGlass: ["clear", "amber"],
    align: "center",
    rows: [
      brandCaps({ weight: 500, letterSpacingEm: 0.24 }),
      productHero(0.16),
      subtitleRow({ maxLines: 2 }),
      strengthRow({ weight: 500, sizeFactor: 0.058 }),
      volumeRow(),
      ...detailBlock(),
    ],
    codeCorner: "bottom-left",
    decor: [
      { kind: "divider", after: "product-name", widthFactor: 0.1, strokePt: 0.6, fill: { role: "accent" } },
    ],
    materials: ["clear", "plain", "kraft", "matte"],
  }),
  defineTemplate({
    id: "frosted-panel",
    name: "Frosted Panel",
    family: "frosted-panel",
    familyName: "Frosted Panel",
    category: ["transparent", "beauty"],
    mood: ["frosted", "soft", "blocked"],
    vibe: { minimal: 2, luxury: 1 },
    colorMode: "light",
    density: "standard",
    pairingId: "contemporary-skincare",
    recommendedGlass: ["frosted", "clear"],
    align: "left",
    rows: [
      brandCaps({ letterSpacingEm: 0.18 }),
      kickerSubtitle({ color: "muted", spacingBefore: 0.6 }),
      productHero(0.15, { spacingBefore: 0.5 }),
      strengthRow({ sizeFactor: 0.058 }),
      volumeRow(),
      ...detailBlock(),
    ],
    codeCorner: "bottom-right",
    decor: [
      { kind: "band", edge: "top", heightFactor: 0.12, fill: { gradient: true }, inset: true, minLabelHeightMm: 16 },
    ],
    materials: ["clear", "plain", "glossy", "matte"],
  }),
  defineTemplate({
    id: "window-label",
    name: "Window Label",
    family: "window-label",
    familyName: "Window Label",
    category: ["transparent", "plain"],
    mood: ["vertical", "open", "no-label"],
    vibe: { minimal: 3 },
    colorMode: "light",
    density: "minimal",
    pairingId: "minimal-premium",
    recommendedGlass: ["clear", "amber"],
    align: "left",
    minHeightMm: 16,
    verticalRow: { slot: "brand", edge: "left", font: "body", weight: 600, sizeFactor: 0.046, minPt: 4.5, color: "muted", letterSpacingEm: 0.28, casing: "uppercase" },
    rows: [
      productHero(0.15),
      strengthRow({ color: "text", weight: 600, sizeFactor: 0.06 }),
      subtitleRow(),
      volumeRow(),
      ...detailBlock(),
    ],
    codeCorner: "bottom-right",
    decor: [],
    materials: ["clear", "plain", "glossy"],
  }),
  defineTemplate({
    id: "clear-luxury",
    name: "Clear Luxury",
    family: "clear-luxury",
    familyName: "Clear Luxury",
    category: ["transparent", "luxury"],
    mood: ["invisible", "serif", "cornered"],
    vibe: { luxury: 2, minimal: 2, premium: 1 },
    colorMode: "light",
    density: "minimal",
    pairingId: "prata-elegant",
    recommendedGlass: ["clear", "frosted"],
    align: "center",
    rows: [
      brandCaps({ weight: 500, letterSpacingEm: 0.3 }),
      productHero(0.155, { spacingBefore: 1.2 }),
      strengthRow({ weight: 500, sizeFactor: 0.055, letterSpacingEm: 0.12 }),
      subtitleRow({ sizeFactor: 0.046 }),
      volumeRow(),
      ...detailBlock(),
    ],
    codeCorner: "bottom-right",
    decor: [
      { kind: "corners", lengthMm: 2.6, strokePt: 0.6, color: "muted", insetMm: 1.3, minLabelHeightMm: 15 },
    ],
    materials: ["clear", "plain", "glossy", "matte"],
  }),
  defineTemplate({
    id: "minimal-overlay",
    name: "Minimal Overlay",
    family: "minimal-overlay",
    familyName: "Minimal Overlay",
    category: ["transparent", "plain"],
    mood: ["overlay", "brand-below", "sparse"],
    vibe: { minimal: 3 },
    colorMode: "light",
    density: "minimal",
    pairingId: "grotesk-minimal",
    recommendedGlass: ["clear"],
    align: "left",
    rows: [
      productHero(0.165),
      strengthRow({ color: "text", weight: 500, sizeFactor: 0.06, spacingBefore: 0.9 }),
      subtitleRow(),
      brandBottom({ align: "left" }),
      volumeRow("footer", { spacingBefore: 0.35 }),
      ...detailBlock(),
    ],
    codeCorner: "bottom-right",
    decor: [],
    materials: ["clear", "plain", "matte"],
  }),
  defineTemplate({
    id: "transparent-technical",
    name: "Transparent Technical",
    family: "transparent-technical",
    familyName: "Transparent Technical",
    category: ["transparent", "laboratory"],
    mood: ["technical", "side-coded", "mono"],
    vibe: { clinical: 2, futuristic: 2 },
    colorMode: "light",
    density: "standard",
    pairingId: "retro-terminal",
    recommendedGlass: ["clear", "cobalt"],
    align: "left",
    codePlacement: "side",
    qrScale: 1.15,
    rows: [
      brandCaps({ weight: 700, letterSpacingEm: 0.1 }),
      ...techHeader(),
      productHero(0.125, { casing: "uppercase" }),
      strengthRow({ weight: 700, sizeFactor: 0.06 }),
      volumeRow("footer", { font: "technical" }),
      ...tightDetailBlock().filter((r) => r.slot !== "lot" && r.slot !== "expiry"),
    ],
    codeCorner: "bottom-right",
    decor: [
      { kind: "side-rail", edge: "left", insetMm: 1.1, strokePt: 1, color: "text" },
    ],
    materials: ["clear", "plain", "glossy"],
  }),
] as const;
