import {
  brandBottom,
  brandCaps,
  detailBlock,
  kickerSubtitle,
  productHero,
  strengthRow,
  subtitleRow,
  techHeader,
  tightDetailBlock,
  volumeRow,
} from "./parts";
import type { EasyTemplateDef } from "./types";
import { defineTemplate } from "./types";

/** Library expansion — holographic, neon, beauty, and botanical families. */

export const EFFECTS_EXPANSION: readonly EasyTemplateDef[] = [
  // --- Holographic -----------------------------------------------------------------
  defineTemplate({
    id: "shattered-foil",
    name: "Shattered Foil",
    family: "shattered-foil",
    familyName: "Shattered Foil",
    category: ["holographic", "neon"],
    mood: ["angular", "edgy", "striped"],
    vibe: { bold: 2, futuristic: 2 },
    colorMode: "dark",
    density: "standard",
    pairingId: "condensed-impact",
    recommendedGlass: ["opaque", "cobalt"],
    align: "left",
    rows: [
      brandCaps({ weight: 400, letterSpacingEm: 0.2 }),
      productHero(0.19, { casing: "uppercase", minPt: 8 }),
      strengthRow({ letterSpacingEm: 0.08 }),
      subtitleRow(),
      volumeRow(),
      ...detailBlock(),
    ],
    codeCorner: "bottom-right",
    decor: [
      { kind: "stripe", edge: "left", widthFactor: 0.12, fill: { effect: true } },
    ],
    materials: ["holographic", "metallic", "neon", "glossy"],
  }),
  defineTemplate({
    id: "holographic-spectrum",
    name: "Holographic Spectrum",
    family: "holographic-spectrum",
    familyName: "Holographic Spectrum",
    category: ["holographic"],
    mood: ["spectral", "banded", "dark"],
    vibe: { futuristic: 2, premium: 1, bold: 1 },
    colorMode: "dark",
    density: "standard",
    pairingId: "futuristic",
    recommendedGlass: ["opaque", "cobalt"],
    align: "center",
    rows: [
      brandCaps({ weight: 700, letterSpacingEm: 0.28 }),
      productHero(0.14, { casing: "uppercase", letterSpacingEm: 0.05 }),
      { slot: "strength", zone: "hero", font: "body", weight: 700, sizeFactor: 0.062, minPt: 4.5, maxLines: 1, color: "onAccent", chip: "fill", spacingBefore: 1.3 },
      subtitleRow({ sizeFactor: 0.046, letterSpacingEm: 0.08 }),
      volumeRow(),
      ...detailBlock(),
    ],
    codeCorner: "bottom-right",
    decor: [
      { kind: "band", edge: "top", heightFactor: 0.08, fill: { effect: true }, minLabelHeightMm: 13 },
      { kind: "band", edge: "bottom", heightFactor: 0.08, fill: { effect: true }, minLabelHeightMm: 13 },
    ],
    materials: ["holographic", "metallic", "glossy"],
  }),
  defineTemplate({
    id: "silver-prism",
    name: "Silver Prism",
    family: "silver-prism",
    familyName: "Silver Prism",
    category: ["holographic", "clinical"],
    mood: ["silver", "cornered", "light"],
    vibe: { clinical: 1, minimal: 2, futuristic: 1, premium: 1 },
    colorMode: "light",
    density: "standard",
    pairingId: "minimal-premium",
    recommendedGlass: ["clear", "frosted"],
    align: "center",
    rows: [
      brandCaps({ letterSpacingEm: 0.26 }),
      productHero(0.15),
      subtitleRow(),
      strengthRow({ sizeFactor: 0.06 }),
      volumeRow(),
      ...detailBlock(),
    ],
    codeCorner: "bottom-right",
    decor: [
      { kind: "corners", lengthMm: 2.8, strokePt: 0.7, color: "accent", insetMm: 1.3, minLabelHeightMm: 14 },
      { kind: "underline-hero", widthFactor: 0.12, strokePt: 0.8, fill: { effect: true } },
    ],
    materials: ["holographic", "metallic", "plain", "glossy"],
  }),
  defineTemplate({
    id: "aurora-film",
    name: "Aurora Film",
    family: "aurora-film",
    familyName: "Aurora Film",
    category: ["holographic", "beauty"],
    mood: ["aurora", "pastel", "kicker"],
    vibe: { luxury: 1, minimal: 2, botanical: 1 },
    colorMode: "light",
    density: "minimal",
    pairingId: "quiet-luxury",
    recommendedGlass: ["frosted", "clear"],
    align: "center",
    rows: [
      brandCaps({ weight: 500, letterSpacingEm: 0.26 }),
      kickerSubtitle({ color: "muted", spacingBefore: 0.5 }),
      productHero(0.165, { spacingBefore: 0.5 }),
      strengthRow({ weight: 500, sizeFactor: 0.056, spacingBefore: 1.3 }),
      volumeRow(),
      ...detailBlock(),
    ],
    codeCorner: "bottom-left",
    decor: [
      { kind: "band", edge: "bottom", heightFactor: 0.07, fill: { effect: true }, minLabelHeightMm: 13 },
    ],
    materials: ["holographic", "clear", "plain", "glossy"],
  }),
  defineTemplate({
    id: "crystal-grid",
    name: "Crystal Grid",
    family: "crystal-grid",
    familyName: "Crystal Grid",
    category: ["holographic", "laboratory"],
    mood: ["crystalline", "railed", "marked"],
    vibe: { futuristic: 2, clinical: 1, premium: 1 },
    colorMode: "light",
    density: "standard",
    pairingId: "tech-lab",
    recommendedGlass: ["clear", "cobalt"],
    align: "center",
    rows: [
      brandCaps({ letterSpacingEm: 0.24 }),
      productHero(0.135, { casing: "uppercase", letterSpacingEm: 0.04 }),
      strengthRow({ weight: 700, sizeFactor: 0.062, letterSpacingEm: 0.1 }),
      subtitleRow({ sizeFactor: 0.046 }),
      volumeRow(),
      ...detailBlock(),
    ],
    codeCorner: "bottom-right",
    decor: [
      { kind: "side-rail", edge: "left", insetMm: 1.3, strokePt: 0.7, color: "accent" },
      { kind: "side-rail", edge: "right", insetMm: 1.3, strokePt: 0.7, color: "accent" },
      { kind: "corners", lengthMm: 2.4, strokePt: 0.7, color: "muted", insetMm: 2.4, minLabelHeightMm: 16 },
    ],
    materials: ["holographic", "metallic", "plain", "glossy"],
  }),
  defineTemplate({
    id: "rainbow-monoline",
    name: "Rainbow Monoline",
    family: "rainbow-monoline",
    familyName: "Rainbow Monoline",
    category: ["holographic", "neon"],
    mood: ["linear", "spectrum", "divided"],
    vibe: { futuristic: 2, minimal: 1, bold: 1 },
    colorMode: "dark",
    density: "standard",
    pairingId: "engineered",
    recommendedGlass: ["opaque", "cobalt"],
    align: "left",
    rows: [
      brandCaps({ weight: 700, letterSpacingEm: 0.22 }),
      productHero(0.145, { casing: "uppercase", letterSpacingEm: 0.05 }),
      strengthRow({ weight: 700, sizeFactor: 0.062 }),
      subtitleRow({ sizeFactor: 0.046 }),
      volumeRow(),
      ...detailBlock(),
    ],
    codeCorner: "bottom-right",
    decor: [
      { kind: "divider", after: "brand", widthFactor: 0.94, strokePt: 0.9, fill: { effect: true } },
      { kind: "divider", after: "strength", widthFactor: 0.2, strokePt: 0.9, fill: { effect: true } },
    ],
    materials: ["holographic", "metallic", "neon", "glossy"],
  }),
  defineTemplate({
    id: "minimal-iridescent",
    name: "Minimal Iridescent",
    family: "minimal-iridescent",
    familyName: "Minimal Iridescent",
    category: ["holographic", "plain", "beauty"],
    mood: ["understated", "airy", "shimmer"],
    vibe: { minimal: 3, luxury: 1 },
    colorMode: "light",
    density: "minimal",
    pairingId: "airy-modern",
    recommendedGlass: ["frosted", "clear"],
    align: "center",
    rows: [
      brandCaps({ letterSpacingEm: 0.34 }),
      productHero(0.125, { casing: "uppercase", letterSpacingEm: 0.1, spacingBefore: 1.4 }),
      subtitleRow({ letterSpacingEm: 0.06, spacingBefore: 1.1 }),
      strengthRow({ weight: 600, color: "muted", sizeFactor: 0.052, letterSpacingEm: 0.14, spacingBefore: 1.4 }),
      volumeRow(),
      ...detailBlock(),
    ],
    codeCorner: "bottom-right",
    decor: [
      { kind: "divider", after: "product-name", widthFactor: 0.09, strokePt: 0.8, fill: { effect: true } },
    ],
    materials: ["holographic", "plain", "clear", "glossy", "matte"],
  }),
  defineTemplate({
    id: "prism-badge",
    name: "Prism Badge",
    family: "prism-badge",
    familyName: "Prism Badge",
    category: ["holographic", "plain"],
    mood: ["badged", "monogram", "left"],
    vibe: { bold: 2, futuristic: 1, minimal: 1 },
    colorMode: "dark",
    density: "standard",
    pairingId: "bold-modern",
    recommendedGlass: ["opaque", "clear"],
    align: "left",
    minHeightMm: 18,
    rows: [
      { slot: "brand", zone: "header", font: "display", sizeFactor: 0.11, minPt: 6.5, maxLines: 1, color: "text", monogram: true, align: "left" },
      productHero(0.15, { spacingBefore: 1.4 }),
      strengthRow({ sizeFactor: 0.064 }),
      subtitleRow(),
      volumeRow(),
      ...detailBlock(),
    ],
    codeCorner: "bottom-right",
    decor: [
      { kind: "medallion", sizeFactor: 0.2, fill: { effect: true }, minLabelHeightMm: 18 },
    ],
    materials: ["holographic", "metallic", "glossy", "plain"],
  }),
  defineTemplate({
    id: "spectral-column",
    name: "Spectral Column",
    family: "spectral-column",
    familyName: "Spectral Column",
    category: ["holographic", "neon"],
    mood: ["columned", "vertical", "spectral"],
    vibe: { futuristic: 3, bold: 1 },
    colorMode: "dark",
    density: "standard",
    pairingId: "futuristic",
    recommendedGlass: ["cobalt", "opaque"],
    align: "left",
    minHeightMm: 16,
    verticalRow: { slot: "brand", edge: "left", font: "body", weight: 700, sizeFactor: 0.046, minPt: 4.5, color: "muted", letterSpacingEm: 0.26, casing: "uppercase" },
    rows: [
      productHero(0.15, { casing: "uppercase", letterSpacingEm: 0.03 }),
      strengthRow({ weight: 700, sizeFactor: 0.066 }),
      subtitleRow({ sizeFactor: 0.046 }),
      volumeRow(),
      ...detailBlock(),
    ],
    codeCorner: "bottom-right",
    decor: [
      { kind: "stripe", edge: "right", widthFactor: 0.05, fill: { effect: true } },
    ],
    materials: ["holographic", "neon", "metallic", "glossy"],
  }),
  // --- Neon --------------------------------------------------------------------------
  defineTemplate({
    id: "neon-magenta",
    name: "Neon Magenta",
    family: "neon-magenta",
    familyName: "Neon Magenta",
    category: ["neon"],
    mood: ["magenta", "huge", "loud"],
    vibe: { bold: 3, playful: 1 },
    colorMode: "dark",
    density: "minimal",
    pairingId: "impact-display",
    recommendedGlass: ["clear", "opaque"],
    align: "center",
    rows: [
      brandCaps({ weight: 500, letterSpacingEm: 0.2 }),
      productHero(0.23, { casing: "uppercase" }),
      { slot: "strength", zone: "hero", font: "display", sizeFactor: 0.09, minPt: 5.5, maxLines: 1, color: "onAccent", chip: "fill", spacingBefore: 1.4 },
      subtitleRow(),
      volumeRow(),
      ...detailBlock(),
    ],
    codeCorner: "bottom-right",
    decor: [],
    materials: ["neon", "plain", "glossy"],
  }),
  defineTemplate({
    id: "ultraviolet",
    name: "Ultraviolet",
    family: "ultraviolet",
    familyName: "Ultraviolet",
    category: ["neon"],
    mood: ["uv", "tracked", "railed"],
    vibe: { futuristic: 2, bold: 2 },
    colorMode: "dark",
    density: "standard",
    pairingId: "futuristic",
    recommendedGlass: ["cobalt", "opaque"],
    align: "center",
    rows: [
      brandCaps({ weight: 700, letterSpacingEm: 0.32 }),
      productHero(0.14, { casing: "uppercase", letterSpacingEm: 0.07 }),
      strengthRow({ weight: 700, sizeFactor: 0.064, letterSpacingEm: 0.16 }),
      subtitleRow({ sizeFactor: 0.046, letterSpacingEm: 0.1 }),
      volumeRow(),
      ...detailBlock(),
    ],
    codeCorner: "bottom-left",
    decor: [
      { kind: "side-rail", edge: "left", insetMm: 1.2, strokePt: 1.1, color: "accent" },
      { kind: "side-rail", edge: "right", insetMm: 1.2, strokePt: 1.1, color: "accent" },
    ],
    materials: ["neon", "plain", "glossy", "holographic"],
  }),
  defineTemplate({
    id: "blacklight",
    name: "Blacklight",
    family: "blacklight",
    familyName: "Blacklight",
    category: ["neon"],
    mood: ["nocturnal", "brand-below", "glow"],
    vibe: { bold: 2, futuristic: 1, playful: 1 },
    colorMode: "dark",
    density: "standard",
    pairingId: "audiowide-energy",
    recommendedGlass: ["opaque", "cobalt"],
    align: "center",
    rows: [
      productHero(0.16),
      strengthRow({ sizeFactor: 0.068 }),
      subtitleRow(),
      brandBottom({ weight: 700, color: "accent" }),
      volumeRow("footer", { spacingBefore: 0.4 }),
      ...detailBlock(),
    ],
    codeCorner: "bottom-right",
    decor: [
      { kind: "divider", after: "product-name", widthFactor: 0.3, strokePt: 1.3, fill: { role: "accent" } },
    ],
    materials: ["neon", "plain", "glossy"],
  }),
  defineTemplate({
    id: "neon-warning",
    name: "Neon Warning",
    family: "neon-warning",
    familyName: "Neon Warning",
    category: ["neon", "laboratory"],
    mood: ["hazard", "condensed", "cornered"],
    vibe: { bold: 3, clinical: 1 },
    colorMode: "dark",
    density: "standard",
    pairingId: "poster-block",
    recommendedGlass: ["clear", "opaque"],
    align: "left",
    rows: [
      brandCaps({ weight: 400, letterSpacingEm: 0.16 }),
      productHero(0.2, { casing: "uppercase", minPt: 8 }),
      { slot: "strength", zone: "hero", font: "body", weight: 700, sizeFactor: 0.064, minPt: 4.5, maxLines: 1, color: "onAccent", chip: "fill", spacingBefore: 1.2 },
      subtitleRow(),
      volumeRow(),
      ...detailBlock(),
    ],
    codeCorner: "bottom-left",
    decor: [
      { kind: "corners", lengthMm: 3.2, strokePt: 1.3, color: "accent", insetMm: 1.2, minLabelHeightMm: 14 },
    ],
    materials: ["neon", "plain", "glossy"],
  }),
  defineTemplate({
    id: "energy-gradient",
    name: "Energy Gradient",
    family: "energy-gradient",
    familyName: "Energy Gradient",
    category: ["neon"],
    mood: ["gradient", "energetic", "grounded"],
    vibe: { bold: 2, playful: 2 },
    colorMode: "dark",
    density: "standard",
    pairingId: "bold-modern",
    recommendedGlass: ["clear", "cobalt"],
    align: "left",
    rows: [
      brandCaps({ letterSpacingEm: 0.16 }),
      kickerSubtitle({ spacingBefore: 0.6 }),
      productHero(0.17, { spacingBefore: 0.5 }),
      strengthRow({ sizeFactor: 0.068 }),
      volumeRow(),
      ...detailBlock(),
    ],
    codeCorner: "bottom-right",
    decor: [
      { kind: "band", edge: "bottom", heightFactor: 0.14, fill: { gradient: true }, inset: true, minLabelHeightMm: 16 },
    ],
    materials: ["neon", "plain", "glossy"],
  }),
  defineTemplate({
    id: "digital-spectrum",
    name: "Digital Spectrum",
    family: "digital-spectrum",
    familyName: "Digital Spectrum",
    category: ["neon", "laboratory"],
    mood: ["digital", "two-column", "dense"],
    vibe: { futuristic: 2, bold: 1, clinical: 1 },
    colorMode: "dark",
    density: "detailed",
    pairingId: "tech-lab",
    recommendedGlass: ["cobalt"],
    align: "left",
    minHeightMm: 22,
    minWidthMm: 45,
    split: { ratio: 0.5 },
    rows: [
      brandCaps({ letterSpacingEm: 0.18 }),
      productHero(0.145, { casing: "uppercase" }),
      strengthRow({ weight: 700, sizeFactor: 0.066 }),
      subtitleRow({ sizeFactor: 0.046, maxLines: 2 }),
      volumeRow("header", { column: "right", font: "technical" }),
      { slot: "lot", zone: "header", font: "technical", sizeFactor: 0.044, minPt: 4, maxLines: 1, color: "muted", column: "right", spacingBefore: 0.3 },
      { slot: "expiry", zone: "header", font: "technical", sizeFactor: 0.044, minPt: 4, maxLines: 1, color: "muted", column: "right", spacingBefore: 0.25 },
      { slot: "description", zone: "hero", font: "body", sizeFactor: 0.044, minPt: 4, maxLines: 3, color: "muted", column: "right" },
      { slot: "ingredients", zone: "footer", font: "body", sizeFactor: 0.042, minPt: 4, maxLines: 3, color: "muted", column: "right" },
      { slot: "directions", zone: "footer", font: "body", sizeFactor: 0.042, minPt: 4, maxLines: 2, color: "muted", column: "right", spacingBefore: 0.35 },
      { slot: "storage", zone: "footer", font: "body", sizeFactor: 0.042, minPt: 4, maxLines: 1, color: "muted", column: "right", spacingBefore: 0.3 },
      { slot: "warning", zone: "footer", font: "body", emphasis: true, sizeFactor: 0.044, minPt: 4, maxLines: 2, color: "text" },
      { slot: "verification", zone: "footer", font: "technical", sizeFactor: 0.042, minPt: 4, maxLines: 1, color: "muted", spacingBefore: 0.3 },
      { slot: "website", zone: "footer", font: "body", emphasis: true, sizeFactor: 0.044, minPt: 4, maxLines: 1, color: "accent", spacingBefore: 0.4 },
    ],
    codeCorner: "bottom-right",
    decor: [
      { kind: "side-rail", edge: "left", insetMm: 1.2, strokePt: 1.2, color: "accent" },
    ],
    materials: ["neon", "holographic", "plain", "glossy"],
  }),
  defineTemplate({
    id: "neon-pulse-band",
    name: "Neon Pulse Band",
    family: "neon-pulse-band",
    familyName: "Neon Pulse Band",
    category: ["neon", "plain"],
    mood: ["banded", "condensed", "punchy"],
    vibe: { bold: 3, futuristic: 1 },
    colorMode: "dark",
    density: "standard",
    pairingId: "condensed-impact",
    recommendedGlass: ["clear", "opaque"],
    align: "left",
    rows: [
      brandCaps({ weight: 400, letterSpacingEm: 0.18 }),
      productHero(0.185, { casing: "uppercase", minPt: 8 }),
      { slot: "strength", zone: "hero", font: "body", weight: 600, sizeFactor: 0.062, minPt: 4.5, maxLines: 1, color: "accent", chip: "outline", spacingBefore: 1.2 },
      subtitleRow(),
      volumeRow(),
      ...detailBlock(),
    ],
    codeCorner: "bottom-right",
    decor: [
      { kind: "band", edge: "bottom", heightFactor: 0.08, fill: { role: "accent" } },
    ],
    materials: ["neon", "plain", "glossy"],
  }),
  // --- Beauty & skincare -----------------------------------------------------------------
  defineTemplate({
    id: "pearl-skincare",
    name: "Pearl Skincare",
    family: "pearl-skincare",
    familyName: "Pearl Skincare",
    category: ["beauty", "luxury"],
    mood: ["pearl", "kicker", "editorial"],
    vibe: { luxury: 2, minimal: 2 },
    colorMode: "light",
    density: "minimal",
    pairingId: "editorial-beauty",
    recommendedGlass: ["frosted", "opaque"],
    align: "center",
    rows: [
      brandCaps({ weight: 400, letterSpacingEm: 0.3 }),
      kickerSubtitle({ color: "muted", spacingBefore: 0.5 }),
      productHero(0.165, { spacingBefore: 0.5 }),
      strengthRow({ sizeFactor: 0.056, spacingBefore: 1.3 }),
      volumeRow(),
      ...detailBlock(),
    ],
    codeCorner: "bottom-right",
    decor: [],
  }),
  defineTemplate({
    id: "botanical-serum",
    name: "Botanical Serum",
    family: "botanical-serum",
    familyName: "Botanical Serum",
    category: ["beauty", "botanical"],
    mood: ["herbal", "left", "divided"],
    vibe: { botanical: 3, minimal: 1 },
    colorMode: "light",
    density: "standard",
    pairingId: "botanical-premium",
    recommendedGlass: ["amber", "clear"],
    align: "left",
    rows: [
      brandCaps({ weight: 500, letterSpacingEm: 0.2 }),
      productHero(0.16),
      subtitleRow({ maxLines: 2 }),
      strengthRow({ weight: 500, sizeFactor: 0.058 }),
      volumeRow(),
      ...detailBlock(),
    ],
    codeCorner: "bottom-right",
    decor: [
      { kind: "divider", after: "subtitle", widthFactor: 0.14, strokePt: 0.6, fill: { role: "accent" } },
    ],
    materials: ["plain", "kraft", "matte", "clear", "glossy"],
  }),
  defineTemplate({
    id: "clinical-beauty",
    name: "Clinical Beauty",
    family: "clinical-beauty",
    familyName: "Clinical Beauty",
    category: ["beauty", "clinical"],
    mood: ["derm", "outlined", "precise"],
    vibe: { clinical: 2, minimal: 2, luxury: 1 },
    colorMode: "light",
    density: "standard",
    pairingId: "modern-clinical",
    recommendedGlass: ["clear", "frosted"],
    align: "center",
    rows: [
      brandCaps({ letterSpacingEm: 0.22 }),
      productHero(0.14),
      subtitleRow(),
      { slot: "strength", zone: "hero", font: "body", weight: 600, sizeFactor: 0.056, minPt: 4.5, maxLines: 1, color: "accent", chip: "outline", spacingBefore: 1.3 },
      volumeRow(),
      ...detailBlock(),
    ],
    codeCorner: "bottom-right",
    decor: [
      { kind: "border", insetMm: 1.4, strokePt: 0.6, color: "border" },
    ],
  }),
  defineTemplate({
    id: "soft-gradient",
    name: "Soft Gradient",
    family: "soft-gradient",
    familyName: "Soft Gradient",
    category: ["beauty", "plain"],
    mood: ["gradient", "gentle", "modern"],
    vibe: { minimal: 2, luxury: 1, playful: 1 },
    colorMode: "light",
    density: "standard",
    pairingId: "contemporary-skincare",
    recommendedGlass: ["frosted", "clear"],
    align: "left",
    rows: [
      brandCaps({ letterSpacingEm: 0.16 }),
      productHero(0.155),
      subtitleRow({ maxLines: 2 }),
      strengthRow({ sizeFactor: 0.058 }),
      volumeRow(),
      ...detailBlock(),
    ],
    codeCorner: "bottom-left",
    decor: [
      { kind: "band", edge: "top", heightFactor: 0.11, fill: { gradient: true }, inset: true, minLabelHeightMm: 15 },
    ],
  }),
  defineTemplate({
    id: "nude-luxury",
    name: "Nude Luxury",
    family: "nude-luxury",
    familyName: "Nude Luxury",
    category: ["beauty", "luxury"],
    mood: ["nude", "brand-below", "serif"],
    vibe: { luxury: 2, minimal: 2, botanical: 1 },
    colorMode: "light",
    density: "minimal",
    pairingId: "prata-elegant",
    recommendedGlass: ["frosted", "amber"],
    align: "center",
    rows: [
      productHero(0.17),
      subtitleRow({ spacingBefore: 0.9 }),
      strengthRow({ weight: 500, sizeFactor: 0.055, letterSpacingEm: 0.1 }),
      brandBottom({ letterSpacingEm: 0.26, weight: 500 }),
      volumeRow("footer", { spacingBefore: 0.35 }),
      ...detailBlock(),
    ],
    codeCorner: "bottom-right",
    decor: [
      { kind: "divider", after: "strength", widthFactor: 0.08, strokePt: 0.6, fill: { role: "accent" } },
    ],
  }),
  defineTemplate({
    id: "clean-cosmetic",
    name: "Clean Cosmetic",
    family: "clean-cosmetic",
    familyName: "Clean Cosmetic",
    category: ["beauty", "plain"],
    mood: ["clean", "sentence-case", "quiet"],
    vibe: { minimal: 3, clinical: 1 },
    colorMode: "light",
    density: "minimal",
    pairingId: "contemporary-skincare",
    recommendedGlass: ["clear", "frosted"],
    align: "center",
    rows: [
      brandCaps({ casing: undefined, letterSpacingEm: 0.04, weight: 700, sizeFactor: 0.06 }),
      productHero(0.15, { spacingBefore: 1.1 }),
      subtitleRow({ maxLines: 2 }),
      strengthRow({ color: "muted", weight: 600, sizeFactor: 0.054, spacingBefore: 1.2 }),
      volumeRow(),
      ...detailBlock(),
    ],
    codeCorner: "bottom-right",
    decor: [],
  }),
  defineTemplate({
    id: "petal-soft",
    name: "Petal Soft",
    family: "petal-soft",
    familyName: "Petal Soft",
    category: ["beauty", "botanical"],
    mood: ["petal", "rounded", "warm"],
    vibe: { botanical: 2, playful: 1, minimal: 1 },
    colorMode: "light",
    density: "standard",
    pairingId: "friendly-organic",
    recommendedGlass: ["frosted", "amber"],
    align: "center",
    rows: [
      brandCaps({ weight: 600, letterSpacingEm: 0.2 }),
      productHero(0.15),
      subtitleRow({ maxLines: 2 }),
      strengthRow({ sizeFactor: 0.058 }),
      volumeRow(),
      ...detailBlock(),
    ],
    codeCorner: "bottom-left",
    decor: [
      { kind: "band", edge: "bottom", heightFactor: 0.09, fill: { role: "accent" }, inset: true, minLabelHeightMm: 14 },
    ],
  }),
  // --- Botanical & apothecary ---------------------------------------------------------
  defineTemplate({
    id: "botanical-frame",
    name: "Botanical Frame",
    family: "botanical-frame",
    familyName: "Botanical Frame",
    category: ["botanical", "beauty"],
    mood: ["framed", "heritage", "left"],
    vibe: { botanical: 3, luxury: 1 },
    colorMode: "light",
    density: "standard",
    pairingId: "heritage-apothecary",
    recommendedGlass: ["amber"],
    align: "left",
    rows: [
      brandCaps({ font: "display", weight: 700, casing: undefined, letterSpacingEm: 0.04, sizeFactor: 0.06 }),
      productHero(0.15),
      subtitleRow({ maxLines: 2 }),
      strengthRow({ weight: 600, sizeFactor: 0.058 }),
      volumeRow(),
      ...detailBlock(),
    ],
    codeCorner: "bottom-right",
    decor: [
      { kind: "border", insetMm: 1.1, strokePt: 0.7, color: "text" },
      { kind: "border", insetMm: 1.8, strokePt: 0.35, color: "muted", minLabelHeightMm: 15 },
    ],
    materials: ["kraft", "plain", "matte", "clear"],
  }),
  defineTemplate({
    id: "herbal-ledger",
    name: "Herbal Ledger",
    family: "herbal-ledger",
    familyName: "Herbal Ledger",
    category: ["botanical", "laboratory"],
    mood: ["ledger", "mono", "warm"],
    vibe: { botanical: 2, clinical: 1, minimal: 1 },
    colorMode: "light",
    density: "standard",
    pairingId: "retro-terminal",
    recommendedGlass: ["amber"],
    align: "left",
    rows: [
      brandCaps({ weight: 700, letterSpacingEm: 0.08 }),
      ...techHeader(),
      productHero(0.125),
      strengthRow({ weight: 700, sizeFactor: 0.06 }),
      subtitleRow({ sizeFactor: 0.046 }),
      volumeRow("footer", { font: "technical" }),
      ...tightDetailBlock().filter((r) => r.slot !== "lot" && r.slot !== "expiry"),
    ],
    codeCorner: "bottom-right",
    decor: [
      { kind: "divider", after: "expiry", widthFactor: 0.94, strokePt: 0.5, fill: { role: "border" } },
    ],
    materials: ["kraft", "plain", "matte", "clear"],
  }),
  defineTemplate({
    id: "garden-caps",
    name: "Garden Caps",
    family: "garden-caps",
    familyName: "Garden Caps",
    category: ["botanical", "plain"],
    mood: ["monogram", "friendly", "round"],
    vibe: { botanical: 2, playful: 2 },
    colorMode: "light",
    density: "minimal",
    pairingId: "friendly-organic",
    recommendedGlass: ["clear", "amber"],
    align: "center",
    minHeightMm: 18,
    rows: [
      { slot: "brand", zone: "header", font: "display", sizeFactor: 0.115, minPt: 6.5, maxLines: 1, color: "onAccent", monogram: true },
      productHero(0.14, { spacingBefore: 1.5 }),
      subtitleRow({ maxLines: 2 }),
      strengthRow({ sizeFactor: 0.056 }),
      volumeRow(),
      ...detailBlock(),
    ],
    codeCorner: "bottom-right",
    decor: [
      { kind: "medallion", sizeFactor: 0.2, fill: { role: "accent" }, minLabelHeightMm: 18 },
    ],
    materials: ["plain", "kraft", "matte", "clear", "glossy"],
  }),
  defineTemplate({
    id: "sage-column",
    name: "Sage Column",
    family: "sage-column",
    familyName: "Sage Column",
    category: ["botanical", "beauty"],
    mood: ["sage", "vertical", "calm"],
    vibe: { botanical: 2, minimal: 2 },
    colorMode: "light",
    density: "standard",
    pairingId: "marcellus-calm",
    recommendedGlass: ["amber", "clear"],
    align: "left",
    minHeightMm: 16,
    verticalRow: { slot: "brand", edge: "right", font: "body", weight: 500, sizeFactor: 0.046, minPt: 4.5, color: "muted", letterSpacingEm: 0.24, casing: "uppercase" },
    rows: [
      productHero(0.155),
      subtitleRow({ maxLines: 2 }),
      strengthRow({ weight: 500, sizeFactor: 0.058 }),
      volumeRow(),
      ...detailBlock(),
    ],
    codeCorner: "bottom-left",
    decor: [
      { kind: "side-rail", edge: "left", insetMm: 1.3, strokePt: 0.9, color: "accent" },
    ],
    materials: ["plain", "kraft", "matte", "clear"],
  }),
  defineTemplate({
    id: "amber-apothecary",
    name: "Amber Apothecary",
    family: "amber-apothecary",
    familyName: "Amber Apothecary",
    category: ["botanical", "plain"],
    mood: ["amber", "kicker", "heritage"],
    vibe: { botanical: 3, premium: 1 },
    colorMode: "light",
    density: "standard",
    pairingId: "heritage-apothecary",
    recommendedGlass: ["amber"],
    align: "left",
    rows: [
      brandCaps({ font: "display", weight: 700, casing: undefined, letterSpacingEm: 0.03, sizeFactor: 0.062 }),
      kickerSubtitle({ spacingBefore: 0.6 }),
      productHero(0.155, { spacingBefore: 0.5 }),
      strengthRow({ weight: 600, sizeFactor: 0.058 }),
      volumeRow(),
      ...detailBlock(),
    ],
    codeCorner: "bottom-right",
    decor: [
      { kind: "border", insetMm: 1.2, strokePt: 0.6, color: "muted" },
    ],
    materials: ["kraft", "plain", "matte"],
  }),
  defineTemplate({
    id: "clear-mark",
    name: "Clear Mark",
    family: "clear-mark",
    familyName: "Clear Mark",
    category: ["transparent", "luxury"],
    mood: ["mark", "monogram", "invisible"],
    vibe: { minimal: 2, luxury: 2 },
    colorMode: "light",
    density: "minimal",
    pairingId: "minimal-premium",
    recommendedGlass: ["clear", "frosted"],
    align: "center",
    minHeightMm: 18,
    rows: [
      { slot: "brand", zone: "header", font: "display", sizeFactor: 0.115, minPt: 6.5, maxLines: 1, color: "accent", monogram: true },
      productHero(0.14, { spacingBefore: 1.5 }),
      strengthRow({ weight: 600, color: "text", sizeFactor: 0.056 }),
      subtitleRow({ sizeFactor: 0.046 }),
      volumeRow(),
      ...detailBlock(),
    ],
    codeCorner: "bottom-right",
    decor: [
      { kind: "medallion", sizeFactor: 0.19, fill: { role: "accent" }, ring: true, minLabelHeightMm: 18 },
    ],
    materials: ["clear", "plain", "glossy", "matte"],
  }),
] as const;
