import { footerRows } from "./core";
import type { EasyTemplateDef } from "./types";
import { defineTemplate } from "./types";

/** Laboratory & research flagship families (§5): data-first layouts. */

export const LABORATORY_TEMPLATES: readonly EasyTemplateDef[] = [
  defineTemplate({
    id: "laboratory-grid",
    name: "Laboratory Grid",
    family: "laboratory-grid",
    familyName: "Laboratory Grid",
    category: ["laboratory", "research", "clinical"],
    mood: ["gridded", "framed", "technical"],
    vibe: { clinical: 2, futuristic: 2 },
    colorMode: "light",
    density: "detailed",
    pairingId: "tech-lab",
    recommendedGlass: ["clear", "cobalt"],
    align: "left",
    rows: [
      { slot: "brand", zone: "header", font: "display", sizeFactor: 0.06, minPt: 4.5, maxLines: 1, color: "text", letterSpacingEm: 0.08, casing: "uppercase" },
      { slot: "lot", zone: "header", font: "technical", sizeFactor: 0.044, minPt: 4, maxLines: 1, color: "muted", spacingBefore: 0.4 },
      { slot: "expiry", zone: "header", font: "technical", sizeFactor: 0.044, minPt: 4, maxLines: 1, color: "muted", spacingBefore: 0.25 },
      { slot: "product-name", zone: "hero", font: "display", sizeFactor: 0.13, minPt: 6.5, maxLines: 2, color: "text" },
      { slot: "strength", zone: "hero", font: "body", weight: 600, sizeFactor: 0.068, minPt: 4.5, maxLines: 1, color: "accent", spacingBefore: 0.8 },
      { slot: "subtitle", zone: "hero", font: "body", sizeFactor: 0.048, minPt: 4, maxLines: 1, color: "muted", spacingBefore: 0.5 },
      { slot: "volume", zone: "footer", font: "technical", sizeFactor: 0.046, minPt: 4, maxLines: 1, color: "muted" },
      { slot: "description", zone: "footer", font: "body", sizeFactor: 0.044, minPt: 4, maxLines: 2, color: "muted", spacingBefore: 0.35 },
      { slot: "ingredients", zone: "footer", font: "body", sizeFactor: 0.042, minPt: 4, maxLines: 3, color: "muted", spacingBefore: 0.35 },
      { slot: "directions", zone: "footer", font: "body", sizeFactor: 0.042, minPt: 4, maxLines: 2, color: "muted", spacingBefore: 0.3 },
      { slot: "storage", zone: "footer", font: "body", sizeFactor: 0.042, minPt: 4, maxLines: 1, color: "muted", spacingBefore: 0.3 },
      { slot: "warning", zone: "footer", font: "body", emphasis: true, sizeFactor: 0.042, minPt: 4, maxLines: 2, color: "text", spacingBefore: 0.3 },
      { slot: "verification", zone: "footer", font: "technical", sizeFactor: 0.042, minPt: 4, maxLines: 1, color: "muted", spacingBefore: 0.3 },
      { slot: "website", zone: "footer", font: "body", sizeFactor: 0.044, minPt: 4, maxLines: 1, color: "accent", spacingBefore: 0.4 },
    ],
    codeCorner: "bottom-right",
    decor: [
      { kind: "border", insetMm: 1, strokePt: 0.9, color: "text" },
      { kind: "side-rail", edge: "left", insetMm: 2.2, strokePt: 0.6, color: "accent", minLabelHeightMm: 15 },
    ],
  }),
  defineTemplate({
    id: "research-index",
    name: "Research Index",
    family: "research-index",
    familyName: "Research Index",
    category: ["laboratory", "research"],
    mood: ["indexed", "terminal", "columned"],
    vibe: { clinical: 2, futuristic: 1, minimal: 1 },
    colorMode: "light",
    density: "detailed",
    pairingId: "retro-terminal",
    recommendedGlass: ["clear"],
    align: "left",
    minHeightMm: 22,
    minWidthMm: 45,
    split: { ratio: 0.52, divider: true },
    rows: [
      { slot: "brand", zone: "header", font: "display", sizeFactor: 0.055, minPt: 4.5, maxLines: 1, color: "accent", casing: "uppercase" },
      { slot: "product-name", zone: "hero", font: "display", sizeFactor: 0.12, minPt: 6, maxLines: 2, color: "text", casing: "uppercase" },
      { slot: "strength", zone: "hero", font: "body", weight: 700, sizeFactor: 0.065, minPt: 4.5, maxLines: 1, color: "accent", spacingBefore: 0.8 },
      { slot: "subtitle", zone: "hero", font: "body", sizeFactor: 0.046, minPt: 4, maxLines: 2, color: "muted", spacingBefore: 0.5 },
      { slot: "volume", zone: "header", font: "technical", sizeFactor: 0.046, minPt: 4, maxLines: 1, color: "muted", column: "right" },
      { slot: "lot", zone: "header", font: "technical", sizeFactor: 0.046, minPt: 4, maxLines: 1, color: "muted", column: "right", spacingBefore: 0.35 },
      { slot: "expiry", zone: "header", font: "technical", sizeFactor: 0.046, minPt: 4, maxLines: 1, color: "muted", column: "right", spacingBefore: 0.25 },
      { slot: "verification", zone: "header", font: "technical", sizeFactor: 0.044, minPt: 4, maxLines: 1, color: "muted", column: "right", spacingBefore: 0.25 },
      { slot: "description", zone: "hero", font: "body", sizeFactor: 0.044, minPt: 4, maxLines: 3, color: "muted", column: "right" },
      { slot: "ingredients", zone: "footer", font: "body", sizeFactor: 0.042, minPt: 4, maxLines: 3, color: "muted", column: "right" },
      { slot: "directions", zone: "footer", font: "body", sizeFactor: 0.042, minPt: 4, maxLines: 2, color: "muted", column: "right", spacingBefore: 0.35 },
      { slot: "storage", zone: "footer", font: "body", sizeFactor: 0.042, minPt: 4, maxLines: 1, color: "muted", column: "right", spacingBefore: 0.35 },
      { slot: "warning", zone: "footer", font: "body", emphasis: true, sizeFactor: 0.044, minPt: 4, maxLines: 2, color: "text" },
      { slot: "website", zone: "footer", font: "body", sizeFactor: 0.044, minPt: 4, maxLines: 1, color: "accent", spacingBefore: 0.4 },
    ],
    codeCorner: "bottom-right",
    decor: [],
  }),
  defineTemplate({
    id: "molecular-line",
    name: "Molecular Line",
    family: "molecular-line",
    familyName: "Molecular Line",
    category: ["laboratory", "research", "plain"],
    mood: ["linear", "minimal", "precise"],
    vibe: { clinical: 1, minimal: 3, futuristic: 1 },
    colorMode: "light",
    density: "standard",
    pairingId: "grotesk-minimal",
    recommendedGlass: ["clear", "frosted"],
    align: "left",
    rows: [
      { slot: "brand", zone: "header", font: "body", weight: 500, sizeFactor: 0.052, minPt: 4.5, maxLines: 1, color: "text", letterSpacingEm: 0.05 },
      { slot: "product-name", zone: "hero", font: "display", sizeFactor: 0.14, minPt: 6.5, maxLines: 2, color: "text" },
      { slot: "strength", zone: "hero", font: "body", sizeFactor: 0.06, minPt: 4.5, maxLines: 1, color: "accent", spacingBefore: 0.9 },
      { slot: "subtitle", zone: "hero", font: "body", sizeFactor: 0.048, minPt: 4, maxLines: 1, color: "muted", spacingBefore: 0.5 },
      { slot: "volume", zone: "footer", font: "body", sizeFactor: 0.048, minPt: 4, maxLines: 1, color: "muted" },
      ...footerRows(),
    ],
    codeCorner: "bottom-right",
    decor: [
      { kind: "divider", after: "brand", widthFactor: 0.94, strokePt: 0.5, fill: { role: "border" } },
      { kind: "divider", after: "strength", widthFactor: 0.2, strokePt: 0.8, fill: { role: "accent" } },
    ],
  }),
  defineTemplate({
    id: "data-matrix",
    name: "Data Matrix",
    family: "data-matrix",
    familyName: "Data Matrix",
    category: ["laboratory", "research", "clinical"],
    mood: ["scannable", "side-coded", "engineered"],
    vibe: { futuristic: 2, clinical: 2 },
    colorMode: "light",
    density: "standard",
    pairingId: "engineered",
    recommendedGlass: ["clear", "cobalt"],
    align: "left",
    codePlacement: "side",
    qrScale: 1.2,
    rows: [
      { slot: "brand", zone: "header", font: "body", weight: 700, sizeFactor: 0.052, minPt: 4.5, maxLines: 1, color: "muted", letterSpacingEm: 0.14, casing: "uppercase" },
      { slot: "product-name", zone: "hero", font: "display", sizeFactor: 0.115, minPt: 6, maxLines: 2, color: "text" },
      { slot: "strength", zone: "hero", font: "body", weight: 700, sizeFactor: 0.062, minPt: 4.5, maxLines: 1, color: "accent", spacingBefore: 0.9 },
      { slot: "subtitle", zone: "hero", font: "body", sizeFactor: 0.046, minPt: 4, maxLines: 1, color: "muted", spacingBefore: 0.5 },
      { slot: "volume", zone: "footer", font: "body", sizeFactor: 0.046, minPt: 4, maxLines: 1, color: "muted" },
      ...footerRows(),
    ],
    codeCorner: "bottom-right",
    decor: [
      { kind: "side-rail", edge: "left", insetMm: 1.2, strokePt: 1.6, color: "accent" },
    ],
  }),
  defineTemplate({
    id: "specimen-compact",
    name: "Specimen Compact",
    family: "specimen-record",
    familyName: "Specimen Record",
    category: ["laboratory", "research"],
    mood: ["compact", "monospace", "utilitarian"],
    vibe: { clinical: 2, minimal: 2 },
    colorMode: "light",
    density: "standard",
    pairingId: "retro-terminal",
    recommendedGlass: ["clear", "amber"],
    align: "left",
    codePlacement: "footer-center",
    rows: [
      { slot: "brand", zone: "header", font: "body", weight: 700, sizeFactor: 0.055, minPt: 4.5, maxLines: 1, color: "text", casing: "uppercase" },
      { slot: "product-name", zone: "hero", font: "display", sizeFactor: 0.11, minPt: 6, maxLines: 2, color: "text" },
      { slot: "strength", zone: "hero", font: "body", weight: 700, sizeFactor: 0.06, minPt: 4.5, maxLines: 1, color: "accent", spacingBefore: 0.7 },
      { slot: "lot", zone: "footer", font: "technical", sizeFactor: 0.046, minPt: 4, maxLines: 1, color: "muted" },
      { slot: "expiry", zone: "footer", font: "technical", sizeFactor: 0.046, minPt: 4, maxLines: 1, color: "muted", spacingBefore: 0.25 },
      { slot: "volume", zone: "footer", font: "technical", sizeFactor: 0.046, minPt: 4, maxLines: 1, color: "muted", spacingBefore: 0.25 },
      { slot: "warning", zone: "footer", font: "body", emphasis: true, sizeFactor: 0.044, minPt: 4, maxLines: 2, color: "text", spacingBefore: 0.4 },
      { slot: "verification", zone: "footer", font: "technical", sizeFactor: 0.044, minPt: 4, maxLines: 1, color: "muted", spacingBefore: 0.25 },
    ],
    codeCorner: "bottom-left",
    decor: [
      { kind: "divider", after: "strength", widthFactor: 0.94, strokePt: 0.5, fill: { role: "border" } },
    ],
  }),
] as const;
