import { footerRows } from "./core";
import type { EasyTemplateDef } from "./types";
import { defineTemplate } from "./types";

/**
 * Luxury flagship families (§5): serif-led, generous spacing, dark and
 * ivory variants — each a genuinely different grid, not a color swap.
 */

export const LUXURY_TEMPLATES: readonly EasyTemplateDef[] = [
  defineTemplate({
    id: "obsidian-gold",
    name: "Obsidian Gold",
    family: "obsidian-gold",
    familyName: "Obsidian Gold",
    category: ["luxury", "glossy"],
    mood: ["opulent", "engraved", "cornered"],
    vibe: { luxury: 3, premium: 3 },
    colorMode: "dark",
    density: "standard",
    pairingId: "prata-elegant",
    recommendedGlass: ["amber", "opaque"],
    featured: true,
    align: "center",
    rows: [
      { slot: "brand", zone: "header", font: "body", weight: 600, sizeFactor: 0.055, minPt: 4.5, maxLines: 1, color: "accent", letterSpacingEm: 0.34, casing: "uppercase" },
      { slot: "product-name", zone: "hero", font: "display", sizeFactor: 0.155, minPt: 7, maxLines: 2, color: "text" },
      { slot: "subtitle", zone: "hero", font: "body", sizeFactor: 0.05, minPt: 4, maxLines: 1, color: "muted", letterSpacingEm: 0.1, spacingBefore: 1.1 },
      { slot: "strength", zone: "hero", font: "body", weight: 500, sizeFactor: 0.062, minPt: 4.5, maxLines: 1, color: "accent", letterSpacingEm: 0.18, spacingBefore: 1.3, casing: "uppercase" },
      { slot: "volume", zone: "footer", font: "body", sizeFactor: 0.048, minPt: 4, maxLines: 1, color: "muted", letterSpacingEm: 0.08 },
      ...footerRows(),
    ],
    codeCorner: "bottom-right",
    decor: [
      { kind: "corners", lengthMm: 3.4, strokePt: 0.8, color: "accent", insetMm: 1.4, minLabelHeightMm: 15 },
      { kind: "divider", after: "product-name", widthFactor: 0.12, strokePt: 0.7, fill: { effect: true } },
    ],
  }),
  defineTemplate({
    id: "ivory-atelier",
    name: "Ivory Atelier",
    family: "ivory-atelier",
    familyName: "Ivory Atelier",
    category: ["luxury", "beauty", "plain"],
    mood: ["ivory", "quiet", "editorial"],
    vibe: { luxury: 3, minimal: 2, premium: 1 },
    colorMode: "light",
    density: "minimal",
    pairingId: "quiet-luxury",
    recommendedGlass: ["clear", "frosted"],
    featured: true,
    align: "left",
    rows: [
      { slot: "brand", zone: "header", font: "body", weight: 500, sizeFactor: 0.052, minPt: 4.5, maxLines: 1, color: "muted", letterSpacingEm: 0.24, casing: "uppercase" },
      { slot: "product-name", zone: "hero", font: "display", sizeFactor: 0.17, minPt: 7, maxLines: 2, color: "text" },
      { slot: "subtitle", zone: "hero", font: "body", sizeFactor: 0.052, minPt: 4, maxLines: 2, color: "muted", spacingBefore: 1 },
      { slot: "strength", zone: "hero", font: "body", weight: 500, sizeFactor: 0.058, minPt: 4.5, maxLines: 1, color: "text", spacingBefore: 1.4 },
      { slot: "volume", zone: "footer", font: "body", sizeFactor: 0.048, minPt: 4, maxLines: 1, color: "muted" },
      ...footerRows(),
    ],
    codeCorner: "bottom-right",
    decor: [
      { kind: "side-rail", edge: "left", insetMm: 1.3, strokePt: 1.1, color: "accent" },
    ],
  }),
  defineTemplate({
    id: "midnight-chrome",
    name: "Midnight Chrome",
    family: "midnight-chrome",
    familyName: "Midnight Chrome",
    category: ["luxury", "glossy", "holographic"],
    mood: ["chrome", "sleek", "vertical"],
    vibe: { luxury: 2, premium: 2, futuristic: 2 },
    colorMode: "dark",
    density: "standard",
    pairingId: "minimal-premium",
    recommendedGlass: ["opaque", "cobalt"],
    align: "left",
    minHeightMm: 16,
    verticalRow: { slot: "brand", edge: "left", font: "body", weight: 600, sizeFactor: 0.05, minPt: 4.5, color: "muted", letterSpacingEm: 0.3, casing: "uppercase" },
    rows: [
      { slot: "product-name", zone: "hero", font: "display", sizeFactor: 0.16, minPt: 7, maxLines: 2, color: "text" },
      { slot: "subtitle", zone: "hero", font: "body", sizeFactor: 0.05, minPt: 4, maxLines: 1, color: "muted", spacingBefore: 0.9 },
      { slot: "strength", zone: "hero", font: "body", weight: 600, sizeFactor: 0.065, minPt: 4.5, maxLines: 1, color: "accent", spacingBefore: 1.1 },
      { slot: "volume", zone: "footer", font: "body", sizeFactor: 0.048, minPt: 4, maxLines: 1, color: "muted" },
      ...footerRows(),
    ],
    codeCorner: "bottom-right",
    decor: [
      { kind: "stripe", edge: "right", widthFactor: 0.04, fill: { effect: true } },
    ],
  }),
  defineTemplate({
    id: "onyx-monogram",
    name: "Onyx Monogram",
    family: "onyx-monogram",
    familyName: "Onyx Monogram",
    category: ["luxury"],
    mood: ["monogram", "medallion", "formal"],
    vibe: { luxury: 3, premium: 2, minimal: 1 },
    colorMode: "dark",
    density: "minimal",
    pairingId: "classic-estate",
    recommendedGlass: ["amber", "opaque"],
    align: "center",
    minHeightMm: 18,
    rows: [
      { slot: "brand", zone: "header", font: "display", sizeFactor: 0.12, minPt: 7, maxLines: 1, color: "accent", monogram: true },
      { slot: "product-name", zone: "hero", font: "display", sizeFactor: 0.13, minPt: 6.5, maxLines: 2, color: "text", casing: "uppercase", letterSpacingEm: 0.06, spacingBefore: 1.6 },
      { slot: "subtitle", zone: "hero", font: "body", sizeFactor: 0.048, minPt: 4, maxLines: 1, color: "muted", letterSpacingEm: 0.12, spacingBefore: 0.9 },
      { slot: "strength", zone: "hero", font: "body", weight: 500, sizeFactor: 0.058, minPt: 4.5, maxLines: 1, color: "accent", letterSpacingEm: 0.16, spacingBefore: 1.1 },
      { slot: "volume", zone: "footer", font: "body", sizeFactor: 0.048, minPt: 4, maxLines: 1, color: "muted" },
      ...footerRows(),
    ],
    codeCorner: "bottom-right",
    decor: [
      { kind: "medallion", sizeFactor: 0.2, fill: { role: "accent" }, ring: true, minLabelHeightMm: 18 },
    ],
  }),
  defineTemplate({
    id: "imperial-emerald",
    name: "Imperial Emerald",
    family: "imperial-emerald",
    familyName: "Imperial Emerald",
    category: ["luxury", "botanical"],
    mood: ["regal", "columned", "deep"],
    vibe: { luxury: 3, botanical: 1, premium: 2 },
    colorMode: "dark",
    density: "detailed",
    pairingId: "botanical-premium",
    recommendedGlass: ["amber", "cobalt"],
    align: "left",
    minHeightMm: 22,
    minWidthMm: 45,
    split: { ratio: 0.58, divider: true },
    rows: [
      { slot: "brand", zone: "header", font: "body", weight: 600, sizeFactor: 0.055, minPt: 4.5, maxLines: 1, color: "accent", letterSpacingEm: 0.26, casing: "uppercase" },
      { slot: "product-name", zone: "hero", font: "display", sizeFactor: 0.16, minPt: 7, maxLines: 2, color: "text" },
      { slot: "subtitle", zone: "hero", font: "body", sizeFactor: 0.05, minPt: 4, maxLines: 2, color: "muted", spacingBefore: 0.9 },
      { slot: "strength", zone: "hero", font: "body", weight: 500, sizeFactor: 0.06, minPt: 4.5, maxLines: 1, color: "accent", spacingBefore: 1.1 },
      { slot: "volume", zone: "header", font: "body", sizeFactor: 0.046, minPt: 4, maxLines: 1, color: "muted", column: "right" },
      { slot: "description", zone: "hero", font: "body", sizeFactor: 0.048, minPt: 4, maxLines: 4, color: "muted", column: "right" },
      { slot: "ingredients", zone: "footer", font: "body", sizeFactor: 0.042, minPt: 4, maxLines: 3, color: "muted", column: "right" },
      { slot: "directions", zone: "footer", font: "body", sizeFactor: 0.042, minPt: 4, maxLines: 2, color: "muted", column: "right", spacingBefore: 0.5 },
      { slot: "storage", zone: "footer", font: "body", sizeFactor: 0.042, minPt: 4, maxLines: 1, color: "muted", column: "right", spacingBefore: 0.5 },
      { slot: "warning", zone: "footer", font: "body", emphasis: true, sizeFactor: 0.042, minPt: 4, maxLines: 2, color: "text", column: "right", spacingBefore: 0.5 },
      { slot: "lot", zone: "footer", font: "technical", sizeFactor: 0.044, minPt: 4, maxLines: 1, color: "muted" },
      { slot: "expiry", zone: "footer", font: "technical", sizeFactor: 0.044, minPt: 4, maxLines: 1, color: "muted", spacingBefore: 0.3 },
      { slot: "verification", zone: "footer", font: "technical", sizeFactor: 0.042, minPt: 4, maxLines: 1, color: "muted", spacingBefore: 0.3 },
      { slot: "website", zone: "footer", font: "body", weight: 600, sizeFactor: 0.046, minPt: 4, maxLines: 1, color: "accent", spacingBefore: 0.5 },
    ],
    codeCorner: "bottom-right",
    decor: [
      { kind: "border", insetMm: 1.1, strokePt: 0.6, color: "accent" },
    ],
  }),
  defineTemplate({
    id: "rose-gold-reserve",
    name: "Rose-Gold Reserve",
    family: "rose-gold-reserve",
    familyName: "Rose-Gold Reserve",
    category: ["luxury", "beauty"],
    mood: ["blush", "warm", "banded"],
    vibe: { luxury: 2, premium: 2, botanical: 1 },
    colorMode: "light",
    density: "standard",
    pairingId: "editorial-beauty",
    recommendedGlass: ["frosted", "clear"],
    align: "center",
    rows: [
      { slot: "brand", zone: "header", font: "body", weight: 600, sizeFactor: 0.055, minPt: 4.5, maxLines: 1, color: "text", letterSpacingEm: 0.3, casing: "uppercase" },
      { slot: "product-name", zone: "hero", font: "display", sizeFactor: 0.16, minPt: 7, maxLines: 2, color: "text" },
      { slot: "subtitle", zone: "hero", font: "body", sizeFactor: 0.05, minPt: 4, maxLines: 1, color: "muted", spacingBefore: 1 },
      { slot: "strength", zone: "hero", font: "body", weight: 600, sizeFactor: 0.06, minPt: 4.5, maxLines: 1, color: "accent", spacingBefore: 1.2 },
      { slot: "volume", zone: "footer", font: "body", sizeFactor: 0.048, minPt: 4, maxLines: 1, color: "muted" },
      ...footerRows(),
    ],
    codeCorner: "bottom-left",
    decor: [
      { kind: "band", edge: "top", heightFactor: 0.09, fill: { role: "accent" }, inset: true, minLabelHeightMm: 14 },
    ],
  }),
] as const;
