import { brandCaps, productHero, strengthRow, volumeRow } from "./parts";
import type { EasyTemplateDef, RowDef } from "./types";
import { defineTemplate } from "./types";

/**
 * Peptide research family (§8): working research-vial labels built on the
 * v4 research slots — notice, lot/batch/catalog, storage, and the
 * user-supplied science data. Every layout keeps the research-use notice
 * visible (it drops second-to-last in the engine's ladder) and treats
 * lot/batch as first-class, not fine print.
 */

/** Right-column or footer technical data line. */
function dataRow(slot: RowDef["slot"], overrides: Partial<RowDef> = {}): RowDef {
  return {
    slot,
    zone: "footer",
    font: "technical",
    sizeFactor: 0.044,
    minPt: 4,
    maxLines: 1,
    color: "muted",
    spacingBefore: 0.3,
    ...overrides,
  };
}

/** The research-use notice as a quiet but unmissable uppercase line. */
function noticeRow(overrides: Partial<RowDef> = {}): RowDef {
  return {
    slot: "notice",
    zone: "footer",
    font: "body",
    emphasis: true,
    sizeFactor: 0.046,
    minPt: 4,
    maxLines: 2,
    color: "text",
    letterSpacingEm: 0.08,
    casing: "uppercase",
    spacingBefore: 0.7,
    ...overrides,
  };
}

export const RESEARCH_PEPTIDE_TEMPLATES: readonly EasyTemplateDef[] = [
  defineTemplate({
    id: "peptide-precision",
    name: "Peptide Precision",
    family: "peptide-precision",
    familyName: "Peptide Precision",
    category: ["research", "laboratory"],
    mood: ["precise", "two-column", "registry"],
    vibe: { clinical: 3, minimal: 1 },
    colorMode: "light",
    density: "standard",
    pairingId: "modern-clinical",
    recommendedGlass: ["clear", "amber"],
    featured: true,
    minHeightMm: 20,
    minWidthMm: 50,
    align: "left",
    split: { ratio: 0.56, divider: true },
    rows: [
      brandCaps({ letterSpacingEm: 0.18 }),
      productHero(0.15),
      { slot: "abbreviation", zone: "hero", font: "technical", weight: 600, sizeFactor: 0.055, minPt: 4.5, maxLines: 1, color: "accent", chip: "outline", spacingBefore: 0.9 },
      strengthRow({ color: "text", spacingBefore: 0.8 }),
      noticeRow(),
      dataRow("catalog", { zone: "header", column: "right", color: "text", weight: 600, spacingBefore: 0 }),
      dataRow("lot", { column: "right", spacingBefore: 0.35 }),
      dataRow("batch", { column: "right" }),
      dataRow("volume", { column: "right" }),
      { slot: "storage", zone: "footer", font: "body", sizeFactor: 0.042, minPt: 4, maxLines: 2, color: "muted", column: "right", spacingBefore: 0.45 },
    ],
    codeCorner: "bottom-right",
    decor: [],
  }),
  defineTemplate({
    id: "sequence-lab",
    name: "Sequence Lab",
    family: "sequence-lab",
    familyName: "Sequence Lab",
    category: ["research", "laboratory"],
    mood: ["monospace", "record", "sequence"],
    vibe: { clinical: 2, futuristic: 1, minimal: 1 },
    colorMode: "light",
    density: "detailed",
    pairingId: "retro-terminal",
    recommendedGlass: ["clear"],
    minHeightMm: 24,
    align: "left",
    rows: [
      brandCaps({ font: "technical", letterSpacingEm: 0.12 }),
      { slot: "lot", zone: "header", font: "technical", sizeFactor: 0.044, minPt: 4, maxLines: 1, color: "muted", spacingBefore: 0.4 },
      productHero(0.13),
      { slot: "strength", zone: "hero", font: "technical", weight: 700, sizeFactor: 0.06, minPt: 4.5, maxLines: 1, color: "accent", spacingBefore: 0.8 },
      { slot: "sequence", zone: "hero", font: "technical", sizeFactor: 0.042, minPt: 4, maxLines: 3, color: "muted", spacingBefore: 1, minLabelHeightMm: 24 },
      dataRow("formula", { minLabelHeightMm: 24 }),
      dataRow("molecular-weight", { minLabelHeightMm: 24 }),
      dataRow("cas", { minLabelHeightMm: 24 }),
      dataRow("batch"),
      dataRow("storage", { font: "body", maxLines: 2 }),
      noticeRow({ spacingBefore: 0.8 }),
      volumeRow("footer", { font: "technical", spacingBefore: 0.4 }),
    ],
    codeCorner: "bottom-right",
    decor: [
      { kind: "divider", after: "product-name", widthFactor: 1, strokePt: 0.7, fill: { role: "border" } },
    ],
  }),
  defineTemplate({
    id: "molecular-blue",
    name: "Molecular Blue",
    family: "molecular-blue",
    familyName: "Molecular Blue",
    category: ["research", "clinical"],
    mood: ["centered", "scientific", "calm"],
    vibe: { clinical: 3 },
    colorMode: "light",
    density: "detailed",
    pairingId: "minimal-premium",
    recommendedGlass: ["cobalt", "clear"],
    minHeightMm: 22,
    align: "center",
    rows: [
      brandCaps({ align: "center", letterSpacingEm: 0.26 }),
      { slot: "formula", zone: "hero", font: "technical", sizeFactor: 0.046, minPt: 4, maxLines: 1, color: "accent", letterSpacingEm: 0.14, casing: "uppercase" },
      productHero(0.14, { align: "center", maxLines: 2 }),
      strengthRow({ align: "center", spacingBefore: 0.8 }),
      dataRow("molecular-weight", { align: "center", minLabelHeightMm: 22 }),
      dataRow("cas", { align: "center", minLabelHeightMm: 22 }),
      dataRow("lot", { align: "center", spacingBefore: 0.5 }),
      dataRow("retest", { align: "center" }),
      noticeRow({ align: "center" }),
      volumeRow("footer", { align: "center", spacingBefore: 0.4 }),
    ],
    codeCorner: "bottom-right",
    codePlacement: "footer-center",
    decor: [
      { kind: "band", edge: "top", heightFactor: 0.06, fill: { role: "accent" }, inset: true, minLabelHeightMm: 16 },
    ],
  }),
  defineTemplate({
    id: "research-compound",
    name: "Research Compound",
    family: "research-compound",
    familyName: "Research Compound",
    category: ["research", "laboratory"],
    mood: ["rail", "vertical", "technical"],
    vibe: { clinical: 2, bold: 1, futuristic: 1 },
    colorMode: "light",
    density: "standard",
    pairingId: "pharmaceutical",
    recommendedGlass: ["clear", "amber"],
    minHeightMm: 18,
    minWidthMm: 55,
    align: "left",
    verticalRow: {
      slot: "brand",
      edge: "left",
      font: "body",
      weight: 600,
      sizeFactor: 0.09,
      minPt: 4.5,
      color: "muted",
      letterSpacingEm: 0.2,
      casing: "uppercase",
    },
    rows: [
      productHero(0.16),
      { slot: "strength", zone: "hero", font: "body", weight: 600, sizeFactor: 0.07, minPt: 4.5, maxLines: 1, color: "onAccent", chip: "fill", spacingBefore: 1 },
      noticeRow({ spacingBefore: 0.9 }),
      dataRow("catalog", { spacingBefore: 0.5 }),
      dataRow("lot"),
      dataRow("batch"),
      volumeRow("footer", { spacingBefore: 0.35 }),
    ],
    codeCorner: "bottom-right",
    codePlacement: "side",
    decor: [
      { kind: "side-rail", edge: "left", insetMm: 1.1, strokePt: 1.1, color: "accent" },
    ],
  }),
  defineTemplate({
    id: "amino-grid",
    name: "Amino Grid",
    family: "amino-grid",
    familyName: "Amino Grid",
    category: ["research", "laboratory"],
    mood: ["grid", "indexed", "compact"],
    vibe: { clinical: 2, minimal: 2 },
    colorMode: "light",
    density: "standard",
    pairingId: "grotesk-minimal",
    recommendedGlass: ["clear"],
    minHeightMm: 20,
    minWidthMm: 52,
    align: "left",
    split: { ratio: 0.5 },
    rows: [
      brandCaps(),
      productHero(0.145),
      strengthRow({ spacingBefore: 0.7 }),
      noticeRow({ maxLines: 2 }),
      dataRow("catalog", { zone: "header", column: "right", weight: 600, color: "text", spacingBefore: 0 }),
      dataRow("sku", { column: "right", spacingBefore: 0.3 }),
      dataRow("lot", { column: "right" }),
      dataRow("batch", { column: "right" }),
      dataRow("produced", { column: "right" }),
      dataRow("storage", { font: "body", column: "right", maxLines: 2, spacingBefore: 0.45 }),
    ],
    codeCorner: "bottom-right",
    decor: [
      { kind: "corners", lengthMm: 2.4, strokePt: 0.8, color: "muted", insetMm: 1.1, minLabelHeightMm: 15 },
    ],
  }),
  defineTemplate({
    id: "bioactive-index",
    name: "Bioactive Index",
    family: "bioactive-index",
    familyName: "Bioactive Index",
    category: ["research", "clinical"],
    mood: ["indexed", "underline", "quiet"],
    vibe: { clinical: 2, minimal: 2 },
    colorMode: "light",
    density: "standard",
    pairingId: "neutral-inter",
    recommendedGlass: ["clear", "frosted"],
    align: "left",
    rows: [
      brandCaps(),
      { slot: "catalog", zone: "header", font: "technical", sizeFactor: 0.044, minPt: 4, maxLines: 1, color: "muted", spacingBefore: 0.35 },
      productHero(0.15),
      { slot: "purity", zone: "hero", font: "body", weight: 600, sizeFactor: 0.055, minPt: 4.5, maxLines: 1, color: "accent", chip: "outline", spacingBefore: 0.9 },
      strengthRow({ color: "text", spacingBefore: 0.7 }),
      dataRow("storage", { font: "body", maxLines: 2, spacingBefore: 0.5 }),
      dataRow("lot"),
      dataRow("retest"),
      noticeRow(),
      volumeRow("footer", { spacingBefore: 0.35 }),
    ],
    codeCorner: "bottom-right",
    decor: [
      { kind: "underline-hero", widthFactor: 0.32, strokePt: 1.1, fill: { role: "accent" } },
    ],
  }),
  defineTemplate({
    id: "peptide-registry",
    name: "Peptide Registry",
    family: "peptide-registry",
    familyName: "Peptide Registry",
    category: ["research", "pharmaceutical"],
    mood: ["registry", "boxed", "formal"],
    vibe: { clinical: 3, premium: 1 },
    colorMode: "light",
    density: "standard",
    pairingId: "modern-clinical",
    recommendedGlass: ["clear", "cobalt"],
    minHeightMm: 20,
    align: "center",
    codePlacement: "footer-center",
    rows: [
      brandCaps({ align: "center", letterSpacingEm: 0.22 }),
      productHero(0.14, { align: "center" }),
      { slot: "abbreviation", zone: "hero", font: "technical", weight: 600, sizeFactor: 0.05, minPt: 4, maxLines: 1, color: "muted", letterSpacingEm: 0.18, spacingBefore: 0.6 },
      strengthRow({ align: "center", spacingBefore: 0.7 }),
      noticeRow({ align: "center" }),
      dataRow("lot", { align: "center", spacingBefore: 0.5 }),
      dataRow("batch", { align: "center" }),
      dataRow("produced", { align: "center" }),
      volumeRow("footer", { align: "center", spacingBefore: 0.4 }),
    ],
    codeCorner: "bottom-right",
    decor: [
      { kind: "border", insetMm: 0.9, strokePt: 0.8, color: "border", minLabelHeightMm: 14 },
    ],
  }),
  defineTemplate({
    id: "compound-series",
    name: "Compound Series",
    family: "compound-series",
    familyName: "Compound Series",
    category: ["research", "laboratory"],
    mood: ["abbreviation-kicker", "bold", "series"],
    vibe: { bold: 2, clinical: 2 },
    colorMode: "light",
    density: "standard",
    pairingId: "bold-modern",
    recommendedGlass: ["clear", "amber"],
    minHeightMm: 16,
    align: "left",
    rows: [
      brandCaps(),
      { slot: "abbreviation", zone: "hero", font: "display", sizeFactor: 0.075, minPt: 4.5, maxLines: 1, color: "accent", letterSpacingEm: 0.12, casing: "uppercase" },
      { slot: "product-name", zone: "hero", font: "display", sizeFactor: 0.17, minPt: 7.5, maxLines: 2, color: "text", spacingBefore: 0.5 },
      { slot: "strength", zone: "hero", font: "body", weight: 600, sizeFactor: 0.065, minPt: 4.5, maxLines: 1, color: "onAccent", chip: "fill", spacingBefore: 0.9 },
      noticeRow({ spacingBefore: 1.2 }),
      dataRow("lot", { spacingBefore: 0.45 }),
      dataRow("batch"),
      volumeRow("footer", { color: "text", weight: 600, spacingBefore: 1.2 }),
    ],
    codeCorner: "bottom-right",
    decor: [
      { kind: "stripe", edge: "left", widthFactor: 0.045, fill: { role: "accent" } },
    ],
  }),
  defineTemplate({
    id: "laboratory-peptide",
    name: "Laboratory Peptide",
    family: "laboratory-peptide",
    familyName: "Laboratory Peptide",
    category: ["research", "laboratory"],
    mood: ["two-column", "notice-forward", "technical"],
    vibe: { clinical: 3, futuristic: 1 },
    colorMode: "light",
    density: "standard",
    pairingId: "tech-lab",
    recommendedGlass: ["clear"],
    minHeightMm: 20,
    minWidthMm: 55,
    align: "left",
    split: { ratio: 0.55, divider: true },
    rows: [
      brandCaps({ letterSpacingEm: 0.12 }),
      productHero(0.155),
      { slot: "formula", zone: "hero", font: "technical", sizeFactor: 0.044, minPt: 4, maxLines: 1, color: "muted", spacingBefore: 0.6 },
      strengthRow({ spacingBefore: 0.7 }),
      noticeRow({ zone: "header", column: "right", spacingBefore: 0, align: "left" }),
      dataRow("storage", { font: "body", column: "right", maxLines: 2, spacingBefore: 0.5 }),
      dataRow("lot", { column: "right", spacingBefore: 0.45 }),
      dataRow("batch", { column: "right" }),
      dataRow("retest", { column: "right" }),
      volumeRow("footer", { spacingBefore: 0.35 }),
    ],
    codeCorner: "bottom-right",
    decor: [],
  }),
  defineTemplate({
    id: "research-vial-standard",
    name: "Research Vial Standard",
    family: "research-vial-standard",
    familyName: "Research Vial Standard",
    category: ["research", "pharmaceutical"],
    mood: ["canonical", "banded", "trustworthy"],
    vibe: { clinical: 3, minimal: 1 },
    colorMode: "light",
    density: "standard",
    pairingId: "pharmaceutical",
    recommendedGlass: ["clear", "amber", "cobalt"],
    featured: true,
    align: "left",
    rows: [
      brandCaps({ letterSpacingEm: 0.16 }),
      productHero(0.16),
      strengthRow({ spacingBefore: 0.8 }),
      volumeRow("hero", { spacingBefore: 0.5 }),
      noticeRow(),
      dataRow("lot", { spacingBefore: 0.5 }),
      dataRow("batch"),
      dataRow("storage", { font: "body", maxLines: 2 }),
    ],
    codeCorner: "bottom-right",
    decor: [
      { kind: "band", edge: "bottom", heightFactor: 0.055, fill: { gradient: true } },
    ],
  }),
] as const;
